#!/usr/bin/env python3
"""cut2_appH.py -- compress Appendix H toward the register form: every constant, citation, verification count, defect and
rule kept; explanatory repetition of Chapter 3 removed."""
P = "/home/claude/work/src/docs/chapters/appendix_h.md"
t = open(P, encoding="utf-8").read()
before = len(t.split())
def sub1(old, new):
    global t
    assert t.count(old) == 1, (old[:70], t.count(old)); t = t.replace(old, new)

sub1("This appendix holds, in full, the material that sections 3.7 and 3.12 state in summary — the evidence behind every constant in the risk-adjustment chain, its mechanical verification, and the derivations behind the calibration architecture — and the two diagnostic records that section 3.10 reports in summary. Sources are cited by their numbers in the thesis-wide reference list.",
     "This appendix holds in full what sections 3.7 and 3.12 state in summary — the evidence behind every constant in the risk-adjustment chain, its mechanical verification and the derivations behind the calibration architecture — and the two diagnostic records that section 3.10 reports in summary.")
# H.1
sub1("After the ×4.0 removal the chain was re-verified mechanically over a 1,440-case grid — twelve ages, three contexts, five family-history states and eight speech scores — against nine registered properties: monotone in speech score; monotone in age prevalence; population context never exceeding the concern context; the Bayes identity; neutrality at `TRAINING_PRIOR`; the posterior bounded in (0, 1); the effective prior bounded by the cap; the concern and clinical contexts identical with the clinical branch flagged as a floor; and no surviving ×4.0 anywhere. All 1,440 cases passed with zero failures (`results/reconstruction/bayes_chain_check.json`). The same speech score of 0.90 yields a posterior of 4.8% at age 25 and 92.5% at age 85, and a 72-year-old scoring 0.70 receives 0.316 at ×1.0 and 0.536 at ×2.5, against 0.649 under the retired ×4.0.",
     "After the ×4.0 removal the chain was re-verified mechanically over a 1,440-case grid — twelve ages, three contexts, five family-history states and eight speech scores — against nine registered properties: monotone in speech score; monotone in age prevalence; population context never exceeding the concern context; the Bayes identity; neutrality at `TRAINING_PRIOR`; the posterior bounded in (0, 1); the effective prior bounded by the cap; the concern and clinical contexts identical with the clinical branch flagged as a floor; and no surviving ×4.0 anywhere. All 1,440 cases passed (`results/reconstruction/bayes_chain_check.json`); the worked values are those of section 3.7.")
# H.2
sub1("The prior must match what the model detects, not a narrower condition: the training pool's impaired class contained 234 probable-Alzheimer's, 42 MCI, 21 possible-Alzheimer's, 5 vascular and 3 memory-clinic cases, so the instrument detects cognitive impairment broadly and the correct prior is the prevalence of MCI plus dementia. An earlier version used dementia-only prevalence and systematically understated risk, because MCI is roughly twice as common as dementia at the ages that matter most for early detection. Table (H.1) gives the deployed bands.",
     "The prior must match what the model detects: the training pool's impaired class contained 234 probable-Alzheimer's, 42 MCI, 21 possible-Alzheimer's, 5 vascular and 3 memory-clinic cases, so the instrument detects cognitive impairment broadly and the correct prior is the prevalence of MCI plus dementia. An earlier version used dementia-only prevalence and systematically understated risk, since MCI is roughly twice as common as dementia at the ages that matter most for early detection. Table (H.1) gives the deployed bands.")
# H.3
sub1("The ×2.5 concern multiplier was asserted as an engineering assumption before any source was sought, and support was found afterwards — the true order of events, stated as such. The supporting derivation is Mitchell's cross-sectional meta-analysis [4], cross-sectional being the right object for a *prevalence* prior, which reports subjective memory complaint in 39.8% of those with any cognitive impairment against 17.4% of healthy elderly; positive likelihood ratios derived from its published sensitivity and specificity are **2.29 for MCI-or-dementia**, 2.85 for MCI alone and 3.03 for dementia alone. Two longitudinal meta-analyses corroborate the magnitude without being the derivation, RR 2.07 on n = 29,723 [5] and OR 2.48 with HR 1.90 on n > 74,000 [6]. Caveats run both ways: Mitchell's specificity is computed largely against healthy controls, which inflates the likelihood ratio, while a person who presents *because* they noticed a change is more strongly selected than a survey respondent, so 2.3 is plausibly a floor.",
     "The ×2.5 concern multiplier was asserted as an engineering assumption before any source was sought, and support was found afterwards — the true order of events. The supporting derivation is Mitchell's cross-sectional meta-analysis [4], cross-sectional being the right object for a *prevalence* prior, which reports subjective memory complaint in 39.8% of those with any cognitive impairment against 17.4% of healthy elderly; positive likelihood ratios derived from its published sensitivity and specificity are **2.29 for MCI-or-dementia**, 2.85 for MCI alone and 3.03 for dementia alone. Two longitudinal meta-analyses corroborate the magnitude without being the derivation, RR 2.07 on n = 29,723 [5] and OR 2.48 with HR 1.90 on n > 74,000 [6]. Caveats run both ways: Mitchell's specificity is computed largely against healthy controls, which inflates the ratio, while a person who presents *because* they noticed a change is more strongly selected than a survey respondent, so 2.3 is plausibly a floor.")
sub1("The indirect evidence therefore says ×4.0 was, if anything, too low; the multiplier was removed anyway because the same audit that yields the 84% figure found dementia yield ranging from 22% to 100% across its 85 services, in one country, in one year [9]: a referral rate is a local policy variable, not a property of the person in the room, and the comparison is additionally between studies, countries, health systems and diagnostic constructs. Two structural points complete the record — the referral contexts are mutually exclusive branches, one per session, because nearly everyone a clinician refers also has a subjective complaint; and a multiplier and its baseline prior are a matched pair, so against a prior already conditioned on age the implied clinic uplift shrinks from roughly 8 to roughly 4–5. One citation was withdrawn in this branch: the code had cited a \"clinic-vs-community MCI systematic review\" for clinic rates several times the community rate, and the paper [15] reports the opposite for prevalence — MCI prevalence is *higher* in community samples than clinic samples, what is higher in clinics is progression — and publishes no ratio; the finding is a composition artefact with respect to the composite endpoint, so it refutes the citation, not a referral effect.",
     "The indirect evidence therefore says ×4.0 was, if anything, too low; the multiplier was removed anyway because the same audit that yields the 84% figure found dementia yield ranging from 22% to 100% across its 85 services, in one country, in one year [9]: a referral rate is a local policy variable, not a property of the person in the room, and the comparison is additionally between studies, countries, health systems and diagnostic constructs. The structural points are those of section 3.7 — mutually exclusive referral branches, and a multiplier matched to its baseline prior, so that the implied clinic uplift shrinks from roughly 8 to roughly 4–5 against an age-conditioned prior. One citation was withdrawn in this branch: the code had cited a \"clinic-vs-community MCI systematic review\" for clinic rates several times the community rate, and the paper [15] reports the opposite for prevalence — MCI prevalence is *higher* in community samples than clinic samples, what is higher in clinics is progression — and publishes no ratio; the finding is a composition artefact with respect to the composite endpoint, so it refutes the citation, not a referral effect.")
# H.4
sub1("A reported *no* leaves the prior unchanged rather than lowering it: where diagnosis is scarce, *no* frequently means *nobody in this family was ever diagnosed*, and treating it as protective would penalise precisely the families with the least access to diagnosis. An objection to this branch — that under-diagnosis makes a *yes* mean different things in different settings, the retired ×4.0's defect — was written out and does not hold: with D a truly affected relative, Y the answer *yes* and *a* the ascertainment rate, P(Y | R) = *a* · P(D | R) and P(Y | not R) = *a* · P(D | not R), so the ascertainment rate multiplies both arms of the likelihood ratio and cancels, provided under-ascertainment is non-differential; low ascertainment makes *yes* rarer, not less meaningful, where a referral rate determines who enters the tested population at all. The residual differential mechanism — diagnostic access tracking education, which is protective — would bias the ratio downward, meaning 1.73 is if anything too high, and is worth this sentence and no change.",
     "A reported *no* leaves the prior unchanged rather than lowering it: where diagnosis is scarce, *no* frequently means *nobody in this family was ever diagnosed*, and treating it as protective would penalise the families with the least access to diagnosis. An objection to this branch — that under-diagnosis makes a *yes* mean different things in different settings, the retired ×4.0's defect — was written out and does not hold: with D a truly affected relative, Y the answer *yes* and *a* the ascertainment rate, P(Y | R) = *a* · P(D | R) and P(Y | not R) = *a* · P(D | not R), so the ascertainment rate multiplies both arms of the likelihood ratio and cancels, provided under-ascertainment is non-differential; low ascertainment makes *yes* rarer, not less meaningful. The residual differential mechanism — diagnostic access tracking education, which is protective — would bias the ratio downward, so 1.73 is if anything too high, and is worth this sentence and no change.")
sub1("The defect that is real is sharper. The published figures are *relative risks*, the chain multiplies prior *odds*, and RR ≈ OR only while baseline risk is small, which these bands do not stay: RR 3.98 against the 85-and-over prevalence of 0.550 implies a risk of 2.19 on the risk scale, which is impossible. `MAX_PRIOR` = 0.85 is the symptom rather than a prudence measure: it binds in exactly 4 of the 135 prior combinations — two-or-more-relative cases at ages 80–85 (uncapped prior 0.878) and 85 and over (uncapped 0.924), under either uplift — and in none of the 45 combinations without a referral multiplier. The arithmetic was not changed, because the correct alternative, composing on the risk scale with a ceiling, still requires an arbitrary ceiling and would invalidate the completed 1,440-case verification. The defect is documented with its direction: an age-averaged RR composed with an age-specific prevalence **overstates familial risk at the oldest ages and understates it around 60**, because familial loading is stronger for earlier onset.",
     "The real defect is sharper. The published figures are *relative risks*, the chain multiplies prior *odds*, and RR ≈ OR only while baseline risk is small, which these bands do not stay: RR 3.98 against the 85-and-over prevalence of 0.550 implies a risk of 2.19, which is impossible. `MAX_PRIOR` = 0.85 is the symptom rather than a prudence measure: it binds in exactly 4 of the 135 prior combinations — two-or-more-relative cases at ages 80–85 (uncapped prior 0.878) and 85 and over (uncapped 0.924), under either uplift — and in none of the 45 combinations without a referral multiplier. The arithmetic was not changed, because the correct alternative, composing on the risk scale with a ceiling, still requires an arbitrary ceiling and would invalidate the completed 1,440-case verification. The defect is documented with its direction: an age-averaged RR composed with an age-specific prevalence **overstates familial risk at the oldest ages and understates it around 60**, because familial loading is stronger for earlier onset.")
# H.5
sub1("Section 3.12 states three consequences of the likelihood-ratio reading; this section carries them. **Cox recalibration decomposes into two failures.** Recalibration fits logit *p*\\* = *a* + *b* · logit *p*, and Table (H.2) gives what each coefficient means under the density-ratio reading: *b* rescales the log-likelihood ratio, the strength of the evidence, and *a* the implied prior. Pittsburgh returned a slope of 1.516 and Delaware 0.823 — not merely that calibration does not transfer, but that evidence strength itself is corpus-dependent and in opposite directions, so one global recalibration cannot repair two errors of opposite sign, which is why section 3.9.2's pre-registered decision and the mathematics reached the same conclusion independently.",
     "Section 3.12 states three consequences of the likelihood-ratio reading; this section carries them. **Cox recalibration decomposes into two failures.** Recalibration fits logit *p*\\* = *a* + *b* · logit *p*, and Table (H.2) gives what each coefficient means under the density-ratio reading. Pittsburgh returned a slope of 1.516 and Delaware 0.823 — not merely that calibration does not transfer, but that evidence strength itself is corpus-dependent and in opposite directions, so one global recalibration cannot repair two errors of opposite sign, which is why section 3.9.2's pre-registered decision and the mathematics reached the same conclusion independently.")
sub1("**The model's evidence is age-flat within class.** Age is recoverable from the deployed features at *R*² = 0.994, so an age-specific prevalence multiplied onto the model's evidence could double-count age; the measurement, recomputed after the lock from the stored out-of-fold vector by the committed `scripts/age_flatness_check.py` (`results/reconstruction/age_flatness_check.json`), is given in Table (H.4). Within each class the evidence is approximately age-flat and the drift runs the wrong way for double-counting; the pooled +0.091 is the legitimate label signal of impaired participants being older *and* scoring higher, not leakage into the evidence term.",
     "**The model's evidence is age-flat within class.** Age is recoverable from the deployed features at *R*² = 0.994, so an age-specific prevalence multiplied onto the model's evidence could double-count age; the measurement, recomputed after the lock from the stored out-of-fold vector by the committed `scripts/age_flatness_check.py` (`results/reconstruction/age_flatness_check.json`), is Table (H.4): within each class the evidence is approximately age-flat and the drift runs the wrong way for double-counting, and the pooled +0.091 is the legitimate label signal of impaired participants being older *and* scoring higher, not leakage into the evidence term.")
# H.6
sub1("It failed, reproducing the committed feature on 36% of Pittsburgh and 82% of Delaware recordings, and the diagnosis proceeded by elimination: pronoun counts matched the committed values almost exactly (r = 0.9995 in both cohorts), so the tagger was not the problem; the committed Delaware extractor re-run on forty of its own inputs reproduced its committed output to the last digit, so environment drift was not the problem — the step that matters, because without it the comfortable conclusion would have been a library version; and reading the committed source line by line found that `linguistic_features.py:48` filters `words = [t for t in doc if t.is_alpha]` and the new script did not, so punctuation, contraction fragments and numerals were inflating the denominator. The defect was in the new script, measured against its own registered definition; fixing it honoured the registration, and after the fix the check passes at 100% in both cohorts. One cohort's result block had appeared in terminal output by then, which is recorded in the driver's registration history in those words, with the reasons it does not void the run — the fix was determined by reading the committed source rather than by the result, and no criterion or threshold moved — and with the sentence *the reader is entitled to weigh that*.",
     "It failed, reproducing the committed feature on 36% of Pittsburgh and 82% of Delaware recordings, and the diagnosis proceeded by elimination: pronoun counts matched the committed values almost exactly (r = 0.9995 in both cohorts), so the tagger was not the problem; the committed Delaware extractor re-run on forty of its own inputs reproduced its committed output to the last digit, so environment drift was not the problem — the step that matters, since without it the comfortable conclusion would have been a library version; and reading the committed source line by line found that `linguistic_features.py:48` filters `words = [t for t in doc if t.is_alpha]` and the new script did not, so punctuation, contraction fragments and numerals were inflating the denominator. The defect was in the new script; fixing it honoured the registration, and after the fix the check passes at 100% in both cohorts. One cohort's result block had appeared in terminal output by then, which the driver's registration history records in those words, with the reasons it does not void the run — the fix was determined by reading the committed source rather than by the result, and no criterion or threshold moved — and with the sentence *the reader is entitled to weigh that*.")
sub1("The claim reversed sign once both sides were estimated alike. Nothing in a registration template asks whether a comparator was selected — the registration would have been unimpeachable and the arithmetic reproduces — so the defect was in the comparison, and it was caught only because the claim was uncomfortable enough to invite challenge.",
     "The claim reversed sign once both sides were estimated alike. Nothing in a registration template asks whether a comparator was selected — the registration would have been unimpeachable and the arithmetic reproduces — so the defect was in the comparison, caught only because the claim was uncomfortable enough to invite challenge.")
# H.7
sub1("Of seventeen registered runs — a count verified mechanically by `scripts/check_counts.py`, which counts the scripts carrying a registration docstring and flags any prose claim that disagrees — three required amendment on contact with the data, as Table (H.5) records with the timing of each amendment relative to seeing the result.",
     "Of seventeen registered runs — a count verified mechanically by `scripts/check_counts.py`, which counts the scripts carrying a registration docstring and flags any prose claim that disagrees — three required amendment on contact with the data, as Table (H.5) records with the timing of each amendment relative to seeing the result.")
sub1("Pre-registration in work of this kind is revised on contact with data considerably more often than the published literature suggests, because what gets published is the registrations that held. The discipline that matters is therefore not *never amend* but four rules that can be kept. First, never adjust the rule to reach the assertion: the retention criterion was left standing and uninterpretable rather than rewritten into something that would have graded cleanly. Second, record when an amendment was made relative to seeing the result, in the words a sceptical reader would use. Third, report both versions whenever an amendment changes an answer, as the task-count analysis does for its two label rules. Fourth, register a sanity gate on every derived quantity an analysis depends on, including its labels: the tokenisation defect was caught by exactly such a gate, the label defect was not caught because no gate had been placed on the labels, and every registration written after that episode carries one. The comparison defect extends the fourth rule from derived quantities to comparisons: register how each side of every comparison was arrived at, and refuse any comparison whose two sides were produced by procedures with different numbers of free parameters.",
     "Pre-registration in work of this kind is revised on contact with data more often than the published literature suggests, because what gets published is the registrations that held; the discipline that matters is therefore not *never amend* but four rules that can be kept. First, never adjust the rule to reach the assertion: the retention criterion was left standing and uninterpretable rather than rewritten into something that would have graded cleanly. Second, record when an amendment was made relative to seeing the result, in the words a sceptical reader would use. Third, report both versions whenever an amendment changes an answer, as the task-count analysis does for its two label rules. Fourth, register a sanity gate on every derived quantity an analysis depends on, including its labels: the tokenisation defect was caught by such a gate, the label defect was not because no gate had been placed on the labels, and every registration written after that episode carries one. The comparison defect extends the fourth rule to comparisons: register how each side was arrived at, and refuse any comparison whose two sides were produced by procedures with different numbers of free parameters.")

open(P, "w", encoding="utf-8").write(t)
print("appendix_h words", before, "->", len(t.split()))
