#!/usr/bin/env python3
"""cut2_flips3.py -- third flip pass: Chapter 2 and Appendix B. Whitespace-normalised matching; numbers and caveats kept."""
import re
ROOT = "/home/claude/work/src/docs/chapters/"
FILES = {"c2": ROOT + "chapter2.md", "B": ROOT + "_pending/appendix_b.md"}
T = {k: open(v, encoding="utf-8").read() for k, v in FILES.items()}
Bw = {k: len(v.split()) for k, v in T.items()}
def ws(s): return r"\s+".join(re.escape(w) for w in s.split())
def rep(f, old, new):
    pat = ws(old); n = len(re.findall(pat, T[f]))
    assert n == 1, (f, old[:70], n)
    T[f] = re.sub(pat, lambda m: new, T[f])

# ---- Chapter 2 ----
rep("c2", "One line in the table belongs to this work alone: no system in it reports an external validation of any kind, and on the locked external corpus the best accuracy any threshold could achieve is 0.792, collected by different investigators in a different setting and scored exactly once at a threshold fixed in advance. Figures above 0.90 are reached only by protocols that are not subject-independent, or by transformers, or both; 0.93 is not the bar because it is not measuring the same thing.",
    "One line in the table belongs to this work alone: no system in it reports an external validation of any kind, and on the locked external corpus the best accuracy any threshold could achieve is 0.792, collected by different investigators in a different setting and scored exactly once at a threshold fixed in advance; 0.93 is not the bar because it is not measuring the same thing.")
rep("c2", "What this licenses is stated exactly. It does not license the claim that Dhikra is more accurate than the models reporting 0.93 or 0.95 — that comparison is not available in either direction, and this thesis does not imply it. It licenses the claim that Dhikra's number was obtained under an evaluation condition the higher published numbers have not been tested under, and that when others tested that condition, performance collapsed: a claim about evidence, not about superiority.",
    "What this licenses is stated exactly. It does not license the claim that Dhikra is more accurate than the models reporting 0.93 or 0.95 — that comparison is not available in either direction. It licenses the claim that Dhikra's number was obtained under an evaluation condition the higher published numbers have not been tested under, and that when others tested that condition, performance collapsed: a claim about evidence, not about superiority.")
rep("c2", "The features of this literature sort into three tiers by what a positive finding means: clinically motivated measures — information units, idea density, lexical diversity, syntactic complexity, reference and cohesion — which connect a classifier's behaviour to constructs the clinical literature already interprets and are the tier this project deploys (section 3.3);",
    "The features of this literature sort into three tiers by what a positive finding means: clinically motivated measures — information units, idea density, lexical diversity, syntactic complexity, reference and cohesion — the tier this project deploys, because each connects to a construct the clinical literature already interprets (section 3.3);")
rep("c2", "The nearest linguistically serious work is Taiebine and El Alaoui Faris's adaptation and preliminary validation of the Mini-Linguistic State Examination for Moroccan Arabic, with their earlier acoustic and neurolinguistic case study of logopenic primary progressive aphasia in Arabic — instrument adaptation and case description, not automated screening [17, 18]. Outside Arabic, the DementiaBankHindi effort is a precedent for creating a non-English resource for exactly this task, which is what section 6.5's specification asks of Arabic [19].",
    "The nearest linguistically serious work is Taiebine and El Alaoui Faris's adaptation of the Mini-Linguistic State Examination for Moroccan Arabic and their case study of logopenic primary progressive aphasia in Arabic — instrument adaptation and case description, not automated screening [17, 18]. Outside Arabic, DementiaBankHindi is a precedent for creating a non-English resource for exactly this task, as section 6.5's specification asks of Arabic [19].")
rep("c2", "Both clauses are stated at exactly that strength: the searches behind them, with their limits and the near-misses on either side of the gap, are documented in section 6.4, and a single counterexample retires the claim. What the two arguments of this chapter jointly establish is the thesis's position. The field reports high figures",
    "Both clauses are stated at exactly that strength: the searches behind them are documented in section 6.4, and a single counterexample retires the claim. The two arguments of this chapter jointly fix the thesis's position: the field reports high figures")
rep("c2", "Two properties of this landscape matter here. First, the reported figures are accuracies at an operating point, while this thesis's primary figures are AUCs — threshold-free ranking statistics — and the two are not directly comparable; section 2.3.2 keeps the metrics explicit for exactly that reason. Second,",
    "Two properties of this landscape matter here. First, the reported figures are accuracies at an operating point, while this thesis's primary figures are AUCs — threshold-free ranking statistics — and the two are not directly comparable, which is why section 2.3.2 names the metric in every row. Second,")
rep("c2", "The ADReSS challenge distributed an age- and sex-balanced subset of Pittsburgh, 156 recordings, with a 48-recording held-out test set, and became the field's de facto benchmark [7]. The Delaware corpus contributes a five-task protocol administered to both mild-impairment and control speakers; the Wisconsin Longitudinal Study contributes recorded interviews from a large healthy cohort.",
    "The ADReSS challenge distributed an age- and sex-balanced subset of Pittsburgh, 156 recordings with a 48-recording held-out test set, and became the field's de facto benchmark [7]; the Delaware corpus contributes a five-task protocol administered to both mild-impairment and control speakers, and the Wisconsin Longitudinal Study recorded interviews from a large healthy cohort.")

# ---- Appendix B ----
rep("B", "The secondary outcomes are descriptive: the distribution of each Arabic feature in the healthy stratum, as median and observed range rather than percentiles unless n ≥ 30; word-list validation, every filler, vague noun and demonstrative actually produced against the drafted lists; whether the referential deficit index behaves as intended on real Libyan speech; the recitation probe's completion, surah and familiarity distributions; and a provisional Libyan operating threshold, the 80th percentile of the healthy stratum's score distribution, reported with its exact Beta interval and labelled provisional at n < 30.",
    "The secondary outcomes are descriptive: each Arabic feature's distribution in the healthy stratum, as median and range unless n ≥ 30; word-list validation, every filler, vague noun and demonstrative produced against the drafted lists; whether the referential deficit index behaves as intended on Libyan speech; the recitation probe's completion, surah and familiarity distributions; and a provisional Libyan operating threshold, the 80th percentile of the healthy stratum's score distribution, with its exact Beta interval, labelled provisional at n < 30.")
rep("B", "For every participant the information-unit count from the kitchen scene is computed with its per-unit indicators; the report gives each unit's production rate with an exact binomial interval, the units produced by fewer than 5% of the healthy stratum — the operational definition of a unit the picture fails to elicit, reported as such and carried into any future revision of the artwork, never removed from the scorer, which computes the frozen model's input — and the healthy stratum's total-unit distribution against the Pittsburgh control distribution, compared as full distributions. The comparison cannot separate stimulus from population, language and era, so it is reported as a bound: comparable production means the substitution is probably not costing much; markedly lower production means the cause is unidentified and the threshold must be re-derived locally rather than inherited.",
    "For every participant the information-unit count from the kitchen scene is computed with its per-unit indicators; the report gives each unit's production rate with an exact binomial interval, the units produced by fewer than 5% of the healthy stratum — the operational definition of a unit the picture fails to elicit, carried into any future revision of the artwork and never removed from the scorer, which computes the frozen model's input — and the healthy stratum's total-unit distribution against the Pittsburgh control distribution. The comparison cannot separate stimulus from population, language and era, so it is reported as a bound: comparable production means the substitution is probably not costing much; markedly lower production means the cause is unidentified and the threshold must be re-derived locally.")
rep("B", "Fewer words than the English reference distribution would be expected, since Arabic conveys in fewer orthographic words what English spreads across more, and would be a reason to derive the threshold from local controls, not to doubt the measure.",
    "Fewer words than the English reference distribution would be expected, since Arabic conveys in fewer orthographic words what English spreads across more — a reason to derive the threshold from local controls, not to doubt the measure.")
rep("B", "**Explicitly not an outcome.** Diagnostic accuracy, sensitivity, specificity or AUC, and any claim that the system detects impairment in Arabic. A threshold derived from the healthy stratum has a specificity known by construction, with a stated interval; it does not measure specificity, says nothing about sensitivity, makes no accuracy claim, and its Beta interval is never reported as a validation result.",
    "**Explicitly not an outcome.** Diagnostic accuracy, sensitivity, specificity or AUC, and any claim that the system detects impairment in Arabic; a threshold derived from the healthy stratum has a specificity known by construction, with a stated interval, says nothing about sensitivity, and its Beta interval is never reported as a validation result.")
rep("B", "Descriptive statistics only for the primary outcomes; healthy-stratum feature distributions as median and range; if both strata reach n ≥ 15, an exploratory group comparison with effect sizes and confidence intervals, labelled hypothesis-generating; no classifier trained on this sample, because 24 participants in this project's own pilot produced results from AUC 0.420 to 0.655 depending only on model choice; and the 80th percentile of the healthy stratum's screening-score distribution reported with its exact Beta(k, n+1−k) interval — an order statistic of a single group, not a fitted quantity, fixed before any group comparison is run and reported whatever that comparison shows.",
    "Descriptive statistics only for the primary outcomes; healthy-stratum feature distributions as median and range; if both strata reach n ≥ 15, an exploratory group comparison with effect sizes and confidence intervals, labelled hypothesis-generating; no classifier trained on this sample, because 24 participants in this project's own pilot produced results from AUC 0.420 to 0.655 depending only on model choice; and the 80th percentile of the healthy stratum's screening-score distribution with its exact Beta(k, n+1−k) interval — an order statistic of a single group, fixed before any group comparison is run and reported whatever that comparison shows.")
rep("B", "The realistic timeline is one week to prepare the ethics submission, two to eight weeks of committee review outside the researcher's control, one to two weeks of clinic scheduling, three to six weeks of collection for 20 to 40 participants and one week of analysis; it cannot be completed before the thesis deadline, so the protocol is submitted",
    "The realistic timeline — one week to prepare the ethics submission, two to eight weeks of committee review, one to two weeks of clinic scheduling, three to six weeks of collection for 20 to 40 participants and one week of analysis — cannot be completed before the thesis deadline, so the protocol is submitted")
rep("B", "**The scoring rule.** The automated information-unit scorer was graded INADEQUATE against a human on 20 transcripts, a near-constant undercount of about 1.5 units with rank order preserved (section 5.5.1), so every scorer is trained against the committed coding rules (`docs/scorer_check/CODING_RULES.md`) before collection begins, a subsample of at least ten sessions is double-scored by a second person, and the paper instrument takes its cut-off from hand-scored local controls and never from the software's.",
    "**The scoring rule.** The automated information-unit scorer was graded INADEQUATE against a human on 20 transcripts, a near-constant undercount of about 1.5 units with rank order preserved (section 5.5.1), so every scorer is trained against the committed coding rules (`docs/scorer_check/CODING_RULES.md`), at least ten sessions are double-scored by a second person, and the paper instrument takes its cut-off from hand-scored local controls, never from the software's.")

for k, v in FILES.items():
    open(v, "w", encoding="utf-8").write(T[k]); print(k, "words", Bw[k], "->", len(T[k].split()))
