#!/usr/bin/env python3
"""cut2_ch6.py -- tighten Chapter 6 after cut_ch6.py/cut_ch6b.py: phrasing only, every number and caveat kept."""
P = "/home/claude/work/src/docs/chapters/chapter6.md"
t = open(P, encoding="utf-8").read()
before = len(t.split())
def sub1(old, new):
    global t
    assert t.count(old) == 1, (old[:70], t.count(old)); t = t.replace(old, new)

# preamble
sub1("and everything that concerns the successor rests on development evidence alone, under the rule of section 1.7, sharing no table with a validated figure. The claim the whole thesis has been assembling is stated first, as one claim: every costly decision in this work lowered a number.",
     "and everything that concerns the successor rests on development evidence alone, under the rule of section 1.7. The claim the whole thesis has been assembling is stated first: every costly decision in this work lowered a number.")
sub1("Two disciplines keep that list from congratulating itself: ungrouped folds were found to inflate nothing on this model class, so no such claim is made against the literature (section 3.6.1), and section 5.1.1 concedes that the whole modelling apparatus buys about 4.5 points of AUC over one hand-countable quantity. The development figure of 0.7550 was produced under every constraint above at once; it is not a modest result but an expensive one. The instrument that produced it extracts 117 speech and language measures across five families; its externally evaluated English screening model uses a frozen 64-feature transcript-derived subset of linguistic, information-content and discourse-semantic measures, and 53 acoustic measures support a separate language-independent pathway.",
     "Two disciplines keep that list from congratulating itself: ungrouped folds were found to inflate nothing on this model class, so no such claim is made against the literature (section 3.6.1), and the whole modelling apparatus buys about 4.5 points of AUC over one hand-countable quantity (section 5.1.1). The development figure of 0.7550 was produced under every constraint above at once; it is not a modest result but an expensive one. The instrument extracts 117 speech and language measures across five families; its externally evaluated English screening model uses a frozen 64-feature transcript-derived subset of linguistic, information-content and discourse-semantic measures, and 53 acoustic measures support a separate language-independent pathway.")

# 6.1
sub1("The contributions are listed with the methodological ones first, because they are exactly derived, usable by other groups, and independent of whether this particular model is any good. Appendix F grades every component on a levels-of-evidence register; each point below carries its evidential status in the same breath.",
     "The contributions are listed with the methodological ones first, because they are exactly derived, usable by other groups, and independent of whether this particular model is any good; Appendix F grades every component on a levels-of-evidence register, and each point below carries its evidential status.")
sub1("and the measured 79.8 / 79.9 / 77.8 across three cohorts illustrate the construction behaving as derived.",
     "and the measured 79.8 / 79.9 / 77.8 across three cohorts show the construction behaving as derived.")
sub1("The calibrated ensemble over 64 engineered features is the expensive part of the system — it needs a computer and cannot run on paper — and against a single-feature comparator selected inside each training fold it buys +0.0455 on the development target (0.7550 against 0.7096) and +0.0361 on mild-impairment discourse (0.6379 against 0.6018): roughly four points of AUC on both, and no \"four points versus nothing\", since the earlier appearance that the apparatus bought nothing on discourse came entirely from a comparator estimated differently from the model (section 5.16).",
     "The calibrated ensemble over 64 engineered features is the expensive part of the system — it needs a computer and cannot run on paper — and against a single-feature comparator selected inside each training fold it buys +0.0455 on the development target (0.7550 against 0.7096) and +0.0361 on mild-impairment discourse (0.6379 against 0.6018): roughly four points of AUC on both, not \"four points versus nothing\", since the earlier appearance that the apparatus bought nothing on discourse came from a comparator estimated differently from the model (section 5.16).")
sub1("On picture description the best single feature is the information-unit total in five folds of five, with selection optimism exactly zero, so the paper instruction — count the information units — is stable; on discourse no measure is stably best, so a field worker could not reliably be told what to count. Section 5.15 establishes that for mild impairment the discourse genre carries the signal and the picture task performs at chance, while the paper fallback is more dependable on the picture than on discourse. Table (6.1) states the resolution, which the pilot protocol of Appendix B implements: administer both genres, score discourse when the software is present, and count information units on the picture when it is not.",
     "On picture description the best single feature is the information-unit total in five folds of five, with selection optimism exactly zero, so the paper instruction — count the information units — is stable; on discourse no measure is stably best, so a field worker could not reliably be told what to count. Section 5.15 establishes that for mild impairment the discourse genre carries the signal and the picture task performs at chance, while the paper fallback is more dependable on the picture. Table (6.1) states the resolution, which the pilot protocol of Appendix B implements: administer both genres, score discourse when the software is present, and count information units on the picture when it is not.")
sub1("Before pooling two corpora, test whether a classifier can separate their healthy speakers; this project measured 0.930 between two healthy groups, traced it to transcription convention, and derived the rule that corpora are combined only when each contributes both classes (section 3.2.1). The answer is model-dependent — a published counter-case pooled the same corpora successfully under a contextual representation (section 2.3) — which is exactly why the test must be run per project.",
     "Before pooling two corpora, test whether a classifier can separate their healthy speakers; this project measured 0.930 between two healthy groups, traced it to transcription convention, and derived the rule that corpora are combined only when each contributes both classes (section 3.2.1). The answer is model-dependent — a published counter-case pooled the same corpora successfully under a contextual representation (section 2.3) — which is why the test must be run per project.")
sub1("The system declines to produce a result for audio below the level at which pause extraction was measured to fail, for a stimulus other than the calibrated one, for an Arabic session — no validated Arabic screening score exists — and for any use outside the model card's declared scope (sections 3.8 and 4.5). Encoding a competence boundary and enforcing it at runtime is rare in this literature, and it is a biomedical-engineering contribution rather than a machine-learning one.",
     "The system declines to produce a result for audio below the level at which pause extraction was measured to fail, for a stimulus other than the calibrated one, for an Arabic session — no validated Arabic screening score exists — and for any use outside the model card's declared scope (sections 3.8 and 4.5). Encoding a competence boundary and enforcing it at runtime is rare in this literature, and it is a biomedical-engineering contribution rather than a machine-learning one.")
sub1("Four defects arose in seventeen registered runs, every one in something the registration did not think it needed to state — a tokenisation rule, a denominator's interpretability, a label rule, and a comparison whose two sides were estimated by different procedures (section 3.10) — and the remedy is a rule any project can adopt: register a sanity gate on every derived quantity an analysis depends on, including its labels. The failure mode is this project's most transferable lesson: every defect this work found in its own analysis, artwork and deployment was silent — none raised an error, because each component met its contract, return a number, while the number's meaning had changed — and a component whose contract is to return a value cannot report that the value has stopped meaning what it meant, so something outside it must (sections 3.10 and 4.5.1).",
     "Four defects arose in seventeen registered runs, every one in something the registration did not think it needed to state — a tokenisation rule, a denominator's interpretability, a label rule, and a comparison whose two sides were estimated by different procedures (section 3.10) — and the remedy is a rule any project can adopt: register a sanity gate on every derived quantity an analysis depends on, including its labels. The failure mode is the project's most transferable lesson: every defect this work found in its own analysis, artwork and deployment was silent, because each component met its contract — return a number — while the number's meaning had changed; a component cannot report that its value has stopped meaning what it meant, so something outside it must (sections 3.10 and 4.5.1).")

# 6.2
sub1("**The instrument is wrong about roughly one person in three at its operating point** — accuracy about 67% on development data and 34 of 53 on the locked external set; the AUC of 0.7550 means that, given one impaired and one healthy recording, the model ranks the pair correctly about three times in four.",
     "**The instrument is wrong about roughly one person in three at its operating point** — accuracy about 67% on development data and 34 of 53 on the locked external set; an AUC of 0.7550 means that, given one impaired and one healthy recording, the model ranks the pair correctly about three times in four.")
sub1("diagnosed in section 5.13 as a threshold-referencing failure — the threshold landed at 96.2% sensitivity where the design intent was near 75%, and the eighteen misclassified controls had genuinely described the picture less well, so the model was not malfunctioning — and recovered to 77.8% by control-referenced thresholding. What remains after the diagnosis: the deployed system still carries 0.367; the remedy is analysed, not implemented, and was chosen after seeing the data; and the task-administration explanation for the false positives is a hypothesis, confounded with an 8.4-year age difference in a sample of 27.",
     "diagnosed in section 5.13 as a threshold-referencing failure — the threshold landed at 96.2% sensitivity where the design intent was near 75%, and the eighteen misclassified controls had described the picture less well, so the model was not malfunctioning — and recovered to 77.8% by control-referenced thresholding. What remains: the deployed system still carries 0.367; the remedy is analysed, not implemented, and was chosen after seeing the data; and the task-administration explanation for the false positives is a hypothesis, confounded with an 8.4-year age difference in a sample of 27.")
sub1("That one architectural decision was made with knowledge of a score from that corpus, so 0.8533 validates the frozen English screening model on data absent from its training but is not free of that one prior exposure (section 3.9).",
     "That one architectural decision was made with knowledge of a score from that corpus, so 0.8533 validates the frozen English screening model on data absent from its training but is not free of that prior exposure (section 3.9).")
sub1("Whether it costs real speakers anything is unknown, and this is the largest single untested assumption standing between the reported external figure and the deployed instrument — larger than the threshold-transfer problem beside it.",
     "Whether it costs real speakers anything is unknown, and this is the largest single untested assumption between the reported external figure and the deployed instrument — larger than the threshold-transfer problem beside it.")
sub1("Freezing the model bought a one-shot external evaluation and permanently excluded a known improvement: a pause-and-timing feature module is implemented, tested and deliberately unwired, kept outside the deployed package in `future_work/pause_features.py`, while pause and timing measures are among the strongest reported predictors in this literature and the first thing background noise destroys (section 5.9).",
     "Freezing the model bought a one-shot external evaluation and permanently excluded a known improvement: a pause-and-timing feature module is implemented, tested and deliberately unwired (`future_work/pause_features.py`), while pause and timing measures are among the strongest reported predictors in this literature and the first thing background noise destroys (section 5.9).")

# 6.3
sub1("The future work follows from the limitations, and its first sentence is a boundary rather than a plan: the same properties that make the instrument administrable in a Libyan home without a clinic — no network, no specialist, a paper fallback — make it administrable in a displacement or post-disaster setting, where cognitive screening is least available and cognitive harm most concentrated, and whether it is *useful* there is entirely untested.",
     "The future work follows from the limitations, and its first sentence is a boundary rather than a plan: the properties that make the instrument administrable in a Libyan home without a clinic — no network, no specialist, a paper fallback — make it administrable in a displacement or post-disaster setting, where screening is least available and cognitive harm most concentrated, and whether it is *useful* there is entirely untested.")
sub1("The principal future work is the Libyan study, and its pathway is reported at exactly the strength it has. Clinical validation has not been performed. A pathway toward it has been established through engagement with a national patient organisation, and that engagement is stakeholder engagement, not clinical validation: it is confined to recruitment feasibility and cultural acceptability, the organisation has not reviewed, assessed or endorsed the instrument, and no patient data has been involved. The reference standard requires clinician-confirmed diagnosis; contact has been initiated and no arrangement is in place, so the protocol's reference-standard section is written as what would be required — the Arabic Montreal Cognitive Assessment administered blind to the system's output — rather than as an arrangement. The feasibility pilot is submitted as a completed, ethics-ready protocol (Appendix B) with its endpoint structure fixed in advance: the eventual study's powered primary endpoint is dementia against healthy controls, with a pre-specified mild-impairment arm that is explicitly underpowered and descriptive only. What the pilot delivers is deliberately modest — battery feasibility, the first Libyan healthy normative distributions, validation of the Arabic word lists against dialect actually spoken, a provisional control-referenced threshold at its exact interval width, the elicitation measurements no existing corpus records, and the stimulus-equivalence check — and it cannot test discrimination: at 20 per group it detects only a true AUC of 0.748 or larger, above every effect this project has measured.",
     "The principal future work is the Libyan study, and its pathway is reported at exactly the strength it has. Clinical validation has not been performed. A pathway toward it exists through engagement with a national patient organisation, and that is stakeholder engagement, not clinical validation: it is confined to recruitment feasibility and cultural acceptability, the organisation has not reviewed, assessed or endorsed the instrument, and no patient data has been involved. The reference standard requires clinician-confirmed diagnosis; contact has been initiated and no arrangement is in place, so the protocol's reference-standard section is written as what would be required — the Arabic Montreal Cognitive Assessment administered blind to the system's output — rather than as an arrangement. The feasibility pilot is submitted as a completed, ethics-ready protocol (Appendix B) with its endpoint structure fixed in advance: the eventual study's powered primary endpoint is dementia against healthy controls, with a pre-specified mild-impairment arm that is explicitly underpowered and descriptive only. What the pilot delivers is deliberately modest — battery feasibility, the first Libyan healthy normative distributions, validation of the Arabic word lists against dialect actually spoken, a provisional control-referenced threshold at its exact interval width, the elicitation measurements no existing corpus records, and the stimulus-equivalence check — and it cannot test discrimination: at 20 per group it detects only a true AUC of 0.748 or larger, above every effect this project has measured.")
sub1("For the model itself, the staged validation design below is this project's own prescription for what it could not do, and it follows from the measured transport failures of section 5.13: one global threshold does not transport, and one global recalibration cannot repair it. The stages are strict and ordered:",
     "For the model itself, the staged validation design below is the project's prescription for what it could not do, and it follows from the measured transport failures of section 5.13: one global threshold does not transport, and one global recalibration cannot repair it. The stages are ordered:")
sub1("Candidate corpora for the last stage were checked for provenance. TAUKADIAL — 169 participants and 507 picture-description recordings in Mandarin and English, targeting mild impairment — is not clean until checked, because its English arm is a University of Delaware community cohort recruited under the same programme as this project's Delaware training corpus, so its participant identifiers would have to be checked against the 291 Delaware training participants, or the evaluation restricted to the Mandarin arm, a different claim [1].",
     "Candidate corpora for the last stage were checked for provenance. TAUKADIAL — 169 participants and 507 picture-description recordings in Mandarin and English, targeting mild impairment — is not clean until checked, because its English arm is a University of Delaware community cohort recruited under the same programme as this project's Delaware training corpus: its participant identifiers would have to be checked against the 291 Delaware training participants, or the evaluation restricted to the Mandarin arm, a different claim [1].")
sub1("Three further directions close the list: pretrained speech and text representations remain the principal untested modelling direction, unattemptable in the development environment and forfeiting the paper fallback if adopted wholesale (section 5.1.2); per-deployment threshold derivation on local healthy controls is the operational form of the first contribution (section 5.13.3); and the pause-and-timing module is wired in only after a fourth both-class corpus exists to validate the enlarged model.",
     "Three further directions close the list: pretrained speech and text representations remain the principal untested modelling direction, unattemptable in the development environment and forfeiting the paper fallback if adopted wholesale (section 5.1.2); per-deployment threshold derivation on local healthy controls is the operational form of the first contribution (section 5.13.3); and the pause-and-timing module is wired in only after a fourth both-class corpus exists to validate the enlarged model.")

# 6.3.1
sub1("Its provenance is stated precisely: the original training script is lost, the configuration was recovered by introspection of the deployed artifact, the protocol was confirmed by a pre-registered signature test, and the embedded figure reproduces from a fresh fit run by committed code to within 6.0 × 10⁻⁵ — a reconstruction that has been verified rather than merely trusted, though a verified reconstruction is a weaker guarantee than a committed training script would have given. The caveat belongs in the same paragraph as the recommendation: 0.708 was measured on a matched English subset of 373 recordings, its transfer to Arabic is exactly as unvalidated as everything else in section 6.4, and the one measured Arabic figure — 0.622 [0.378, 0.857] on the 24-speaker pilot, an interval spanning chance — comes from this same acoustic model. Two instruments were built, and the weaker one is the deployable one; what changes that is an Arabic corpus meeting the specification of section 6.5, at which point the linguistic instrument becomes available and the acoustic one becomes its fallback.",
     "Its provenance is stated precisely: the original training script is lost, the configuration was recovered by introspection of the deployed artifact, the protocol was confirmed by a pre-registered signature test, and the embedded figure reproduces from a fresh fit run by committed code to within 6.0 × 10⁻⁵ — a reconstruction verified rather than merely trusted, though a verified reconstruction is a weaker guarantee than a committed training script would have given. The caveat belongs beside the recommendation: 0.708 was measured on a matched English subset of 373 recordings, its transfer to Arabic is exactly as unvalidated as everything else in section 6.4, and the one measured Arabic figure — 0.622 [0.378, 0.857] on the 24-speaker pilot, an interval spanning chance — comes from this same acoustic model. Two instruments were built, and the weaker one is the deployable one; an Arabic corpus meeting the specification of section 6.5 changes that, at which point the linguistic instrument becomes available and the acoustic one its fallback.")

# 6.4
sub1("The Arabic contribution is stated as what it is — an instrument for the dementia target, a documented resource gap, and a corpus specification — because the English construct probe changed what may be claimed. The referential deficit index discriminates in a dementia cohort:",
     "The Arabic contribution is stated as what it is — an instrument for the dementia target, a documented resource gap, and a corpus specification — because the English construct probe changed what may be claimed. The referential deficit index discriminates in a dementia cohort:")
sub1("The failure is in the construct, not the implementation and not the language: on this English evidence, target and stage are the dominant explanation — the index separates at the dementia stage and not at the mild-impairment stage — and nothing measured here supports it as an early marker in any language. The pro-drop argument survives unchanged: Arabic normally omits the subject pronoun because the verb carries person, number and gender, so pronoun counts sit on a different baseline for grammatical rather than clinical reasons, and the English pronoun-overuse marker cannot be carried across (section 3.4). The referential deficit index remains the candidate replacement for it, measured so far in English only; what changed is not whether the candidate works but what it is for. The cost is this: mild impairment is where early detection changes management and is the future study's most valuable target, and the Arabic component as designed cannot address it. Making it a mild-impairment instrument requires an Arabic lemmatiser, because morphological richness confounds surface lexical-diversity measures, an Arabic dependency parser, and Arabic embeddings, all running offline on the target hardware — a substantially different engineering problem from the one this project solved, and naming its three components exactly is worth more than claiming coverage the measurement does not support.",
     "The failure is in the construct, not the implementation and not the language: on this English evidence the index separates at the dementia stage and not at the mild-impairment stage, and nothing measured here supports it as an early marker in any language. The pro-drop argument survives unchanged: Arabic normally omits the subject pronoun because the verb carries person, number and gender, so pronoun counts sit on a different baseline for grammatical rather than clinical reasons, and the English pronoun-overuse marker cannot be carried across (section 3.4). The referential deficit index remains the candidate replacement for it, measured so far in English only; what changed is not whether the candidate works but what it is for. The cost: mild impairment is where early detection changes management and is the future study's most valuable target, and the Arabic component as designed cannot address it. Making it a mild-impairment instrument requires an Arabic lemmatiser, because morphological richness confounds surface lexical-diversity measures, an Arabic dependency parser, and Arabic embeddings, all running offline on the target hardware — a substantially different engineering problem from the one this project solved, and naming its three components exactly is worth more than claiming coverage the measurement does not support.")
sub1("What the measurement saved exceeds what it cost: it arrived before 240 Libyan participants were recruited against a marker that cannot detect what the study most needs to screen for, and a single-task, single-language study would have returned a correctly powered null that was uninterpretable, unable to distinguish a wrong marker from a wrong task from a wrong implementation. The English probes separate all three (sections 5.10.1 and 5.15), and the finding changed what the corpus must contain — both genres from every speaker.",
     "What the measurement saved exceeds what it cost: it arrived before 240 Libyan participants were recruited against a marker that cannot detect what the study most needs to screen for, when a single-task, single-language study would have returned a correctly powered null that was uninterpretable — unable to distinguish a wrong marker from a wrong task from a wrong implementation. The English probes separate all three (sections 5.10.1 and 5.15), and the finding changed what the corpus must contain: both genres from every speaker.")
sub1("Each qualifier does work — clinical archives surely hold such recordings, the claim concerns what a researcher can obtain; word-list, naming and repetition batteries do not elicit the referential behaviour the index measures; and audio without transcripts supports no lexical or syntactic measurement, since Arabic speech recognition is not dependable on dialectal elderly speech. The evidence is a documented search, not a systematic review, and it brackets the gap from both sides:",
     "Each qualifier does work — clinical archives surely hold such recordings, and the claim concerns what a researcher can obtain; word-list, naming and repetition batteries do not elicit the referential behaviour the index measures; and audio without transcripts supports no lexical or syntactic measurement, since Arabic speech recognition is not dependable on dialectal elderly speech. The evidence is a documented search, not a systematic review, and it brackets the gap from both sides:")
sub1("Data with both classes and no connected speech; connected speech with no labels; never the join — and the claim is falsifiable, since one counterexample retires it. Against that gap, the contribution is the three parts named above: a working Arabic engine that computes the candidate marker, its evidential status stated exactly; the documented absence, stated at the strength the search supports and no more; and the specification of section 6.5, which is the part another group could act on tomorrow.",
     "Data with both classes and no connected speech; connected speech with no labels; never the join — and the claim is falsifiable, since one counterexample retires it. Against that gap the contribution is the three parts named above: a working Arabic engine that computes the candidate marker, its evidential status stated exactly; the documented absence, stated at the strength the search supports; and the specification of section 6.5, the part another group could act on tomorrow.")

# 6.5
sub1("What the successor corpus must contain is specified in full in Appendix I, derived entirely from this project's own measurements. It is led by genre rather than by named tasks — connected discourse for the mild-impairment target, picture description retained for the dementia target — and requires both genres from every participant, because a single-genre corpus cannot separate a marker failure from a task failure; it fixes elicitation, because word count is the strongest single mild-impairment measure on discourse and under variable administration it measures the examiner; it requires transcription that preserves the dialectal demonstratives and vague nouns the dementia measurement is made of; it splits the marker families by target; and it requires the healthy arm to recruit both sexes in numbers sufficient for sex-specific reference ranges, the design requirement carried from section 5.2.1.",
     "What the successor corpus must contain is specified in Appendix I, derived entirely from this project's own measurements. It is led by genre rather than by named tasks — connected discourse for the mild-impairment target, picture description retained for the dementia target — and requires both genres from every participant, because a single-genre corpus cannot separate a marker failure from a task failure; it fixes elicitation, because word count is the strongest single mild-impairment measure on discourse and under variable administration it measures the examiner; it requires transcription that preserves the dialectal demonstratives and vague nouns the dementia measurement is made of; it splits the marker families by target; and it requires the healthy arm to recruit both sexes in numbers sufficient for sex-specific reference ranges (section 5.2.1).")

# 6.6
sub1("The frozen English screening model reached external AUC 0.8533 [0.7371, 0.9458] on data absent from its training, at a threshold fixed in advance, scored once, under the exposure history of section 3.9; at that threshold it was sensitive and unspecific, and the specificity is diagnosed and its recovery specified in section 5.13 — a post-hoc methodological contribution, not pre-registered, not deployed, and requiring prospective validation. The apparatus that produces the score — sixty-four engineered features, a calibrated ensemble, the whole modelled part of the system — is worth about four points of AUC over counting one quantity by hand, measured the same way on both targets (section 6.1). That is a real gain, and a small one.",
     "The frozen English screening model reached external AUC 0.8533 [0.7371, 0.9458] on data absent from its training, at a threshold fixed in advance, scored once, under the exposure history of section 3.9; at that threshold it was sensitive and unspecific, and section 5.13 diagnoses the specificity and specifies its recovery — a post-hoc methodological contribution, not pre-registered, not deployed, requiring prospective validation. The apparatus that produces the score — sixty-four engineered features, a calibrated ensemble, the whole modelled part of the system — is worth about four points of AUC over counting one quantity by hand, measured the same way on both targets (section 6.1): a real gain, and a small one.")
sub1("The lock that made one external number mean something. The fifteen negative results, three of which changed a design decision. The pre-registration discipline, with its four disclosed failures and the rules derived from them. The measurement that the Arabic instrument addresses dementia rather than the target the future study most needs — made before two hundred and forty people were recruited against it. None of that is accuracy, and all of it is what makes the accuracy readable; a number without those things is the field's present situation — more than a decade of reported performance above ninety per cent and no tool in routine clinical use (section 2.3).",
     "The lock that made one external number mean something; the fifteen negative results, three of which changed a design decision; the pre-registration discipline, with its four disclosed failures and the rules derived from them; the measurement that the Arabic instrument addresses dementia rather than the target the future study most needs, made before two hundred and forty people were recruited against it. None of that is accuracy, and all of it is what makes the accuracy readable; a number without those things is the field's present situation — more than a decade of reported performance above ninety per cent and no tool in routine clinical use (section 2.3).")

open(P, "w", encoding="utf-8").write(t)
print("chapter6 words", before, "->", len(t.split()))
