#!/usr/bin/env python3
"""cut2_appEG.py -- Appendix E and G compression toward the register form. Quoted report text is untouched."""
import re
ROOT = "/home/claude/work/src/docs/chapters/"
FILES = {"E": ROOT + "appendix_e.md", "G": ROOT + "appendix_g.md"}
T = {k: open(v, encoding="utf-8").read() for k, v in FILES.items()}
Bw = {k: len(v.split()) for k, v in T.items()}
def ws(s): return r"\s+".join(re.escape(w) for w in s.split())
def rep(f, old, new):
    pat = ws(old); n = len(re.findall(pat, T[f]))
    assert n == 1, (f, old[:70], n)
    T[f] = re.sub(pat, lambda m: new, T[f])

# ---- Appendix E ----
rep("E", "This appendix reproduces one complete session administered through the assessment platform of Chapter 4, exactly as the platform saves it: run after the lock through the platform's own interface endpoints, in the order the browser performs them — session start, one recording upload per task, one operator-confirmed transcript per task, then analysis — with the saved session file DEMO-E1 under `data/sessions/` as the source of every figure below. **No participant exists.** The recording uploaded for every task is the project's synthetic sample (`data/samples/sample_control.wav`, produced by `scripts/make_sample.py`, 8.3 seconds of synthesised voiced speech), and the transcripts were typed by the operator for the demonstration — the platform's standard fallback when automatic transcription is not installed, and the way the reference corpus itself was transcribed. The demographic entries (age 68, female, twelve years of education, routine population screening, family history unknown) are demonstration values; the appendix shows what the platform produces and how it words it, and nothing about any person.",
    "This appendix reproduces one complete session administered through the assessment platform of Chapter 4, exactly as the platform saves it: run after the lock through the platform's own interface endpoints in the order the browser performs them — session start, one recording upload per task, one operator-confirmed transcript per task, then analysis — with the saved session file DEMO-E1 under `data/sessions/` as the source of every figure below. **No participant exists.** The recording uploaded for every task is the project's synthetic sample (`data/samples/sample_control.wav`, produced by `scripts/make_sample.py`, 8.3 seconds of synthesised voiced speech), the transcripts were typed by the operator — the platform's standard fallback without automatic transcription, and the way the reference corpus itself was transcribed — and the demographic entries (age 68, female, twelve years of education, routine population screening, family history unknown) are demonstration values. The appendix shows what the platform produces and how it words it, and nothing about any person.")
rep("E", "The session was started in English, so the platform assembled the four-task English battery without the Arabic-only recitation task (section 4.2), and rotated the stimuli deterministically from the participant code and session number, selecting the kitchen scene — the validated picture — and the story identified as `teacher`. Table (E.1) lists the battery in administration order with the quality-gate result for each recording; every recording passed — the synthetic sample runs 8.3 seconds with 6.2 seconds of speech, a signal-to-noise ratio of 37.6 dB and a clipped fraction of 0.0002 — against the minima of Table (4.3). The screening result is computed from the picture description alone; the story-recall and procedural-discourse transcripts are collected as context and do not enter it (section 4.1).",
    "The session was started in English, so the platform assembled the four-task English battery without the Arabic-only recitation task (section 4.2) and rotated the stimuli deterministically from the participant code and session number, selecting the kitchen scene — the validated picture — and the story identified as `teacher`. Table (E.1) lists the battery with the quality-gate result for each recording; every recording passed — 8.3 seconds with 6.2 seconds of speech, a signal-to-noise ratio of 37.6 dB and a clipped fraction of 0.0002 — against the minima of Table (4.3). The screening result is computed from the picture description alone (section 4.1).")
rep("E", "The picture-description transcript, the one the screening score is computed from, was entered as follows.",
    "The picture-description transcript, from which the screening score is computed, was entered as follows.")
rep("E", "The platform ran in screening-score mode, because the trained model was attached, the session was in English and the picture was the calibrated kitchen scene (section 4.5). The model returned a screening score of **0.218** against the fixed threshold of **0.367**, and the report placed the session in the band it labels *typical*, with the wording:",
    "The platform ran in screening-score mode — trained model attached, English session, calibrated kitchen scene (section 4.5) — and returned a screening score of **0.218** against the fixed threshold of **0.367**; the report placed the session in the band it labels *typical*, with the wording:")
rep("E", "and states that the result is computed from the picture-description task only, the sole task with healthy controls in the training corpus and the one on which the model was externally evaluated.",
    "and states that the result is computed from the picture-description task only, the sole task with healthy controls in the training corpus and the one on which the model was externally evaluated.")
rep("E", "The age-adjustment chain of section 3.7 then converted the screening score into a posterior. Table (E.2) lists every quantity the report prints for it. The explanation printed beside the number reads:",
    "The age-adjustment chain of section 3.7 then converted the screening score into a posterior; Table (E.2) lists every quantity the report prints for it, and the explanation beside the number reads:")
rep("E", "Independently of the score, the report lists every measured indicator against its reference range — the profile that is the platform's only output when no score can be justified (section 4.4). Table (E.3) reproduces the 19 indicators as printed, with the plain-language meaning the report attaches to each. One fell outside its reference range, pitch variation at 0.028 against a floor of 0.1 — an artefact of the synthesised input, whose fundamental frequency is almost constant by construction, and an illustration of the profile reporting a measurement the score does not use.",
    "Independently of the score, the report lists every measured indicator against its reference range — the profile that is the platform's only output when no score can be justified (section 4.4); Table (E.3) reproduces the 19 indicators as printed, with the plain-language meaning the report attaches to each. One fell outside its reference range, pitch variation at 0.028 against a floor of 0.1 — an artefact of the synthesised input, whose fundamental frequency is almost constant by construction, and an illustration of the profile reporting a measurement the score does not use.")
rep("E", "The two context tasks are reported beside the profile and do not affect the result. Verbal fluency counted 32 animal names with 0 repetitions and 0 unrecognised words; the report's corpus note gives the training cohort's counts by severity band and a published normative mean for orientation, and ends:",
    "The two context tasks are reported beside the profile and do not affect the result. Verbal fluency counted 32 animal names with 0 repetitions and 0 unrecognised words; the report's corpus note gives the training cohort's counts by severity band and a published normative mean, and ends:")
rep("E", "The severity index, estimated from the picture, fluency and recall tasks combined, placed the session in the *mild range* band and printed its own status in full:",
    "The severity index, from the picture, fluency and recall tasks combined, placed the session in the *mild range* band and printed its own status in full:")
rep("E", "Two texts appear on every screening-score report, and both were present here: the stimulus-substitution caveat quoted in full in section 4.5, and the disclaimer that heads the report reads:",
    "Two texts appear on every screening-score report, and both were present here: the stimulus-substitution caveat quoted in section 4.5, and the disclaimer heading the report:")
rep("E", "The session exercised every stage the platform performs on a real session — battery assembly, audio conversion, the acoustic engine, the quality gate, the typed-transcript fallback, the linguistic and information-unit engines, the screening model, the age-adjustment chain, the indicator profile, the context tasks and the caveat texts — and produced the report a clinician would receive. Two limitations keep the appendix from being mistaken for more than it is. First, the acoustic indicators (the *Fluency & timing* and *Voice* rows of Table (E.3)) describe an 8.3-second synthesised recording, so their values are meaningful only as evidence that the engine ran; the one atypical flag is the synthesis, not speech. Second, the fluency context text compares a count of 32 animals to the dementia cohort's mildest band, because the report's severity comparison has no band above that cohort's healthiest mean — a wording limitation of the current build that a healthy adult's count exposes, recorded rather than hidden. The report file, the driver that produced it and the transcripts entered are committed with the project.",
    "The session exercised every stage the platform performs on a real session — battery assembly, audio conversion, the acoustic engine, the quality gate, the typed-transcript fallback, the linguistic and information-unit engines, the screening model, the age-adjustment chain, the indicator profile, the context tasks and the caveat texts — and produced the report a clinician would receive. Two limitations keep the appendix from being mistaken for more than it is: the acoustic indicators (the *Fluency & timing* and *Voice* rows of Table (E.3)) describe an 8.3-second synthesised recording, so their values show only that the engine ran, the one atypical flag being the synthesis, not speech; and the fluency context text compares a count of 32 animals to the dementia cohort's mildest band, because the report's severity comparison has no band above that cohort's healthiest mean — a wording limitation of the current build that a healthy adult's count exposes, recorded rather than hidden. The report file, the driver that produced it and the transcripts entered are committed with the project.")

# ---- Appendix G ----
rep("G", "This appendix is the full record of the transcription artefact summarised in section 3.2.1: the defect, its size, why it correlates with diagnosis, why it survived a guard designed to exclude exactly this class of contamination, what it costs, and why it was left in place. Sources: `scripts/transcription_artefact_probe.py`, whose docstring carries the audit record and whose criteria were committed before the measurement ran, and `results/reconstruction/transcription_artefact_probe.json`.",
    "This appendix is the full record of the transcription artefact summarised in section 3.2.1: the defect, its size, why it correlates with diagnosis, why it survived a guard designed to exclude exactly this class of contamination, what it costs, and why it was left in place. Sources: `scripts/transcription_artefact_probe.py`, whose docstring carries the audit record and whose criteria were committed before the measurement ran, and `results/reconstruction/transcription_artefact_probe.json`.")
rep("G", "CHAT transcription marks an omitted sound with parentheses: a speaker who said *dryin'* is transcribed `dryin(g)`. The transcript cleaner (`chat_parser.clean_utterance`) strips most CHAT markup and not this form, so the token reaching the feature extractors is `dryin(g)`, with three silent consequences. The tokeniser splits it into four tokens, so the verb is never recognised, and the affected words are exactly the action verbs the information-unit scorer looks for — `dryin(g)` occurs 96 times, `runnin(g)` 84, `washin(g)` 69, `fallin(g)` 67, `gettin(g)` 67, `reachin(g)` 43 and `standin(g)` 37; `dryin` and `drying` count as different types, corrupting the type-token ratio, MATTR-50, Brunet's W and Honoré's R; and the scale is material, 58.9% of Pittsburgh transcripts affected, 1,193 tokens in all, 1.88% of every token in the corpus.",
    "CHAT transcription marks an omitted sound with parentheses: a speaker who said *dryin'* is transcribed `dryin(g)`. The transcript cleaner (`chat_parser.clean_utterance`) strips most CHAT markup and not this form, so the token reaching the feature extractors is `dryin(g)`, with three silent consequences: the tokeniser splits it into four tokens, so the verb is never recognised, and the affected words are exactly the action verbs the information-unit scorer looks for — `dryin(g)` occurs 96 times, `runnin(g)` 84, `washin(g)` 69, `fallin(g)` 67, `gettin(g)` 67, `reachin(g)` 43 and `standin(g)` 37; `dryin` and `drying` count as different types, corrupting the type-token ratio, MATTR-50, Brunet's W and Honoré's R; and the scale is material, 58.9% of Pittsburgh transcripts affected, 1,193 tokens in all, 1.88% of every token in the corpus.")
rep("G", "The deployed feature set deliberately contains no `chat.*` markup features, because the corpus-compatibility finding showed transcription convention alone separates two *healthy* groups from different corpora at an AUC of 0.930. That exclusion removed markup *features*; it did not remove markup from the *transcript text* that the linguistic features are computed on. The guard was correct in principle and incomplete in execution, and a hand audit of the raw text found the residue: excluding a contaminated feature family does not exclude the contamination if it is also inside the input.",
    "The deployed feature set deliberately contains no `chat.*` markup features, because the corpus-compatibility finding showed transcription convention alone separates two *healthy* groups from different corpora at an AUC of 0.930; that exclusion removed markup *features*, not markup from the *transcript text* the linguistic features are computed on. The guard was correct in principle and incomplete in execution, and a hand audit of the raw text found the residue: excluding a contaminated feature family does not exclude the contamination if it is also inside the input.")
rep("G", "All 64 deployed features were re-extracted from corrected text — parenthesised sounds restored, residual non-word characters stripped — with the deployed architecture, folds and seed unchanged.",
    "All 64 deployed features were re-extracted from corrected text — parenthesised sounds restored, residual non-word characters stripped — with architecture, folds and seed unchanged.")
rep("G", "At single-feature level the largest movements are the information-unit totals (`iu.total` 0.7538 to 0.7465, `iu.actions` 0.7332 to 0.7155), consistent with the mechanism above. Two further readings follow.",
    "At single-feature level the largest movements are the information-unit totals (`iu.total` 0.7538 to 0.7465, `iu.actions` 0.7332 to 0.7155), consistent with the mechanism. Two further readings follow.")
rep("G", "the check of the Lu corpus, declared descriptive before it ran, found eight parenthesised-omission forms in the entire corpus, seventeen times rarer than Pittsburgh's control rate; a model that depended on that channel would have lost performance where the channel is absent, and it produced its highest figure there instead.",
    "the check of the Lu corpus, declared descriptive before it ran, found eight parenthesised-omission forms in the entire corpus, seventeen times rarer than Pittsburgh's control rate; a model dependent on that channel would have lost performance where it is absent, and it produced its highest figure there instead.")
rep("G", "Correcting the extractor changes the features the frozen model receives and would forfeit the locked external validation, which cannot be repeated. The correction is instead specified for the next iteration: `clean_utterance` should restore parenthesised sounds and strip residual non-word characters, and the next external corpus should be spent on the corrected pipeline. The same audit found a smaller defect:",
    "Correcting the extractor changes the features the frozen model receives and would forfeit the locked external validation, which cannot be repeated; the correction is specified for the next iteration instead — `clean_utterance` should restore parenthesised sounds and strip residual non-word characters, and the next external corpus should be spent on the corrected pipeline. The same audit found a smaller defect:")
rep("G", "It is left in place for the same reason as the artefact and carried on the same fix list.",
    "It is left in place for the same reason and carried on the same fix list.")
rep("G", "Two details complete the record. First, one Lu file's group header reads `Conrol`, and the locked 27 control / 26 impaired split adds up exactly only if that file was handled as a control, which the corpus build did. Second, the sourcing of the counts: the Pittsburgh artefact figures are recorded in the committed probe script and its result file, and the raw filled-pause count reproduces exactly, 1,881 of 1,881, from the committed parser (`results/reconstruction/pitt_filled_pause_count.json`); the Lu counts were recommitted after the lock (`scripts/lu_artefact_check.py` → `results/reconstruction/lu_artefact_check.json`), where the count of eight reproduces exactly once the pattern is read as the original evidently read it — all parenthesised omissions, whole-word forms such as *(be)cause* and *(there)* included — and the class rates in Table (G.1) are the recommitted values (0.084 control, 0.210 impaired per 100 words; the working record's 0.065/0.220 came from the uncommitted run and is superseded). The registered word-attached criterion is recorded as failed as written, with the decoding in the result file's post-execution notes; the substance, that the channel is effectively absent externally, is unchanged under either reading.",
    "Two details complete the record. First, one Lu file's group header reads `Conrol`, and the locked 27 control / 26 impaired split adds up exactly only if that file was handled as a control, which the corpus build did. Second, the sourcing of the counts: the Pittsburgh figures are recorded in the committed probe script and its result file, and the raw filled-pause count reproduces exactly, 1,881 of 1,881, from the committed parser (`results/reconstruction/pitt_filled_pause_count.json`); the Lu counts were recommitted after the lock (`scripts/lu_artefact_check.py` → `results/reconstruction/lu_artefact_check.json`), where the count of eight reproduces exactly once the pattern is read as the original evidently read it — all parenthesised omissions, whole-word forms such as *(be)cause* and *(there)* included — and the class rates in Table (G.1) are the recommitted values (0.084 control, 0.210 impaired per 100 words; the working record's 0.065/0.220 came from the uncommitted run and is superseded). The registered word-attached criterion is recorded as failed as written, with the decoding in the result file's post-execution notes; the substance, that the channel is effectively absent externally, holds under either reading.")

for k, v in FILES.items():
    open(v, "w", encoding="utf-8").write(T[k]); print(k, "words", Bw[k], "->", len(T[k].split()))
