#!/usr/bin/env python3
"""cut2_flips.py -- small phrasing cuts placed where a unit's last page is mostly blank, so the unit loses a page
(Chapter 6, Appendices F, I, E, J, C, G) plus a Chapter 2 pass. Whitespace-normalised matching; numbers kept."""
import re
ROOT = "/home/claude/work/src/docs/chapters/"
FILES = {"c2": ROOT + "chapter2.md", "c6": ROOT + "chapter6.md", "F": ROOT + "appendix_f.md", "I": ROOT + "appendix_i.md",
         "E": ROOT + "appendix_e.md", "J": ROOT + "appendix_j.md", "G": ROOT + "appendix_g.md"}
T = {k: open(v, encoding="utf-8").read() for k, v in FILES.items()}
B = {k: len(v.split()) for k, v in T.items()}
def ws(s): return r"\s+".join(re.escape(w) for w in s.split())
def rep(f, old, new):
    pat = ws(old); n = len(re.findall(pat, T[f]))
    assert n == 1, (f, old[:70], n)
    T[f] = re.sub(pat, lambda m: new, T[f])

# ---- Chapter 6 (last page 92% blank) ----
rep("c6", "Encoding a competence boundary and enforcing it at runtime is rare in this literature, and it is a biomedical-engineering contribution rather than a machine-learning one.",
    "Encoding a competence boundary and enforcing it at runtime is rare in this literature, and is a biomedical-engineering contribution rather than a machine-learning one.")
rep("c6", "What the measurement saved exceeds what it cost: it arrived before 240 Libyan participants were recruited against a marker that cannot detect what the study most needs to screen for, when a single-task, single-language study would have returned a correctly powered null that was uninterpretable — unable to distinguish a wrong marker from a wrong task from a wrong implementation. The English probes separate all three (sections 5.10.1 and 5.15), and the finding changed what the corpus must contain: both genres from every speaker.",
    "What the measurement saved exceeds what it cost: it arrived before 240 Libyan participants were recruited against a marker that cannot detect what the study most needs to screen for, when a single-task, single-language study would have returned a correctly powered null unable to distinguish a wrong marker from a wrong task from a wrong implementation. The English probes separate all three (sections 5.10.1 and 5.15), and the finding changed what the corpus must contain: both genres from every speaker.")
rep("c6", "The probe remains exploratory, and nothing in this thesis treats it otherwise.",
    "The probe remains exploratory throughout.")
rep("c6", "The stages are ordered: a development pool for fitting and feature decisions, as now; a dedicated calibration cohort, used openly and repeatedly to set the operating threshold and the recalibration map and declared as spent — the locked corpus is the natural candidate, since its scores are already on the record, and what it may never again be called is an external test set; a freeze of everything, model, threshold, calibration map and feature set, recorded as at the lock; and one evaluation on a corpus never touched, pre-registered, single execution, reported whatever it says.",
    "The stages are ordered: a development pool for fitting and feature decisions, as now; a dedicated calibration cohort, used openly and repeatedly to set the operating threshold and the recalibration map and declared as spent — the locked corpus is the natural candidate, since its scores are already on the record, and it may never again be called an external test set; a freeze of everything, model, threshold, calibration map and feature set, recorded as at the lock; and one evaluation on a corpus never touched, pre-registered, single execution, reported whatever it says.")

# ---- Appendix F (last page 92% blank) ----
rep("F", "This appendix grades every component of the project by the evidence behind it, so that an examiner can see what is externally validated, what is measured, what is reconstructed, what is only implemented and what is only specified. Every figure is the canonical value of `docs/NUMBERS.md` or of the result file named in the chapter that owns it, the registered grade words are reproduced as the result files record them, and where a figure appears in a chapter but in no result file the register says so.",
    "This appendix grades every component of the project by the evidence behind it — externally validated, measured, reconstructed, implemented only, or specified only. Every figure is the canonical value of `docs/NUMBERS.md` or of the result file named in the chapter that owns it, the registered grade words are reproduced as the result files record them, and where a figure appears in a chapter but in no result file the register says so.")
rep("F", "Seven levels are used, defined by the procedure that produced the evidence rather than by its size. Level A is external validation:",
    "Seven levels are used, defined by the procedure that produced the evidence. Level A is external validation:")
rep("F", "Table (F.1) assigns every component a level, states the evidence in one line, and carries the figure with its section.",
    "Table (F.1) assigns every component a level, states the evidence in one line and carries the figure with its section.")
rep("F", "Three things follow from the table. First, one figure in the project holds level A, with an exposure history attached:",
    "Three things follow. First, one figure in the project holds level A, with an exposure history attached:")

# ---- Appendix I (last page 71% blank) ----
rep("I", "This appendix is the full specification of the Arabic corpus whose absence section 6.4 documents: what such a corpus must contain for its results to be interpretable, with every figure derived from this project's own measurements rather than asserted. Its evidential sources are",
    "This appendix specifies the Arabic corpus whose absence section 6.4 documents: what it must contain for its results to be interpretable, every figure derived from this project's own measurements. Its evidential sources are")
rep("I", "Chapter 6 section 6.5 carries the summary; the pilot protocol of Appendix B is this specification's first increment.",
    "Section 6.5 carries the summary; the pilot protocol of Appendix B is the specification's first increment.")
rep("I", "The specification is led by the claim that transfers. A corpus built from scratch cannot inherit an instruction to use a particular named task; it can inherit a claim about what kind of task carries the signal.",
    "A corpus built from scratch cannot inherit an instruction to use a particular named task; it can inherit a claim about what kind of task carries the signal.")
rep("I", "The genre level survives translation, cultural substitution and the replacement of every individual stimulus, which is what building a corpus in another language requires, and the mechanism makes it plausible rather than merely observed:",
    "The genre level survives translation, cultural substitution and the replacement of every stimulus, which is what building a corpus in another language requires, and the mechanism makes it plausible rather than merely observed:")
rep("I", "The corpus therefore collects both genres from every participant: the picture task serves the dementia target and the referential index, the discourse tasks serve mild impairment, and a single-genre corpus could not separate a marker failure from a task failure — the confusion section 6.4 records this project as having narrowly avoided.",
    "The corpus therefore collects both genres from every participant: the picture task serves the dementia target and the referential index, the discourse tasks serve mild impairment, and a single-genre corpus could not separate a marker failure from a task failure — the confusion section 6.4 records this project narrowly avoiding.")
rep("I", "The battery instantiates the genres for Libya. Story recall uses an examiner-read story retold immediately: supplying the narrative in the session equalises prior familiarity by construction, which makes it the cleaner instrument psychometrically as well as the culturally safe one, and an established scoring tradition exists to translate against (section 4.2).",
    "Story recall uses an examiner-read story retold immediately: supplying the narrative in the session equalises prior familiarity by construction, the cleaner instrument psychometrically as well as the culturally safe one, with an established scoring tradition to translate against (section 4.2).")
rep("I", "Procedural discourse asks for tea-making, chosen because essentially every participant has performed it hundreds of times, so failure reflects discourse organisation rather than unfamiliarity — and it is the one task a paper administration preserves intact.",
    "Procedural discourse asks for tea-making, which essentially every participant has performed hundreds of times, so failure reflects discourse organisation rather than unfamiliarity — and it is the one task a paper administration preserves intact.")
rep("I", "Three protocol requirements are not optional. Elicitation is fixed",
    "Three protocol requirements are not optional. Elicitation is fixed")
rep("I", "The marker families divide by target, and the division is the measurement's consequence. For mild impairment on discourse",
    "The marker families divide by target, as the measurement requires. For mild impairment on discourse")
rep("I", "Three rulings on the table are recorded so they are not rediscovered. An earlier recommendation that the mild-impairment arm was the cheaper one is withdrawn: it rested on the selection-inflated end of the range, and powered on the conservative end the two arms cost essentially the same — about 130 against 141 per group — so the choice between targets is scientific rather than budgetary.",
    "Three rulings on the table are recorded so they are not rediscovered. An earlier recommendation that the mild-impairment arm was the cheaper one is withdrawn: it rested on the selection-inflated end of the range, and powered on the conservative end the two arms cost essentially the same, about 130 against 141 per group, so the choice between targets is scientific rather than budgetary.")
rep("I", "And the 20-per-group pilot detects only a true AUC of 0.748 or larger, above every effect this project has measured, so it tests neither arm and says so by design; the descriptive endpoint structure of section 6.3 is the consequence. One further requirement is carried from section 5.2.1: the healthy arm recruits both sexes in numbers sufficient for sex-specific reference ranges, because the measured sex disparity is a discrimination gap that no threshold or rescaling can close, and local norms are the one repair the successor design has available.",
    "And the 20-per-group pilot detects only a true AUC of 0.748 or larger, above every effect this project has measured, so it tests neither arm and says so by design, which is why section 6.3's endpoint structure is descriptive. One further requirement is carried from section 5.2.1: the healthy arm recruits both sexes in numbers sufficient for sex-specific reference ranges, because the measured sex disparity is a discrimination gap no threshold or rescaling can close, and local norms are the one repair the successor design has available.")

# ---- Appendix E (last page 35% blank) ----
rep("E", "This appendix reproduces one complete session administered through the assessment platform of Chapter 4, exactly as the platform saves it. The session was run after the lock through the platform's own interface endpoints, in the order the browser performs them — session start, one recording upload per task, one operator-confirmed transcript per task, then analysis — and the saved session file for session DEMO-E1 under `data/sessions/` is the source of every figure below. **No participant exists.**",
    "This appendix reproduces one complete session administered through the assessment platform of Chapter 4, exactly as the platform saves it: run after the lock through the platform's own interface endpoints, in the order the browser performs them — session start, one recording upload per task, one operator-confirmed transcript per task, then analysis — with the saved session file DEMO-E1 under `data/sessions/` as the source of every figure below. **No participant exists.**")
rep("E", "The demographic entries (age 68, female, twelve years of education, routine population screening, family history unknown) are demonstration values. The appendix therefore shows what the platform produces and how it words it; it shows nothing about any person.",
    "The demographic entries (age 68, female, twelve years of education, routine population screening, family history unknown) are demonstration values; the appendix shows what the platform produces and how it words it, and nothing about any person.")
rep("E", "The session was started in English, so the platform assembled the four-task English battery and did not offer the recitation task, which is Arabic-only (section 4.2). It rotated the stimuli deterministically from the participant code and session number, selecting the kitchen scene — the validated picture — and the story identified as `teacher`. Table (E.1) lists the battery in administration order with the quality-gate result for each recording. Every recording passed the gate — the synthetic sample runs 8.3 seconds with 6.2 seconds of speech, a signal-to-noise ratio of 37.6 dB and a clipped fraction of 0.0002 — against the minima of Table (4.3). The screening result is computed from the picture description alone; the story-recall and procedural-discourse transcripts are collected and reported as context and do not enter it (section 4.1).",
    "The session was started in English, so the platform assembled the four-task English battery without the Arabic-only recitation task (section 4.2), and rotated the stimuli deterministically from the participant code and session number, selecting the kitchen scene — the validated picture — and the story identified as `teacher`. Table (E.1) lists the battery in administration order with the quality-gate result for each recording; every recording passed — the synthetic sample runs 8.3 seconds with 6.2 seconds of speech, a signal-to-noise ratio of 37.6 dB and a clipped fraction of 0.0002 — against the minima of Table (4.3). The screening result is computed from the picture description alone; the story-recall and procedural-discourse transcripts are collected as context and do not enter it (section 4.1).")
rep("E", "The platform ran in its screening-score mode, because the trained model was attached, the session was in English and the picture was the calibrated kitchen scene (section 4.5).",
    "The platform ran in screening-score mode, because the trained model was attached, the session was in English and the picture was the calibrated kitchen scene (section 4.5).")
rep("E", "and states that the result is computed from the picture-description task only, the sole task with healthy controls in the training corpus and the one on which the model was externally evaluated, the discourse tasks being recorded but contributing nothing to it.",
    "and states that the result is computed from the picture-description task only, the sole task with healthy controls in the training corpus and the one on which the model was externally evaluated.")
rep("E", "Independently of the score, the report lists every measured indicator against its reference range — the indicator profile that is the platform's only output when no score can be justified (section 4.4). Table (E.3) reproduces the 19 indicators as printed, with the plain-language meaning the report attaches to each.",
    "Independently of the score, the report lists every measured indicator against its reference range — the profile that is the platform's only output when no score can be justified (section 4.4). Table (E.3) reproduces the 19 indicators as printed, with the plain-language meaning the report attaches to each.")
rep("E", "The two context tasks are reported beside the profile and do not affect the result. Verbal fluency counted 32 animal names with 0 repetitions and 0 unrecognised words; the report attaches a corpus note giving the training cohort's counts by severity band and a published normative mean for orientation, and ends:",
    "The two context tasks are reported beside the profile and do not affect the result. Verbal fluency counted 32 animal names with 0 repetitions and 0 unrecognised words; the report's corpus note gives the training cohort's counts by severity band and a published normative mean for orientation, and ends:")
rep("E", "— the CANNOT-CONFIRM grade of section 5.7 travelling with the output, as the design requires.",
    "— the CANNOT-CONFIRM grade of section 5.7 travelling with the output.")
rep("E", "The session exercised every stage the platform performs on a real session — battery assembly, audio conversion, the acoustic engine, the quality gate, the typed-transcript fallback, the linguistic and information-unit engines, the screening model, the age-adjustment chain, the indicator profile, the context tasks and the caveat texts — and produced the report a clinician would receive. Two limitations are stated so that the appendix is not mistaken for more than it is.",
    "The session exercised every stage the platform performs on a real session — battery assembly, audio conversion, the acoustic engine, the quality gate, the typed-transcript fallback, the linguistic and information-unit engines, the screening model, the age-adjustment chain, the indicator profile, the context tasks and the caveat texts — and produced the report a clinician would receive. Two limitations keep the appendix from being mistaken for more than it is.")
rep("E", "Second, the fluency context text compares a count of 32 animals to the dementia cohort's mildest band, because the report's severity comparison has no band above that cohort's healthiest mean — a wording limitation of the current build that a healthy adult's count exposes, recorded here rather than hidden. The report file, the driver that produced it and the transcripts entered are committed with the project.",
    "Second, the fluency context text compares a count of 32 animals to the dementia cohort's mildest band, because the report's severity comparison has no band above that cohort's healthiest mean — a wording limitation of the current build that a healthy adult's count exposes, recorded rather than hidden. The report file, the driver that produced it and the transcripts entered are committed with the project.")

# ---- Appendix J (last page 37% blank) ----
rep("J", "This appendix records where the software lives, what it needs to run, how the figures in this thesis are regenerated from the committed record, and which parts of that record cannot be redistributed. No source code is reproduced here; the repository is the record, and this appendix is its map.",
    "This appendix records where the software lives, what it needs to run, how the figures in this thesis are regenerated from the committed record, and which parts of that record cannot be redistributed; the repository is the record, and this appendix is its map.")
rep("J", "The project is a single directory tree, `dhikra/`, under the address in Table (J.1). The submitted version is identified by the frozen model's checksum rather than by a commit identifier, because the model is the one artefact that must not change: every performance figure in Chapters 3 and 5 was produced by the file whose checksum is given, and a reader who obtains a copy with a different checksum has a different instrument.",
    "The project is a single directory tree, `dhikra/`, under the address in Table (J.1). The submitted version is identified by the frozen model's checksum rather than a commit identifier, because the model is the one artefact that must not change: every performance figure in Chapters 3 and 5 was produced by the file whose checksum is given, and a copy with a different checksum is a different instrument.")
rep("J", "Table (J.2) lists the top-level directories and what each holds. The separation matters for reproducibility: `models/` holds the frozen artefacts, `results/` holds every number the thesis cites, `src/` holds the library the platform and the analysis scripts share, and `scripts/` holds the drivers that produced `results/` from the corpora.",
    "Table (J.2) lists the top-level directories: `models/` holds the frozen artefacts, `results/` every number the thesis cites, `src/` the library the platform and the analysis scripts share, and `scripts/` the drivers that produced `results/` from the corpora.")
rep("J", "The dependencies are listed in `requirements.txt`; one pin is load-bearing and is commented as such in the file. The frozen model is a pickled scikit-learn object built under version 1.8.0, and scikit-learn does not guarantee that a model pickled under one version loads under another, so the library is pinned to the model rather than the model rebuilt for the library — rebuilding it would require a new external evaluation, which the spent corpus cannot provide. Two spaCy language models are installed separately, `en_core_web_sm` and `en_core_web_md`; the second supplies the word vectors behind nine of the sixty-four features, and section 4.5.1 records what happens when it is absent. Automatic transcription is optional: when no recogniser is installed the platform asks for a typed transcript, which is how the reference corpora were produced.",
    "The dependencies are listed in `requirements.txt`; one pin is load-bearing and commented as such. The frozen model is a pickled scikit-learn object built under version 1.8.0, and scikit-learn does not guarantee that a model pickled under one version loads under another, so the library is pinned to the model rather than the model rebuilt for the library — rebuilding it would require a new external evaluation, which the spent corpus cannot provide. Two spaCy language models are installed separately, `en_core_web_sm` and `en_core_web_md`; the second supplies the word vectors behind nine of the sixty-four features, and section 4.5.1 records what happens when it is absent. Automatic transcription is optional: without a recogniser the platform asks for a typed transcript, which is how the reference corpora were produced.")
rep("J", "Table (J.3) gives the reproduction path in the order it runs. The corpora are obtained from DementiaBank under its membership agreement and are never part of the repository; the paths to the local copies are declared in `corpus_paths.json`. The one step that cannot be repeated is the external evaluation:",
    "Table (J.3) gives the reproduction path in the order it runs. The corpora are obtained from DementiaBank under its membership agreement and are never part of the repository; local paths are declared in `corpus_paths.json`. The one step that cannot be repeated is the external evaluation:")
rep("J", "Access to each is by application to the holding organisation under its own agreement, and the corpus builders read the transcripts from the paths in `corpus_paths.json`.",
    "Access to each is by application to the holding organisation under its own agreement.")
rep("J", "The corpora and any derivative that could reconstruct a participant's speech are excluded from the repository: recordings and transcripts alike, from every corpus. The Cookie Theft picture belongs to a published test and is not redistributed; the platform shows the scene drawn for this project instead, with the consequence measured in section 4.3.1. The committed feature matrices are per-recording summary statistics and are retained because the reconstructions of Chapter 5 run from them; they contain no words.",
    "The corpora and any derivative that could reconstruct a participant's speech are excluded from the repository, recordings and transcripts alike. The Cookie Theft picture belongs to a published test and is not redistributed; the platform shows the scene drawn for this project instead, with the consequence measured in section 4.3.1. The committed feature matrices are per-recording summary statistics, retained because the reconstructions of Chapter 5 run from them; they contain no words.")
rep("J", "Chapter 5 reports a probe that changes nothing about what the frozen model can claim as one row of Table (5.9) rather than as a section, and several figures and tables whose content a retained table already carries were retired from the document. Every retired item is reachable from Table (J.4):",
    "Chapter 5 reports a probe that changes nothing about what the frozen model can claim as one row of Table (5.9) rather than as a section, and figures and tables whose content a retained table already carries were retired from the document. Every retired item is reachable from Table (J.4):")

# ---- Appendix G (last page 30% blank) ----
rep("G", "This appendix is the full record of the transcription artefact summarised in section 3.2.1: what the defect is, how large it is, why it correlates with diagnosis, why it survived a guard designed to exclude exactly this class of contamination, what it costs, and why it was left in place. Sources:",
    "This appendix is the full record of the transcription artefact summarised in section 3.2.1: the defect, its size, why it correlates with diagnosis, why it survived a guard designed to exclude exactly this class of contamination, what it costs, and why it was left in place. Sources:")
rep("G", "The reason this is more than a typo is that the rate differs by diagnosis, as Table (G.1) shows: the Pittsburgh artefact alone discriminates at 0.6908, above most individual deployed features, while the same convention at different sites with different transcribers occurs an order of magnitude less often and discriminates at chance — and a genuine phonetic property of impaired speech would not be ten times rarer in another cohort of impaired speakers. This is a Pittsburgh transcription practice that correlates with diagnosis.",
    "This is more than a typo because the rate differs by diagnosis, as Table (G.1) shows: the Pittsburgh artefact alone discriminates at 0.6908, above most individual deployed features, while the same convention at different sites with different transcribers occurs an order of magnitude less often and discriminates at chance — and a genuine phonetic property of impaired speech would not be ten times rarer in another impaired cohort. This is a Pittsburgh transcription practice that correlates with diagnosis.")
rep("G", "The guard was correct in principle and incomplete in execution, and it took a hand audit of the raw text to find the residue: excluding a contaminated feature family does not exclude the contamination if it is also inside the input.",
    "The guard was correct in principle and incomplete in execution, and a hand audit of the raw text found the residue: excluding a contaminated feature family does not exclude the contamination if it is also inside the input.")
rep("G", "The Pittsburgh AUC moved from 0.8095 to 0.7996, a difference of −0.0099 against a pre-registered material band of −0.01: the registered grade is ARTEFACT-NEGLIGIBLE, by one ten-thousandth, and the number, the band and the margin are all reported because the grade without the margin would be a rounding.",
    "The Pittsburgh AUC moved from 0.8095 to 0.7996, −0.0099 against a pre-registered material band of −0.01: the registered grade is ARTEFACT-NEGLIGIBLE, by one ten-thousandth, and number, band and margin are all reported because the grade without the margin would be a rounding.")
rep("G", "Two further readings follow. The artefact is also a train/serve mismatch: the application transcribes with a speech recogniser that emits standard orthography, so the parenthesised form cannot occur at inference, the model was fitted partly on a signal channel that does not exist in deployment, and 0.7996 is the closer estimate of what the deployed system receives. And the external result cannot be artefact-driven:",
    "Two further readings follow. The artefact is also a train/serve mismatch: the application transcribes with a recogniser that emits standard orthography, so the parenthesised form cannot occur at inference, the model was fitted partly on a channel that does not exist in deployment, and 0.7996 is the closer estimate of what the deployed system receives. And the external result cannot be artefact-driven:")
rep("G", "Two details complete the record. First, a corroborating observation from the descriptive check: one Lu file's group header reads `Conrol`, and the locked 27 control / 26 impaired split adds up exactly only if that file was handled as a control, which the corpus build did. Second, the sourcing of the counts:",
    "Two details complete the record. First, one Lu file's group header reads `Conrol`, and the locked 27 control / 26 impaired split adds up exactly only if that file was handled as a control, which the corpus build did. Second, the sourcing of the counts:")

# ---- Chapter 2 (last page 49% blank) ----
rep("c2", "The review is organised around one fact about the third part, because it decides how everything in the second may be read:",
    "The review is organised around one fact about the third part, which decides how everything in the second may be read:")
rep("c2", "The corpora are few and load-bearing. DementiaBank, the dementia section of the TalkBank archive, is the field's canonical repository, and its Pittsburgh corpus — picture descriptions collected longitudinally in the 1980s — is the dataset on which most published results rest [5, 6].",
    "The corpora are few and load-bearing. DementiaBank, the dementia section of the TalkBank archive, is the field's canonical repository, and its Pittsburgh corpus — picture descriptions collected longitudinally in the 1980s — is the dataset on which most published results rest [5, 6].")
rep("c2", "Their model fine-tunes a contextual representation on raw text, which can absorb transcription-convention differences as incidental variation; this project's model reads hand-crafted count features, which are made of exactly the conventions that differ between transcription teams, and the Wisconsin corpus is 100% healthy speakers, so pooling it makes corpus membership nearly equivalent to class membership — this project measured two studies' healthy speakers as separable at AUC 0.930 on transcription convention alone (section 3.2.1) and derived the rule that corpora are combined only when each contributes both classes.",
    "Their model fine-tunes a contextual representation on raw text, which can absorb transcription-convention differences as incidental variation; this project's model reads hand-crafted count features, made of exactly the conventions that differ between transcription teams, and the Wisconsin corpus is 100% healthy speakers, so pooling it makes corpus membership nearly equivalent to class membership — this project measured two studies' healthy speakers as separable at AUC 0.930 on transcription convention alone (section 3.2.1) and derived the rule that corpora are combined only when each contributes both classes.")
rep("c2", "Table (2.1) assembles the published figures beside this work's, sorted by evaluation regime from weakest to strongest, with the metric named in every row — almost all of this literature reports accuracy, so accuracy is the column to compare, and this project's accuracy is stated alongside its AUC for that purpose. Its development accuracy on Pittsburgh at a 0.50 threshold is 0.759 against a majority-class baseline of 0.557, and every figure in the Dhikra rows was recomputed from the committed prediction files before being printed here [7, 9, 10].",
    "Table (2.1) assembles the published figures beside this work's, sorted by evaluation regime from weakest to strongest, with the metric named in every row — almost all of this literature reports accuracy, so this project's accuracy is stated alongside its AUC. Its development accuracy on Pittsburgh at a 0.50 threshold is 0.759 against a majority-class baseline of 0.557, and every figure in the Dhikra rows was recomputed from the committed prediction files [7, 9, 10].")
rep("c2", "The single most important fact for positioning this project's results is that published dementia-detection models have not been shown to transfer between corpora.",
    "The most important fact for positioning this project's results is that published dementia-detection models have not been shown to transfer between corpora.")
rep("c2", "Within each corpus their models performed normally: 0.771 unweighted average recall on ADReSS with linguistic features, 0.860 on ILSE with acoustic features. Across corpora, in their own words, the results were \"barely above chance level\", with one exception — perplexity features reaching 0.625 on ADReSS from an ILSE-trained model — and no domain-adaptation method recovered the loss, because none was systematically attempted [12].",
    "Within each corpus their models performed normally, 0.771 unweighted average recall on ADReSS with linguistic features and 0.860 on ILSE with acoustic features; across corpora, in their own words, the results were \"barely above chance level\", with one exception — perplexity features reaching 0.625 on ADReSS from an ILSE-trained model — and no domain-adaptation method recovered the loss, because none was systematically attempted [12].")
rep("c2", "The project's own Lu-free transfer arms sit in the same regime and agree: Delaware to Pittsburgh 0.777 [0.730, 0.826] and Pittsburgh to Delaware 0.646 [0.587, 0.704], both lower bounds above chance (section 5.12). Table (2.2) states the comparison at the level that carries the argument.",
    "The project's own Lu-free transfer arms sit in the same regime and agree: Delaware to Pittsburgh 0.777 [0.730, 0.826] and Pittsburgh to Delaware 0.646 [0.587, 0.704], both above chance (section 5.12). Table (2.2) states the comparison at the level that carries the argument.")
rep("c2", "The features of this literature sort into three tiers by what a positive finding means. Clinically motivated measures — information units, idea density, lexical diversity, syntactic complexity, reference and cohesion — connect a classifier's behaviour to constructs the clinical literature already interprets, and they are the tier this project deploys (section 3.3). Standard clinical voice measures — fundamental frequency, jitter and shimmer, pause and timing statistics — are established and language-independent but require usable audio, which is why this project implements them in a separate acoustic model that never enters the deployed screening score. And convention features — MFCCs and their derivatives, and learned embeddings — carry discriminative power with little interpretive content; this project excludes them from deployment on interpretability and hardware grounds, and reports the measured cost of that exclusion rather than asserting it is free (section 5.1.2) [3, 4].",
    "The features of this literature sort into three tiers by what a positive finding means. Clinically motivated measures — information units, idea density, lexical diversity, syntactic complexity, reference and cohesion — connect a classifier's behaviour to constructs the clinical literature already interprets, and they are the tier this project deploys (section 3.3). Standard clinical voice measures — fundamental frequency, jitter and shimmer, pause and timing statistics — are established and language-independent but require usable audio, which is why this project implements them in a separate acoustic model that never enters the deployed screening score. Convention features — MFCCs and their derivatives, and learned embeddings — carry discriminative power with little interpretive content; this project excludes them from deployment on interpretability and hardware grounds and reports the measured cost of that exclusion (section 5.1.2) [3, 4].")
rep("c2", "The remainder of the Arabic landscape divides into acoustic probes and structured instruments. A Tunisian Arabic database supports early-detection work built on voice onset time — an acoustic, phonetic measure, not connected-speech analysis — and the database is not publicly accessible [14]. An Arabic transcript dataset has been used to classify Alzheimer's from linguistic and acoustic features with standard machine-learning methods, again without public release [15].",
    "The remainder of the Arabic landscape divides into acoustic probes and structured instruments. A Tunisian Arabic database supports early-detection work built on voice onset time — an acoustic, phonetic measure, not connected-speech analysis — and is not publicly accessible [14]. An Arabic transcript dataset has been used to classify Alzheimer's from linguistic and acoustic features with standard machine-learning methods, again without public release [15].")
rep("c2", "The nearest linguistically serious work is Taiebine and El Alaoui Faris's adaptation and preliminary validation of the Mini-Linguistic State Examination for Moroccan Arabic, together with their earlier acoustic and neurolinguistic case study of logopenic primary progressive aphasia in Arabic — instrument adaptation and case description, not automated screening [17, 18].",
    "The nearest linguistically serious work is Taiebine and El Alaoui Faris's adaptation and preliminary validation of the Mini-Linguistic State Examination for Moroccan Arabic, with their earlier acoustic and neurolinguistic case study of logopenic primary progressive aphasia in Arabic — instrument adaptation and case description, not automated screening [17, 18].")
rep("c2", "To the author's knowledge, no publicly available Libyan Arabic connected-speech corpus for dementia screening has been published, and no prior work has adapted spontaneous picture-description analysis to Arabic. Both clauses are stated at exactly that strength and no more: the searches behind them, with their limits and the near-misses on either side of the gap, are documented in section 6.4, and the claim is falsifiable — a single counterexample retires it. What the two arguments of this chapter jointly establish is the thesis's position.",
    "To the author's knowledge, no publicly available Libyan Arabic connected-speech corpus for dementia screening has been published, and no prior work has adapted spontaneous picture-description analysis to Arabic. Both clauses are stated at exactly that strength: the searches behind them, with their limits and the near-misses on either side of the gap, are documented in section 6.4, and a single counterexample retires the claim. What the two arguments of this chapter jointly establish is the thesis's position.")

for k, v in FILES.items():
    open(v, "w", encoding="utf-8").write(T[k]); print(k, "words", B[k], "->", len(T[k].split()))
