#!/usr/bin/env python3
"""cut2_ch4.py -- tighten Chapter 4 after cut_ch4.py: captions, Table (4.4) cells and connective prose. Every number,
grade and caveat kept; the two quoted caveats are submitted text and untouched."""
P = "/home/claude/work/src/docs/chapters/chapter4.md"
t = open(P, encoding="utf-8").read()
before = len(t.split())
def sub1(old, new):
    global t
    assert t.count(old) == 1, (old[:70], t.count(old)); t = t.replace(old, new)

# captions
sub1("**Figure (4.1) : System architecture. The screening decision is computed from the picture description alone, the only task with healthy controls in the training corpora; story recall, verbal fluency and Qur'anic recitation contribute severity estimation and supporting context and never enter the screening decision; procedural discourse is recorded as connected-discourse material for the successor corpus and is not analysed.**",
     "**Figure (4.1) : System architecture. The screening decision is computed from the picture description alone, the only task with healthy controls in the training corpora; story recall, verbal fluency and Qur'anic recitation contribute severity estimation and context only; procedural discourse is recorded for the successor corpus and not analysed.**")
sub1("**Figure (4.2) : The three picture-description stimuli, drawn for this project and matched on a content specification so that information-unit scoring is comparable across them. The kitchen scene is the only one against which the screening model is calibrated; the courtyard and market scenes exist so that a repeat assessment need not reuse a picture the participant has already described, and the system refuses to produce a score for either. The kitchen panel is the artwork as corrected when an audit of the frozen scoring key against the rendered scene found two scored units missing and three occluded; what the substitution still costs, and cannot stop costing, is measured in section 4.3.1.**",
     "**Figure (4.2) : The three picture-description stimuli, drawn for this project and matched on one content specification. Only the kitchen scene is calibrated; the courtyard and market scenes serve repeat assessments and the system refuses to score either. The kitchen panel is the artwork as corrected after the audit of section 4.3.1, which also measures what the substitution still costs.**")

# 4.1
sub1("Automatic transcription is used when the recogniser's weights are present; when they are not, the platform does not invent text but asks the operator to type the transcript, which is how the reference corpora themselves were produced, so a missing network costs convenience, never validity, and a missing model bundle still leaves a working platform that reports an indicator profile and never claims a screening score it cannot justify.",
     "Automatic transcription is used when the recogniser's weights are present; when they are not, the platform asks the operator to type the transcript, which is how the reference corpora themselves were produced, so a missing network costs convenience, never validity, and a missing model bundle still leaves a working platform that reports an indicator profile and never claims a screening score it cannot justify.")

# 4.2
sub1("Each task has a published basis: delayed story recall probes the earliest-declining domain and predicts progression from mild impairment to dementia, with the examiner-supplied story a project-authored instrument in that paradigm rather than a normed test [3]; sixty-second animal fluency is the standard batteries' own form, with age- and education-stratified norms [4, 5]; and the recitation probe rests on the documented survival of early-acquired, long-rehearsed material, musical memory being the strongest published analogue, while the task itself is validated nowhere and is framed as exploratory [6].",
     "Each task has a published basis: delayed story recall probes the earliest-declining domain and predicts progression from mild impairment to dementia, the examiner-supplied story being a project-authored instrument in that paradigm rather than a normed test [3]; sixty-second animal fluency is the standard batteries' own form, with age- and education-stratified norms [4, 5]; and the recitation probe rests on the documented survival of early-acquired, long-rehearsed material, musical memory being the strongest published analogue, while the task itself is validated nowhere and is framed as exploratory [6].")
sub1("The report repeats the same fact to the operator in plain language. Repeat visits do not reuse material: selection from the three matched pictures, three twelve-proposition stories and the surah bank rotates deterministically from participant code and session number, so a repeat visit receives a different form while any session reproduces exactly from its recorded stimulus identifiers; the first English visit is the exception, since the validated scene is shown by default.",
     "The report repeats the same fact to the operator in plain language. Repeat visits do not reuse material: selection from the three matched pictures, three twelve-proposition stories and the surah bank rotates deterministically from participant code and session number, so a repeat visit receives a different form while any session reproduces exactly from its recorded stimulus identifiers, the first English visit excepted, since the validated scene is shown by default.")

# 4.3
sub1("A picture-description task is a measuring instrument: its scores are comparable only because every participant faces the same measured difficulty, which is why the field has kept one standard picture for decades — a different image each session would make the tool look more advanced while making its numbers meaningless. The correct response to repeat testing is parallel forms:",
     "A picture-description task is a measuring instrument: its scores are comparable only because every participant faces the same measured difficulty, which is why the field has kept one standard picture for decades — a different image each session would make the tool look more advanced while making its numbers meaningless. The correct response to repeat testing is parallel forms:")

# 4.3.1
sub1("Substituting a stimulus while keeping a model fitted on the original was the single largest unexamined assumption in the deployed pipeline, and it was examined [7, 8, 9].",
     "Substituting a stimulus while keeping a model fitted on the original was the largest unexamined assumption in the deployed pipeline, and it was examined [7, 8, 9].")
sub1("The only possible effect of the unscored content is behavioural — attention spent naming what earns nothing is attention not spent naming what the scorer counts — and its magnitude on real speakers is unknowable without Libyan data, so the pre-registered analysis asked the inverse question: how many units would the substitution have to cost a speaker before the screening decision changes? Table (4.2) is the answer.",
     "The only possible effect of the unscored content is behavioural — attention spent naming what earns nothing is attention not spent naming what the scorer counts — and its magnitude on real speakers is unknowable without Libyan data, so the pre-registered analysis asked the inverse question, how many units the substitution would have to cost a speaker before the screening decision changes; Table (4.2) is the answer.")
sub1("Whether the substituted picture costs real speakers anything is unknown and cannot be known without Libyan data, which is why the pilot protocol carries a pre-specified stimulus-equivalence endpoint. One post-hoc diagnostic does not change the grade: the report already refuses a confident call within 0.1032 of the threshold, a band holding 45.3% of control recordings at baseline, and 93.6% of the controls that cross at one displaced unit were already inside it, so the borderline caveat absorbs almost the whole small-displacement effect; at six displaced units the protection fails (46.1%), which is why the substitution caveat of section 4.5 attaches to every score rather than to borderline ones. This section must not be conflated with the scorer-agreement check of section 5.5.1, which measures the lexical matching rule on transcripts of the real Cookie Theft rather than the picture: a hand count runs about 1.5 units above the software and a substituted picture may cost a speaker units, but the offsets have never been measured together and nothing may be inferred from their opposite signs.",
     "Whether the substituted picture costs real speakers anything is unknown without Libyan data, which is why the pilot protocol carries a pre-specified stimulus-equivalence endpoint. One post-hoc diagnostic does not change the grade: the report already refuses a confident call within 0.1032 of the threshold, a band holding 45.3% of control recordings at baseline, and 93.6% of the controls that cross at one displaced unit were already inside it, so the borderline caveat absorbs almost the whole small-displacement effect; at six displaced units the protection fails (46.1%), which is why the substitution caveat of section 4.5 attaches to every score. This section must not be conflated with the scorer-agreement check of section 5.5.1, which measures the lexical matching rule on transcripts of the real Cookie Theft: a hand count runs about 1.5 units above the software and a substituted picture may cost a speaker units, but the offsets have never been measured together and nothing may be inferred from their opposite signs.")

# 4.4
sub1("What the operator receives is designed around the instrument's measured limits rather than around completeness. The screening result is a band",
     "What the operator receives is designed around the instrument's measured limits. The screening result is a band")

# 4.5
sub1("A system that always returns a number is more dangerous than one that sometimes declines, because a score computed from ten seconds of mumbling in a noisy corridor is formatted exactly like a valid one.",
     "A system that always returns a number is more dangerous than one that sometimes declines, because a score computed from ten seconds of mumbling in a noisy corridor is formatted exactly like a valid one.")
sub1("Beyond refusing, the system confesses. Every screening score from the validated picture is delivered alongside the statement that the picture is a substitute, with the measured consequence of section 4.3.1 attached, because the system has no evidence that would justify withholding the score and none that would justify presenting it as though the substitution were free. The caveat is quoted in full, because it is submitted text:",
     "Beyond refusing, the system confesses. Every screening score from the validated picture is delivered with the statement that the picture is a substitute and the measured consequence of section 4.3.1 attached, because the system has no evidence that would justify withholding the score and none that would justify presenting the substitution as free. The caveat is quoted in full, because it is submitted text:")

# 4.5.1
sub1("Neither raised an error; both produced a number of exactly the expected type and range, and that is not coincidence — a median imputer is designed to substitute, a scorer is designed to return zero for an unmentioned unit, and at the interface a degraded value is indistinguishable from a legitimate one. The remedy is the one section 3.10 prescribes for registrations, extended to the deployed system: the startup banner states whether the vector model is present, and the report names each substitution when it occurs — the caveats quoted above are that remedy, running in the shipped code. The system is not more accurate for saying any of it; it is more honest, and the difference between those properties is what this chapter is about. The general form of the pattern — every defect this project found in its own analysis, artwork and deployment was silent until something outside the failing component was built to say so — belongs to the conclusions, and Chapter 6 states it.",
     "Neither raised an error; both produced a number of exactly the expected type and range, and that is not coincidence — a median imputer is designed to substitute, a scorer to return zero for an unmentioned unit, and at the interface a degraded value is indistinguishable from a legitimate one. The remedy is the one section 3.10 prescribes for registrations, extended to the deployed system: the startup banner states whether the vector model is present, and the report names each substitution when it occurs — the caveats quoted above are that remedy, running in the shipped code. The system is not more accurate for saying any of it; it is more honest, and the difference between those properties is what this chapter is about. The general form of the pattern — every defect this project found was silent until something outside the failing component was built to say so — belongs to the conclusions (section 6.1).")

# 4.6 and Table (4.4) cells
sub1("Table (4.4) collects on one page every verification activity the project performed on the system as built, with the method and the outcome of each; the sections and appendices named in the table own the detail, and the table adds no result of its own.",
     "Table (4.4) collects every verification activity performed on the system as built, with method and outcome; the sections and appendices named own the detail, and the table adds no result of its own.")
sub1("| Architecture recovered by introspection of the deployed artefact under the pinned scikit-learn 1.8.0, no training script having been committed, and checked against seven pre-registered signatures of the locked outputs (Appendix C) | 7 of 7 signatures matched; the acoustic model's embedded figure reproduces from a fresh fit by committed code (Appendix F) |",
     "| Architecture recovered by introspection of the deployed artefact under the pinned scikit-learn 1.8.0, no training script having been committed, and checked against seven pre-registered signatures of the locked outputs (Appendix C) | 7 of 7 signatures matched; the acoustic model's embedded figure reproduces from a fresh fit by committed code (Appendix F) |")
sub1("| Eight controlled degradations applied to the recordings, each of nine acoustic measures correlated with its clean value (section 5.9) | Robust to compression, 8 kHz resampling, low volume, clipping and distance; pause measures degrade at 20 dB and extraction fails at 10 dB, which sets the refusal threshold of Table (4.3) |",
     "| Eight controlled degradations, each of nine acoustic measures correlated with its clean value (section 5.9) | Robust to compression, 8 kHz resampling, low volume, clipping and distance; pause measures degrade at 20 dB and extraction fails at 10 dB, which sets the refusal threshold of Table (4.3) |")
sub1("| The automated scorer against a human rater on 20 blind transcripts, graded against a pre-registered criterion of mean absolute difference ≤ 1.200 (section 5.5.1) | 1.600, grade INADEQUATE; a near-constant undercount of about 1.5 units with rank order preserved (ICC 0.904), so the AUC results survive and the pilot's scoring rule binds (Appendix B) |",
     "| The automated scorer against a human rater on 20 blind transcripts, pre-registered criterion mean absolute difference ≤ 1.200 (section 5.5.1) | 1.600, grade INADEQUATE; a near-constant undercount of about 1.5 units with rank order preserved (ICC 0.904), so the AUC results survive and the pilot's scoring rule binds (Appendix B) |")
sub1("| Controls at successive annual visits taken as the estimate of instrument noise (123 pairs), and the probability that a repeat recording lands on the same side of the threshold (section 5.14.1) | Standard error of measurement 0.103, minimal detectable change 0.286; decision reproducibility 0.8355, 0.669 near the threshold and 0.954 away from it — the basis of the three-band report |",
     "| Controls at successive annual visits as the estimate of instrument noise (123 pairs), and the probability that a repeat recording lands on the same side of the threshold (section 5.14.1) | Standard error of measurement 0.103, minimal detectable change 0.286; decision reproducibility 0.8355, 0.669 near the threshold and 0.954 away from it — the basis of the three-band report |")
sub1("| Four refusal conditions enforced in code; the noise and clipping thresholds derived from the degradation experiment, the three minima asserted (section 4.5) | The passing path was exercised end to end by the demonstration session of Appendix E; the refusal branches themselves have no committed test, and that test is assigned to the pilot |",
     "| Four refusal conditions enforced in code; noise and clipping thresholds from the degradation experiment, the three minima asserted (section 4.5) | The passing path was exercised end to end by the demonstration session of Appendix E; the refusal branches have no committed test, which is assigned to the pilot |")
sub1("| At startup the platform reports whether the word-vector model behind nine features is present, and every report names any feature substituted by a training average (section 4.5.1) | Implemented after the installer defect was found; the demonstration session's report carried the stimulus caveat only, so no feature was substituted in that run (Appendix E) |",
     "| The platform reports at startup whether the word-vector model behind nine features is present, and every report names any feature substituted by a training average (section 4.5.1) | Implemented after the installer defect was found; the demonstration session's report carried the stimulus caveat only, so no feature was substituted in that run (Appendix E) |")
sub1("| One execution on the external corpus at the threshold fixed in advance, under the governance of section 3.9, then reproduced once under a protocol permitting one execution and no decision (sections 3.9.1 and 5.3) | AUC 0.8533 [0.7371, 0.9458], sensitivity 96.2% and specificity at the pre-specified threshold diagnosed in section 5.13; the reproduction matched to ten decimal places and cell for cell, and a tombstone file blocks any further run |",
     "| One execution on the external corpus at the threshold fixed in advance, under the governance of section 3.9, then reproduced once under a protocol permitting one execution and no decision (sections 3.9.1 and 5.3) | AUC 0.8533 [0.7371, 0.9458], sensitivity 96.2%, specificity at the pre-specified threshold diagnosed in section 5.13; the reproduction matched to ten decimal places and cell for cell, and a tombstone file blocks any further run |")

open(P, "w", encoding="utf-8").write(t)
print("chapter4 words", before, "->", len(t.split()))
