#!/usr/bin/env python3
"""cut2_appB.py -- compress Appendix B toward the register form: design, eligibility, consent, reference standard, battery,
endpoint decision, power, pre-registered secondary outcomes, analysis plan and timeline all kept; Table (B.5) and
Table (B.7) become sentences; verbatim prompts untouched."""
import re
P = "/home/claude/work/src/docs/chapters/_pending/appendix_b.md"
t = open(P, encoding="utf-8").read()
before = len(t.split())
def sub1(old, new):
    global t
    assert t.count(old) == 1, (old[:70], t.count(old)); t = t.replace(old, new)
def drop_table(caption_prefix):
    global t
    L = t.split("\n")
    a = next(k for k, l in enumerate(L) if l.startswith(caption_prefix))
    b = a + 1
    while b < len(L) and (L[b].startswith("|") or not L[b].strip()): b += 1
    del L[a:b]; t = "\n".join(L)

# preamble
sub1("This appendix reproduces the Libyan Arabic feasibility-study protocol committed in the project (`docs/libyan_pilot_protocol.md`, version 1.0), the document prepared for submission to the University of Tripoli research ethics committee, compressed to its operative content; justification the chapters already carry is cited rather than repeated. One statement of context governs the whole document, and it is Chapter 6's ruled wording (section 6.3): contact with clinicians has been initiated, no arrangement exists, and securing a named clinician is the first step of the pathway and not yet done. Wherever the protocol refers to \"the collaborating clinician\", it describes what would be required for the study to run, not an arrangement that exists.",
     "This appendix reproduces the Libyan Arabic feasibility-study protocol committed in the project (`docs/libyan_pilot_protocol.md`, version 1.0), prepared for submission to the University of Tripoli research ethics committee, compressed to its operative content; justification the chapters carry is cited rather than repeated. One statement of context governs the document, in Chapter 6's ruled wording (section 6.3): contact with clinicians has been initiated, no arrangement exists, and securing a named clinician is the first step of the pathway and not yet done. Wherever the protocol refers to \"the collaborating clinician\", it describes what would be required for the study to run, not an arrangement that exists.")
# B.1
sub1("A diagnostic accuracy study asks how well the tool detects impairment and requires roughly 240 participants to answer with any precision (Appendix I); a feasibility study asks whether elderly Libyan participants can complete the battery of four core assessment tasks plus one optional exploratory Qur'anic recitation probe, whether the recording setup produces analysable audio in a real clinic, whether the Arabic feature extractors run correctly on genuine Libyan dialectal speech rather than the Modern Standard Arabic they were drafted against, what the measurements look like in cognitively healthy Libyan speakers, and whether the closed-class word lists — fillers, vague nouns, demonstratives — are appropriate for Libyan dialect. **No diagnostic accuracy figure will be computed from this pilot and no Arabic AUC will be reported from it.** The need is documented in Chapter 1 and section 6.4 — no population-level dementia prevalence study exists for Libya [1, 2, 3], and no publicly available Arabic corpus pairs impaired and healthy speakers on a connected-speech task — and the instrument's Arabic component is an implemented method with no clinical validation; this pilot is the first step toward closing that gap.",
     "A diagnostic accuracy study asks how well the tool detects impairment and requires roughly 240 participants to answer with any precision (Appendix I); a feasibility study asks whether elderly Libyan participants can complete the four core tasks plus the optional exploratory Qur'anic recitation probe, whether the recording setup produces analysable audio in a real clinic, whether the Arabic feature extractors run correctly on Libyan dialectal speech rather than the Modern Standard Arabic they were drafted against, what the measurements look like in cognitively healthy Libyan speakers, and whether the closed-class word lists — fillers, vague nouns, demonstratives — fit Libyan dialect. **No diagnostic accuracy figure will be computed from this pilot and no Arabic AUC will be reported from it.** The need is documented in Chapter 1 and section 6.4 — no population-level dementia prevalence study exists for Libya [1, 2, 3], and no publicly available Arabic corpus pairs impaired and healthy speakers on a connected-speech task — and the instrument's Arabic component is an implemented method with no clinical validation.")
# B.3
sub1("The remedy for the instrument's weakest figure — its specificity on the locked external corpus at the pre-specified threshold, diagnosed in section 5.13 as a threshold-referencing failure — is control-referenced thresholding: the operating threshold set at a fixed percentile of the local cognitively healthy score distribution, so that specificity is fixed by construction and does not move with local prevalence. **That rule needs healthy speakers and no patients, which is precisely what this study's healthy stratum is**, so one recruitment delivers both the Arabic feature validation and the normative distribution from which a Libyan operating threshold can be derived.",
     "The remedy for the instrument's weakest figure — its specificity on the locked external corpus at the pre-specified threshold, diagnosed in section 5.13 as a threshold-referencing failure — is control-referenced thresholding: the operating threshold set at a fixed percentile of the local cognitively healthy score distribution, so that specificity is fixed by construction and does not move with local prevalence. **That rule needs healthy speakers and no patients, which is what this study's healthy stratum is**, so one recruitment delivers both the Arabic feature validation and the normative distribution from which a Libyan operating threshold can be derived.")
sub1("At 20 healthy participants the derived threshold is *provisional* — prospective specificity anywhere between 56% and 91% — and still a decisive improvement on a threshold transplanted from American cohorts, whose specificity in a Libyan clinic is unestimable. The 20-participant minimum stands for feasibility, every healthy participant beyond it directly buys threshold precision, and n ≥ 30 is the point at which the normative deliverable becomes worth publishing; roughly 59 buy a ±10-point interval and 108 a ±7.5-point one, figures for a follow-on normative study. The interval is a floor on the uncertainty: the Beta law assumes the control sample is drawn from the population the threshold will serve, and a convenience sample of families of clinic attendees and staff relatives is plausibly healthier, better educated and younger than the population a deployed instrument would meet. A healthier-than-typical control sample produces lower scores, so the derived threshold sits lower than it should and the instrument over-refers rather than under-refers; that error direction favours sensitivity over missed cases, but excess false positives remain an equity, anxiety and resource-use concern, so education, residence and age are recorded for every healthy participant and the threshold is reported recomputed with the sample reweighted to the local population where census figures allow. The in-sample bootstrap interval reported for the rule on the external corpus answers how precisely the rule hits its own target; the Beta interval answers what a new population would experience; the two are never interchanged.",
     "At 20 healthy participants the derived threshold is *provisional* — prospective specificity anywhere between 56% and 91% — and still a decisive improvement on a threshold transplanted from American cohorts, whose specificity in a Libyan clinic is unestimable. The 20-participant minimum stands for feasibility, every healthy participant beyond it buys threshold precision, and n ≥ 30 is the point at which the normative deliverable becomes worth publishing; roughly 59 buy a ±10-point interval and 108 a ±7.5-point one, figures for a follow-on normative study. The interval is a floor on the uncertainty: the Beta law assumes the control sample is drawn from the population the threshold will serve, and a convenience sample of families of clinic attendees and staff relatives is plausibly healthier, better educated and younger than the population a deployed instrument would meet. A healthier-than-typical control sample produces lower scores, so the derived threshold sits too low and the instrument over-refers rather than under-refers — an error direction that favours sensitivity over missed cases, though excess false positives remain an equity, anxiety and resource-use concern — so education, residence and age are recorded for every healthy participant and the threshold is also reported recomputed with the sample reweighted to the local population where census figures allow. The in-sample bootstrap interval reported for the rule on the external corpus answers how precisely the rule hits its own target; the Beta interval answers what a new population would experience; the two are never interchanged.")
# B.4
sub1("For participants with capacity: written informed consent in Arabic after a verbal explanation, the information sheet stating that participation is voluntary, that refusal affects no aspect of their care, that they may withdraw at any time without giving a reason, and that withdrawal deletes their recording. For participants with impaired capacity: written consent from a legally authorised representative plus ongoing assent from the participant, assent being behavioural as much as verbal — if the participant becomes distressed, refuses a task or asks to stop, the session ends, and consent from a relative does not override the participant's own reluctance in the moment.",
     "For participants with capacity: written informed consent in Arabic after a verbal explanation, the information sheet stating that participation is voluntary, that refusal affects no aspect of their care, that they may withdraw at any time without giving a reason, and that withdrawal deletes their recording. For participants with impaired capacity: written consent from a legally authorised representative plus ongoing assent from the participant, behavioural as much as verbal — if the participant becomes distressed, refuses a task or asks to stop, the session ends, and a relative's consent does not override the participant's own reluctance in the moment.")
sub1("The form is drafted (`docs/forms/CONSENT_FORM_ar.md`) with the assent acknowledgement placed above the representative's signature and five fields left bracketed because they cannot be invented — approval number, complaints contact, retention period, withdrawal window, site. No participant in any stratum is given a screening result, because disclosing to one stratum and not another makes the silence itself informative; any participant or family expressing concern about memory is advised to consult the collaborating clinician in the normal way.",
     "The form is drafted (`docs/forms/CONSENT_FORM_ar.md`) with the assent acknowledgement above the representative's signature and five fields left bracketed because they cannot be invented — approval number, complaints contact, retention period, withdrawal window, site. No participant in any stratum is given a screening result, because disclosing to one stratum and not another makes the silence itself informative; a participant or family expressing concern about memory is advised to consult the collaborating clinician in the normal way.")
# B.6
sub1("The battery leads with connected discourse because the pre-registered task-count probe of section 5.15 found that for mild cognitive impairment picture description is the weakest of five tasks and performs at chance, while two discourse tasks together beat three picture tasks together (+0.079 [+0.004, +0.158]); picture description is retained unchanged for the dementia target, where it alone has an externally evaluated model behind it. Story recall uses an examiner-supplied story retold immediately, so no cultural knowledge of a narrative is required, in the paradigm of Craft Story 21 of the NACC Uniform Data Set; procedural discourse requires no stimulus material, which makes it the one task that survives intact in a paper fallback, and making tea is chosen because every participant has performed it hundreds of times. Elicitation is fixed and logged because word count is the strongest single mild-impairment marker on connected discourse (section 5.10.1), so variable elicitation would record examiner behaviour, and because the flagged healthy speakers of the locked external corpus had described the picture genuinely thinly while a minimum-length rule was tested and refused (section 5.13): for every task and every participant the prompt is read verbatim, the maximum duration is enforced, the re-prompt rule is at most two probes using the exact wording *\"tell me anything else you can\"*, each after 10 s of silence, and elicitation time and probe count are recorded as metadata. The Qur'anic probe additionally records which surah was recited, self-reported familiarity, approximate age at memorisation and any formal tajweed training, the confounders without which recitation accuracy is uninterpretable.",
     "The battery leads with connected discourse because the pre-registered task-count probe of section 5.15 found that for mild cognitive impairment picture description is the weakest of five tasks and performs at chance, while two discourse tasks together beat three picture tasks together (+0.079 [+0.004, +0.158]); picture description is retained unchanged for the dementia target, where it alone has an externally evaluated model behind it. Story recall uses an examiner-supplied story retold immediately, so no cultural knowledge of a narrative is required, in the paradigm of Craft Story 21 of the NACC Uniform Data Set; procedural discourse requires no stimulus material, so it is the one task that survives intact in a paper fallback, and making tea is chosen because every participant has performed it hundreds of times. Elicitation is fixed and logged because word count is the strongest single mild-impairment marker on connected discourse (section 5.10.1), so variable elicitation would record examiner behaviour, and because the flagged healthy speakers of the locked external corpus had described the picture thinly while a minimum-length rule was tested and refused (section 5.13): for every task and every participant the prompt is read verbatim, the maximum duration is enforced, the re-prompt rule is at most two probes using the exact wording *\"tell me anything else you can\"*, each after 10 s of silence, and elicitation time and probe count are recorded. The Qur'anic probe additionally records which surah was recited, self-reported familiarity, approximate age at memorisation and any formal tajweed training, the confounders without which recitation accuracy is uninterpretable.")
# B.7
sub1("The operator does not prompt with example words during verbal fluency, does not fill silences — pauses are the measurement — and does not correct, complete or comment on the participant's speech. Participants are identified only by code, with the linking key held separately by the clinician; recordings are stored encrypted on an unshared device, carry no names, national identifiers, addresses or telephone numbers, are deleted on withdrawal, are retained for the period the ethics committee specifies, and are neither uploaded to any third-party service nor shared outside the named research team without a further ethics amendment.",
     "The operator does not prompt with example words during verbal fluency, does not fill silences — pauses are the measurement — and does not correct, complete or comment on the participant's speech. Participants are identified only by code, with the linking key held separately by the clinician; recordings are stored encrypted on an unshared device, carry no names, national identifiers, addresses or telephone numbers, are deleted on withdrawal, are retained for the period the ethics committee specifies, and are neither uploaded to any third-party service nor shared outside the named research team without a further ethics amendment.")
# B.8.1 — Table (B.5) becomes a sentence
sub1("This subsection fixes the design of the study the pilot exists to make possible, so that the decision is on the record before recruitment starts. **The primary endpoint is dementia versus healthy controls, powered**, for three reasons forced by evidence this project already holds:",
     "This subsection fixes the design of the study the pilot exists to make possible, so that the decision is on the record before recruitment starts. **The primary endpoint is dementia versus healthy controls, powered**, for three reasons forced by evidence the project already holds:")
sub1("The objection that a dementia-only cohort discards the reason the battery administers both genres is answered by Table (B.5): group and task are different axes, and every participant receives both genres whoever is recruited. This is section 1.7 applied to a study design — the powered arm and the descriptive arm are reported separately and never in the same table.",
     "The objection that a dementia-only cohort discards the reason the battery administers both genres fails because group and task are different axes: the group axis (dementia, mild impairment, control) is decided here, and the task axis is decided by the battery, which administers both genres to every participant whoever is recruited. This is section 1.7 applied to a study design — the powered arm and the descriptive arm are reported separately and never in the same table.")
drop_table("**Table (B.5)")
# B.8.2
sub1("This study cannot test the referential deficit index, and the arithmetic belongs in the protocol rather than being discovered later. The index's pronoun-free form, which is structurally what the Arabic index is, reaches AUC 0.596 on Pittsburgh and 0.625 on the age- and sex-matched subset (section 5.10.1), so the expectation for an Arabic dementia sample is roughly 0.60; detecting a true AUC of 0.60 at 80% power requires 130 participants per group, and this study's 20 per group detects only a true AUC of 0.748 or larger (Hanley–McNeil, two-sided α = 0.05; Table (B.6)), so a null result here would be uninterpretable and must not be reported as evidence against the index. No effect this project has measured is that large, and a study that reported a null at this size would be reporting the sample size, not the instrument; the sizes that could test either effect are about 130 per group for the mild-impairment discourse effect and 141 for the dementia referential effect (Appendix I). Two earlier figures in this section were corrected and the corrections are kept on the record: 75 per group for the discourse effect rested on a selection-inflated estimate withdrawn in section 5.16, and a detectable AUC of 0.645 was the figure for sixty per group, not twenty.",
     "This study cannot test the referential deficit index, and the arithmetic belongs in the protocol rather than being discovered later. The index's pronoun-free form, structurally what the Arabic index is, reaches AUC 0.596 on Pittsburgh and 0.625 on the age- and sex-matched subset (section 5.10.1), so the expectation for an Arabic dementia sample is roughly 0.60; detecting a true AUC of 0.60 at 80% power requires 130 participants per group, and this study's 20 per group detects only a true AUC of 0.748 or larger (Hanley–McNeil, two-sided α = 0.05; Table (B.5)), so a null result here would be uninterpretable and must not be reported as evidence against the index. No effect this project has measured is that large; the sizes that could test either effect are about 130 per group for the mild-impairment discourse effect and 141 for the dementia referential effect (Appendix I). Two earlier figures in this section were corrected and the corrections are kept on the record: 75 per group for the discourse effect rested on a selection-inflated estimate withdrawn in section 5.16, and a detectable AUC of 0.645 was the figure for sixty per group, not twenty.")
sub1("**Table (B.6) : Minimum detectable true AUC at 80% power by group size**", "**Table (B.5) : Minimum detectable true AUC at 80% power by group size**")
# B.8.3
sub1("Every scorer is therefore trained against the committed coding rules (`docs/scorer_check/CODING_RULES.md`) before collection begins, a subsample of at least ten sessions is double-scored by a second person, and because a person counting by hand arrives at roughly 1.5 more units than the software for the same speech, the paper instrument takes its cut-off from hand-scored local controls and never from the software's.",
     "Every scorer is therefore trained against the committed coding rules (`docs/scorer_check/CODING_RULES.md`) before collection begins, a subsample of at least ten sessions is double-scored by a second person, and because a hand count arrives at roughly 1.5 more units than the software for the same speech, the paper instrument takes its cut-off from hand-scored local controls and never from the software's.")
sub1("For every participant the information-unit count from the kitchen scene is computed with its per-unit indicators, and the report gives each unit's production rate with an exact binomial interval, the count of units produced by fewer than 5% of the healthy stratum — the operational definition of a unit the picture fails to elicit — and the healthy stratum's total-unit distribution against the Pittsburgh control distribution, compared as full distributions. The comparison cannot separate stimulus from population, language and era, so it is reported as a bound: comparable production means the substitution is probably not costing much; markedly lower production means the cause is unidentified and the threshold must be re-derived locally rather than inherited. Any unit produced by fewer than 5% of the healthy stratum is reported as not elicited by this stimulus and carried into any future revision of the artwork; it does not license removing the unit from the scorer, which computes the frozen model's input and cannot change.",
     "For every participant the information-unit count from the kitchen scene is computed with its per-unit indicators, and the report gives each unit's production rate with an exact binomial interval, the count of units produced by fewer than 5% of the healthy stratum — the operational definition of a unit the picture fails to elicit — and the healthy stratum's total-unit distribution against the Pittsburgh control distribution, compared as full distributions. The comparison cannot separate stimulus from population, language and era, so it is reported as a bound: comparable production means the substitution is probably not costing much; markedly lower production means the cause is unidentified and the threshold must be re-derived locally rather than inherited. A unit produced by fewer than 5% of the healthy stratum is reported as not elicited by this stimulus and carried into any future revision of the artwork; it does not license removing the unit from the scorer, which computes the frozen model's input and cannot change.")
sub1("The total number of words the participant speaks across the two connected-discourse tasks, under the fixed elicitation above, is one number counted from the transcript with no software; on Delaware it reaches AUC 0.6420 [0.5786, 0.7052] for mild impairment against control, while estimated alike the fair single-feature comparator is 0.6018, so the modelling apparatus buys about +0.036 and the hand count does not match it (section 5.16). This pilot is not powered to test it, so what is registered is descriptive: the distribution of total discourse words in healthy Libyan participants, the first such normative observation in Arabic; the impaired group's distribution beside it, with no significance test and no AUC; and the fraction of sessions in which the fixed elicitation was actually achieved. Markedly fewer words than the English reference distribution would be expected, since Arabic conveys in fewer orthographic words what English spreads across more, and would be a reason to derive the threshold from local controls, not a reason to doubt the measure.",
     "The total number of words the participant speaks across the two connected-discourse tasks, under the fixed elicitation above, is one number counted from the transcript with no software; on Delaware it reaches AUC 0.6420 [0.5786, 0.7052] for mild impairment against control, while estimated alike the fair single-feature comparator is 0.6018, so the modelling apparatus buys about +0.036 and the hand count does not match it (section 5.16). This pilot is not powered to test it, so what is registered is descriptive: the distribution of total discourse words in healthy Libyan participants, the first such normative observation in Arabic; the impaired group's distribution beside it, with no significance test and no AUC; and the fraction of sessions in which the fixed elicitation was achieved. Markedly fewer words than the English reference distribution would be expected, since Arabic conveys in fewer orthographic words what English spreads across more, and would be a reason to derive the threshold from local controls, not to doubt the measure.")
sub1("**Explicitly not an outcome.** Diagnostic accuracy, sensitivity, specificity or AUC, and any claim that the system detects impairment in Arabic. A threshold derived from the healthy stratum has a specificity known by construction, with a stated interval; it does not measure specificity, says nothing about sensitivity, and makes no accuracy claim, and the Beta interval is never reported as though it were a validation result.",
     "**Explicitly not an outcome.** Diagnostic accuracy, sensitivity, specificity or AUC, and any claim that the system detects impairment in Arabic. A threshold derived from the healthy stratum has a specificity known by construction, with a stated interval; it does not measure specificity, says nothing about sensitivity, makes no accuracy claim, and its Beta interval is never reported as a validation result.")
# B.10 — Table (B.7) becomes a sentence
sub1("Table (B.7) gives the timeline; it cannot be completed before the thesis deadline, so the protocol is submitted as a completed, ethics-ready study design constituting the principal future work of the project. A completed protocol is itself a contribution: it converts \"Arabic validation is future work\" from an aspiration into a specified, costed, ethically framed plan that another researcher could execute.",
     "The realistic timeline is one week to prepare the ethics submission, two to eight weeks of committee review outside the researcher's control, one to two weeks of clinic scheduling, three to six weeks of collection for 20 to 40 participants and one week of analysis; it cannot be completed before the thesis deadline, so the protocol is submitted as a completed, ethics-ready study design constituting the principal future work of the project. A completed protocol is itself a contribution: it converts \"Arabic validation is future work\" from an aspiration into a specified, costed, ethically framed plan that another researcher could execute.")
drop_table("**Table (B.7)")
t = t.rstrip("\n") + "\n"

open(P, "w", encoding="utf-8").write(t)
print("appendix_b words", before, "->", len(t.split()))
print("tables now:", re.findall(r"\*\*Table \((B\.\d)\)", t))
