#!/usr/bin/env python3
"""cut2_ch3.py -- tighten Chapter 3 after cut_ch3.py/cut_ch3b.py: phrasing only (whitespace-normalised matching, the
source is hard-wrapped). Every number, grade, citation and caveat kept."""
import re
P = "/home/claude/work/src/docs/chapters/chapter3.md"
t = open(P, encoding="utf-8").read()
before = len(t.split())
def ws(s): return r"\s+".join(re.escape(w) for w in s.split())
def rep(old, new):
    global t
    pat = ws(old); n = len(re.findall(pat, t))
    assert n == 1, (old[:70], n)
    t = re.sub(pat, lambda m: new, t)

# preamble
rep("A speech-based screening result is easy to produce and hard to trust, and what a reader must assess is not the number reported but the number of decisions taken with knowledge of the data the number was computed on. This work makes that quantity auditable — an external corpus locked and scored once, a pre-registration practice applied to every post-lock analysis, and a written record of the occasions on which both mechanisms failed, because a governance account that reports only successes is indistinguishable from no governance account at all.",
    "A speech-based screening result is easy to produce and hard to trust, and what a reader must assess is not the number reported but the number of decisions taken with knowledge of the data it was computed on. This work makes that quantity auditable — an external corpus locked and scored once, a pre-registration practice applied to every post-lock analysis, and a written record of the occasions on which both mechanisms failed, because a governance account that reports only successes is indistinguishable from none.")

# 3.1
rep("The exclusions matter more than the inclusions. The Wisconsin corpus contains only healthy speakers, so pooling it makes corpus membership nearly equivalent to class membership and a model can score highly by learning which archive a recording came from; this was measured and is reported in Chapter 5.",
    "The exclusions matter more than the inclusions. The Wisconsin corpus contains only healthy speakers, so pooling it makes corpus membership nearly equivalent to class membership and a model can score highly by learning which archive a recording came from, as Chapter 5 reports.")
rep("Eight further DementiaBank corpora were obtained and not used, because the design required picture description with diagnostic labels at a scale supporting cross-validated fitting, which Pittsburgh, Delaware and Lu alone meet. The Arabic pilot sits outside the development pool and evaluated the language-independent acoustic model only.",
    "Eight further DementiaBank corpora were obtained and not used, because the design required picture description with diagnostic labels at a scale supporting cross-validated fitting, which Pittsburgh, Delaware and Lu alone meet; the Arabic pilot sits outside the development pool and evaluated the language-independent acoustic model only.")

# 3.2.1
rep("The Delaware and Lu corpora settle what it is: the same convention, at different sites, occurs an order of magnitude less often and discriminates at chance, and a genuine phonetic property of impaired speech would not be ten times rarer in another cohort of impaired speakers.",
    "The Delaware and Lu corpora settle what it is: the same convention, at different sites, occurs an order of magnitude less often and discriminates at chance, and a genuine phonetic property of impaired speech would not be ten times rarer in another impaired cohort.")
rep("The application transcribes with a recogniser emitting standard orthography, so the form **cannot occur at inference** and 0.7996 is the closer estimate of what the deployed system receives. The extractor was **not corrected**: changing the features the frozen model receives would forfeit an unrepeatable external validation.",
    "The application transcribes with a recogniser emitting standard orthography, so the form **cannot occur at inference** and 0.7996 is the closer estimate of what the deployed system receives. The extractor was **not corrected**, because changing the features the frozen model receives would forfeit an unrepeatable external validation.")

# 3.6.1
rep("The pre-registered threshold for demonstrating an advantage was a gain of at least 0.02 to the ungrouped arm; it came in at −0.0025 and the registered grade is *not demonstrated*. The opportunity for leakage was overwhelmingly present and the model did not take it. The explanation is already in this work:",
    "The pre-registered threshold for demonstrating an advantage was a gain of at least 0.02 to the ungrouped arm; it came in at −0.0025 and the registered grade is *not demonstrated*: the opportunity for leakage was overwhelmingly present and the model did not take it. The explanation is already in this work:")
rep("And the null is reported prominently: this is the work testing for an advantage it expected, failing to find it, and declining to claim it.",
    "And the null is reported prominently: an advantage expected, tested for, not found, and not claimed.")

# 3.7
rep("The model output is a screening score: a development-calibrated probability estimate conditioned on the class balance of the training pool, 465 impaired recordings in 987, or 0.4711, and almost nobody is screened at a prevalence of 47%. The risk-adjustment stage therefore divides out the training prior, applies an age-specific population prevalence, a multiplier for why the person is being tested and one for family history, and returns a context-adjusted estimated risk — not a probability clinically calibrated for Libya. Section 3.12 derives the chain; Appendix H holds the evidence base for every constant, the prevalence and multiplier tables, and the property-based verification. Two parameters changed during this work, and each carries a methodological point.",
    "The model output is a screening score: a development-calibrated probability estimate conditioned on the class balance of the training pool, 465 impaired recordings in 987, or 0.4711, and almost nobody is screened at a prevalence of 47%. The risk-adjustment stage therefore divides out the training prior, applies an age-specific population prevalence, a multiplier for why the person is being tested and one for family history, and returns a context-adjusted estimated risk — not a probability clinically calibrated for Libya. Section 3.12 derives the chain; Appendix H holds the evidence base for every constant, the prevalence and multiplier tables and the property-based verification. Two parameters changed during this work, each with a methodological point.")
rep("but because **referral is not a diagnostic test and has no stable operating characteristics**: the same national audit that yields the highest of those figures found dementia yield ranging from 22% to 100% across 85 services, in one country, in one year, so a referral rate is a local policy variable, and no value calibrated on British or Dutch memory clinics would transport to a setting where referral pathways for cognitive complaint are largely absent. **A quantity can be well evidenced in direction, large in magnitude, and still not be a parameter, because it has no stable referent** [9]. A clinician-referred session now receives the same ×2.5 as a reported concern, declared as a **floor rather than an estimate**, since nearly everyone referred also reports a change and the indirect evidence says the true uplift is larger; removing an overstated figure without saying so would simply have converted it into an understated one. The referral contexts are mutually exclusive branches, one per session, and a multiplier and its baseline are a matched pair: the ×1.0 baseline presumes an unselected population, so against an age-conditioned prior the implied clinic uplift shrinks from roughly eight to roughly four to five.",
    "but because **referral is not a diagnostic test and has no stable operating characteristics**: the national audit that yields the highest of those figures found dementia yield ranging from 22% to 100% across 85 services, in one country, in one year, so a referral rate is a local policy variable, and no value calibrated on British or Dutch memory clinics would transport to a setting where referral pathways for cognitive complaint are largely absent. **A quantity can be well evidenced in direction, large in magnitude, and still not be a parameter, because it has no stable referent** [9]. A clinician-referred session now receives the same ×2.5 as a reported concern, declared as a **floor rather than an estimate**, since nearly everyone referred also reports a change and the indirect evidence says the true uplift is larger; removing an overstated figure silently would have converted it into an understated one. The referral contexts are mutually exclusive branches, one per session, and a multiplier and its baseline are a matched pair: the ×1.0 baseline presumes an unselected population, so against an age-conditioned prior the implied clinic uplift shrinks from roughly eight to roughly four to five.")
rep("That branch carries a defect which is disclosed rather than patched: the published figures are **relative risks**, the chain multiplies prior **odds**, and the two diverge once baseline risk is large, so the composition **overstates familial risk at the oldest ages**; the prior cap of 0.85 is the symptom rather than a prudence measure, binding in exactly 4 of 135 prior combinations — all two-first-degree-relative cases at ages 80 and above with a referral uplift — and Appendix H sets out the defect, its direction across the age range, the reason the arithmetic is left unpatched, and an objection to the family-history branch itself that was tested and withdrawn. The chain was verified mechanically over 1,440 cases against nine properties, **all 1,440 passing with zero failures**; the same speech score of 0.90 yields a posterior of 4.8% at age 25 and 92.5% at age 85, and a 72-year-old scoring 0.70 receives 0.316 with no context multiplier, 0.536 under the ×2.5 uplift, and would have received 0.649 under the retired ×4.0.",
    "That branch carries a defect which is disclosed rather than patched: the published figures are **relative risks**, the chain multiplies prior **odds**, and the two diverge once baseline risk is large, so the composition **overstates familial risk at the oldest ages**; the prior cap of 0.85 is the symptom rather than a prudence measure, binding in exactly 4 of 135 prior combinations — all two-first-degree-relative cases at ages 80 and above with a referral uplift — and Appendix H sets out the defect, its direction across the age range, why the arithmetic is left unpatched, and an objection to the branch itself that was tested and withdrawn. The chain was verified mechanically over 1,440 cases against nine properties, **all 1,440 passing**; the same speech score of 0.90 yields a posterior of 4.8% at age 25 and 92.5% at age 85, and a 72-year-old scoring 0.70 receives 0.316 with no context multiplier, 0.536 under the ×2.5 uplift, and would have received 0.649 under the retired ×4.0.")

# 3.9
rep("It was not caught by an internal check. An adversarial external review of the draft claims identified the contamination, and **this work's own governance did not catch it**, which is stated plainly rather than presenting the correction as foresight.",
    "An adversarial external review of the draft claims identified the contamination, and **this work's own governance did not catch it**, which is stated plainly rather than presenting the correction as foresight.")
# 3.9.1
rep("The specificity collapse is reported in full because exposing it is what a locked test set is for; its diagnosis — a threshold referenced to the wrong distribution, with a remedy analysed but not deployed — is section 5.13. Subsequently the evaluation was reproduced under a protocol permitting one execution and no decision in either direction; the AUC matched to ten decimal places and the confusion matrix cell for cell, and a tombstone file now blocks any further run.",
    "The specificity collapse is reported in full because exposing it is what a locked test set is for; its diagnosis — a threshold referenced to the wrong distribution, with a remedy analysed but not deployed — is section 5.13. The evaluation was subsequently reproduced under a protocol permitting one execution and no decision in either direction; the AUC matched to ten decimal places and the confusion matrix cell for cell, and a tombstone file now blocks any further run.")
rep("That is a fact about the *scope* of the contamination, recorded after the problem was volunteered; it is not a defence. The pooling decision was also re-examined without touching the locked corpus: the exact pre-lock comparison cannot be reproduced Lu-free, so a weaker proposition was pre-registered and tested instead — whether the two development corpora are mutually informative — and they are, in both directions (section 5.12).",
    "That is a fact about the *scope* of the contamination, recorded after the problem was volunteered; it is not a defence. The pooling decision was also re-examined without touching the locked corpus: the exact pre-lock comparison cannot be reproduced Lu-free, so a weaker proposition was pre-registered instead — whether the two development corpora are mutually informative — and they are, in both directions (section 5.12).")
# 3.9.2
rep("**Had the locked corpus been consulted, the correction would have been applied. The rule that forbade consulting it changed the decision, and changed it rightly** — a case in which the rule and the analyst's judgement diverged and the rule was correct, which is more than arguing that a rule is prudent.",
    "**Had the locked corpus been consulted, the correction would have been applied. The rule that forbade consulting it changed the decision, and changed it rightly** — a case in which the rule and the analyst's judgement diverged and the rule was correct.")

# 3.10
rep("The pattern used throughout the post-lock work is uniform: the criteria, tolerances and stop rule for a run are written into the driver script's docstring and committed **before the run**, the grading is mechanical, failure is reported rather than iterated away, and the interpretive direction is registered too — for the acoustic protocol test, failure meant *the protocol is not confirmed*, never *the model is wrong*. Two worked examples show the machinery catching a defect in a **rule** and a defect in the **analyst**.",
    "The pattern used throughout the post-lock work is uniform: the criteria, tolerances and stop rule for a run are written into the driver script's docstring and committed **before the run**, the grading is mechanical, failure is reported rather than iterated away, and the interpretive direction is registered too — for the acoustic protocol test, failure meant *the protocol is not confirmed*, never *the model is wrong*. Two worked examples show the machinery catching a defect in the **analyst** and a defect in a **rule**.")
rep("The defect was in the **new script**, not the tagger, the environment or the committed extractor (Appendix H), and fixing it **honoured** the pre-registration rather than relaxing it; one cohort's result had appeared in terminal output before the fix, and that is recorded in the driver's registration history in those words. The check that caught it was a provenance formality nobody expected to fail: the value of pre-registration is concentrated in the checks written when the author is not worried.",
    "The defect was in the **new script**, not the tagger, the environment or the committed extractor (Appendix H), and fixing it **honoured** the pre-registration rather than relaxing it; one cohort's result had appeared in terminal output before the fix, and the driver's registration history records that in those words. The check that caught it was a provenance formality nobody expected to fail: the value of pre-registration is concentrated in the checks written when the author is not worried.")
rep("**The criterion was left exactly as registered and the arm was not re-run**, because **a rule rewritten after seeing the result is the result wearing a rule's clothes**; the first criterion, that transfer exceeds chance, passed on its own terms, so the transfer finding stands and only the retention framing is void. **Neither failure was found by a reviewer; both were found by the machinery, which is the only test of whether the machinery is real.**",
    "**The criterion was left exactly as registered and the arm was not re-run**, because **a rule rewritten after seeing the result is the result wearing a rule's clothes**; the first criterion, that transfer exceeds chance, passed on its own terms, so the transfer finding stands and only the retention framing is void. **Neither failure was found by a reviewer; both were found by the machinery, which is the only test of whether the machinery is real.**")
rep("They share a shape: in none of the three was the defect in the hypothesis, the criterion band or the analysis set, the three things a registration template asks for. **A pre-registration protects the parts of a design its author already knows are contestable; it does not protect the parts they have not thought of, and in practice those are where the defects are.** The working discipline this produced is four rules, derived in Appendix H: never adjust the rule to reach the assertion; record when an amendment was made relative to seeing the result; report both versions whenever an amendment changes an answer; and register a sanity gate on every derived quantity an analysis depends on, including its labels. A fourth case extends the last rule to comparisons: a claim that a hand-countable feature matched the calibrated ensemble **reversed sign once both sides were estimated alike** (section 5.16), because one side had been selected as the best of 43 on the same participants and the other not selected at all — so the rule extends to refusing any comparison whose sides were produced by procedures with different numbers of free parameters.",
    "They share a shape: in none of the three was the defect in the hypothesis, the criterion band or the analysis set, the three things a registration template asks for. **A pre-registration protects the parts of a design its author already knows are contestable; it does not protect the parts they have not thought of, and in practice those are where the defects are.** The working discipline this produced is four rules, derived in Appendix H: never adjust the rule to reach the assertion; record when an amendment was made relative to seeing the result; report both versions whenever an amendment changes an answer; and register a sanity gate on every derived quantity an analysis depends on, including its labels. A fourth case extends the last rule to comparisons: a claim that a hand-countable feature matched the calibrated ensemble **reversed sign once both sides were estimated alike** (section 5.16), because one side had been selected as the best of 43 on the same participants and the other not selected at all — so the rule refuses any comparison whose sides were produced by procedures with different numbers of free parameters.")

# 3.11
rep("The positive half matters more. The lemma says what normative normalisation *is* good for — calibration and thresholds, which are ranking-position questions — so control-referenced thresholding, this work's principal methodological contribution, works precisely because a threshold is a calibration property rather than a discrimination property: **the lemma is not a limitation on the contribution but the reason it is correctly aimed.** It also settles the sex gap: if no monotone transform can close it, only a different feature set or model can, and under the frozen-model constraint neither is available, so the gap is reported, explained mechanistically in Chapter 5, and carried into Chapter 6 as a design requirement.",
    "The positive half matters more. The lemma says what normative normalisation *is* good for — calibration and thresholds, which are ranking-position questions — so control-referenced thresholding, this work's principal methodological contribution, works precisely because a threshold is a calibration property rather than a discrimination property: **the lemma is not a limitation on the contribution but the reason it is correctly aimed.** It also settles the sex gap: if no monotone transform can close it, only a different feature set or model can, and under the frozen-model constraint neither is available, so the gap is reported, explained mechanistically in Chapter 5, and carried into Chapter 6 as a design requirement.")

# 3.12
rep("The system converts a speech sample into a screening score, then re-applies a deployment-specific prevalence, and the chain is derived rather than merely asserted so that its prevalence-independence claim is provable.",
    "The system converts a speech sample into a screening score, then re-applies a deployment-specific prevalence, and the chain is derived so that its prevalence-independence claim is provable.")
rep("In deployment the likelihood ratio functions as an empirical evidence estimator rather than an exact density ratio: it inherits whatever miscalibration *p*(*x*) carries, and with the development calibration slope above one (section 5.4.1) it conservatively underweights extreme values, understating strong evidence rather than overstating it.",
    "In deployment the likelihood ratio is an empirical evidence estimator rather than an exact density ratio: it inherits whatever miscalibration *p*(*x*) carries, and with the development calibration slope above one (section 5.4.1) it conservatively underweights extreme values, understating strong evidence rather than overstating it.")
rep("so Pittsburgh's slope of 1.516 against Delaware's 0.823 means that *evidence strength itself is corpus-dependent and in opposite directions*, one global recalibration cannot repair two errors of opposite sign, and section 3.9.2's pre-registered decision and the mathematics reached the same conclusion independently.",
    "so Pittsburgh's slope of 1.516 against Delaware's 0.823 means that *evidence strength itself is corpus-dependent and in opposite directions*, one global recalibration cannot repair two errors of opposite sign, and section 3.9.2's pre-registered decision and the mathematics reached the same conclusion independently.")
rep("And control-referenced thresholding and the likelihood ratio are complementary rather than competing: a threshold at a fixed percentile of the local healthy-control distribution fixes the false-positive rate by construction and needs no prevalence estimate, while the likelihood ratio supplies how much evidence a given sample carries, with prevalence entering only at the final step.",
    "And control-referenced thresholding and the likelihood ratio are complementary: a threshold at a fixed percentile of the local healthy-control distribution fixes the false-positive rate by construction and needs no prevalence estimate, while the likelihood ratio supplies how much evidence a sample carries, with prevalence entering only at the final step.")

open(P, "w", encoding="utf-8").write(t)
print("chapter3 words", before, "->", len(t.split()))
