#!/usr/bin/env python3
"""cut2_ch12.py -- tighten Chapters 1 and 2 (whitespace-normalised matching): overlap between the two chapters and
between sections; every figure, citation and caveat kept."""
import re
FILES = {"c1": "/home/claude/work/src/docs/chapters/chapter1.md", "c2": "/home/claude/work/src/docs/chapters/chapter2.md"}
T = {k: open(v, encoding="utf-8").read() for k, v in FILES.items()}
B = {k: len(v.split()) for k, v in T.items()}
def ws(s): return r"\s+".join(re.escape(w) for w in s.split())
def rep(f, old, new):
    pat = ws(old); n = len(re.findall(pat, T[f]))
    assert n == 1, (f, old[:70], n)
    T[f] = re.sub(pat, lambda m: new, T[f])

# ---- Chapter 1 ----
rep("c1", "The chapters that follow argue that the second half of that sentence is where the contribution lives: what separates a screening number that can be acted on from one that cannot is not the model behind it but the evidence regime around it.",
    "The chapters that follow argue that what separates a screening number that can be acted on from one that cannot is not the model behind it but the evidence regime around it.")
rep("c1", "Among its earliest observable signs are changes in language: word-finding difficulty, thinning informational content, simplified syntax and looser reference appear in ordinary speech years before formal diagnosis, and they are measurable in language production itself rather than only in structured testing — the foundational evidence, from writing produced decades before disease, is reviewed in section 2.1. That is the premise of speech-based screening: a few minutes of ordinary speech, elicited by simple tasks and measured objectively, can carry a signal worth acting on. What screening means here is fixed at the outset, because every later claim inherits it.",
    "Among its earliest observable signs are changes in language: word-finding difficulty, thinning informational content, simplified syntax and looser reference appear in ordinary speech years before formal diagnosis, and they are measurable in language production itself rather than only in structured testing (section 2.1). That is the premise of speech-based screening: a few minutes of ordinary speech, elicited by simple tasks and measured objectively, can carry a signal worth acting on. What screening means here is fixed at the outset, because every later claim inherits it.")
rep("c1", "That absence is the problem statement, and it is stated at exactly that strength: nobody knows how common dementia is in Libya, because it has never been measured. The instruments that would measure it — validated cognitive screens, specialist assessment pathways, research corpora of Libyan speech — largely do not exist either, and the two absences feed each other: prevalence cannot be estimated without screening at scale, and screening at scale is not built for a population no instrument has been validated in. This thesis attacks the instrument half of that circle, with the tools of biomedical engineering, and is explicit throughout about which parts of the attack are validated evidence and which are prepared groundwork.",
    "That absence is the problem statement, stated at exactly that strength: nobody knows how common dementia is in Libya, because it has never been measured. The instruments that would measure it — validated cognitive screens, specialist assessment pathways, research corpora of Libyan speech — largely do not exist either, and the two absences feed each other: prevalence cannot be estimated without screening at scale, and screening at scale is not built for a population no instrument has been validated in. This thesis attacks the instrument half of that circle with the tools of biomedical engineering, and says throughout which parts of the attack are validated evidence and which are prepared groundwork.")
rep("c1", "An instrument that reads that signal, runs on hardware a Libyan clinic already owns, and explains its output in terms a family can understand is the motivating design, and the deployment constraints it must satisfy are stated next, because they are unusually strict and are not stated as modesty.",
    "An instrument that reads that signal, runs on hardware a Libyan clinic already owns, and explains its output in terms a family can understand is the motivating design; the deployment constraints it must satisfy are stated next.")
rep("c1", "The design constraints that follow are unusually severe for a diagnostic-adjacent system: no dedicated hardware, no network dependency after installation, and a paper form that reproduces the task battery when no device is available. They are not stated as modesty. Cognitive impairment",
    "The design constraints are unusually severe for a diagnostic-adjacent system — no dedicated hardware, no network dependency after installation, and a paper form that reproduces the task battery when no device is available — and they are not stated as modesty. Cognitive impairment")
rep("c1", "These objectives are reproduced as registered at the project's proposal, unchanged. Where the work exceeded an objective — the evaluation governance of Chapter 3 grew from a means into a contribution ranked first among the conclusions of section 6.1 — and where it narrowed one — the Arabic adaptation of objective 4 is delivered at the design level, with its validation specified rather than performed — the relevant chapter says so plainly, so that the distance between what was registered and what was achieved is disclosed rather than tidied away.",
    "These objectives are reproduced as registered at the project's proposal, unchanged. Where the work exceeded an objective — the evaluation governance of Chapter 3 grew from a means into a contribution ranked first in section 6.1 — and where it narrowed one — the Arabic adaptation of objective 4 is delivered at the design level, its validation specified rather than performed — the relevant chapter says so, so that the distance between what was registered and what was achieved is disclosed rather than tidied away.")
rep("c1", "Four boundaries fix the scope, and each is stated here because every later chapter inherits it. First,",
    "Four boundaries fix the scope. First,")
rep("c1", "The Arabic component is a method awaiting validation — a culturally and linguistically adapted battery, stimuli drawn for the deployment culture, and a replacement marker engineered for Arabic's grammar — prepared for Libyan validation, not validated in Libya. No Libyan data exists in this work; a validation protocol is prepared and ethics-ready (Appendix B), and the corpus its full validation requires is specified in Appendix I.",
    "The Arabic component is a method awaiting validation — a culturally and linguistically adapted battery, stimuli drawn for the deployment culture, and a replacement marker engineered for Arabic's grammar — prepared for Libyan validation, not validated in Libya; no Libyan data exists in this work, a validation protocol is prepared and ethics-ready (Appendix B), and the corpus its full validation requires is specified in Appendix I.")
# 1.6 structure, compressed
rep("c1", "Chapter 2, Literature Review, reviews the evidence that language change precedes diagnosis, the systems built on that evidence, and the corpora they are evaluated on, and makes the comparison that positions this work: the field's high published figures live in an evaluation regime never shown to transfer between corpora, and this thesis reports in the regime that has. Chapter 3, Methodology, describes the corpora, features and evaluation protocol, and then the part that carries the thesis: the external test-set governance and the failure that produced it, pre-registration as a working method including where it failed, and the derivations that fix what the results can mean. Chapter 4, System Design, describes the instrument built around the frozen model — the platform, the task battery and its stimuli, the report, and the boundaries at which the system refuses to produce anything — under the constraint that it must degrade gracefully from a screening score — a development-calibrated probability estimate — to an indicator profile to a paper checklist. Chapter 5, Results and Discussion, reports the externally evaluated model — the development and external evaluations with their confounds and calibration, the operating point and its diagnosis, fifteen negative results in one register, the measurement properties — and the probes that belong to the successor, reported under the rule of section 1.7. Chapter 6, Conclusion and Future Work, states what was learned and what it is worth, each limitation with what would remove it, the staged validation design, the Arabic contribution in its three parts, and the closing claim. The ten appendices carry the feature definitions, the pilot protocol, the model card, the reporting-guideline self-assessment, a sample report, the levels-of-evidence register, the transcription-artefact audit, the risk-adjustment evidence base, the corpus specification, and the software and reproducibility record.",
    "Chapter 2 reviews the evidence that language change precedes diagnosis, the systems built on it and the corpora they are evaluated on, and positions this work: the field's high published figures live in an evaluation regime never shown to transfer between corpora, and this thesis reports in the regime that has. Chapter 3 describes the corpora, features and evaluation protocol, then the part that carries the thesis — the external test-set governance and the failure that produced it, pre-registration as a working method including where it failed, and the derivations that fix what the results can mean. Chapter 4 describes the instrument built around the frozen model — platform, task battery and stimuli, report, and the boundaries at which the system refuses to produce anything — under the constraint that it must degrade from a screening score to an indicator profile to a paper checklist. Chapter 5 reports the externally evaluated model — development and external evaluations with their confounds and calibration, the operating point and its diagnosis, fifteen negative results in one register, the measurement properties — and then the probes that belong to the successor, under the rule of section 1.7. Chapter 6 states what was learned and what it is worth, each limitation with what would remove it, the staged validation design, the Arabic contribution in its three parts, and the closing claim. The ten appendices carry the feature definitions, the pilot protocol, the model card, the reporting-guideline self-assessment, a sample report, the levels-of-evidence register, the transcription-artefact audit, the risk-adjustment evidence base, the corpus specification, and the software and reproducibility record.")
# 1.7
rep("c1", "This thesis contains two kinds of number, and they are not comparable. The distinction is not deployed versus experimental — that describes how code is used, which is not the property that matters. The property that matters is external validation, and in this project it is scarce in a specific and permanent way. Validated:",
    "This thesis contains two kinds of number, and they are not comparable. The distinction is not deployed versus experimental, which describes how code is used; it is external validation, which in this project is scarce in a specific and permanent way. Validated:")
rep("c1", "That evaluation cannot be repeated: the corpus is spent, and repeating it would destroy the property that makes it worth having. Specified: every other configuration measured in this project — the task-genre findings, the transfer ablations, the acoustic path, the threshold rule, the Arabic instrument. Each has development-set evidence, and none has external validation, nor can any of them ever obtain it, because the corpus that would provide it has been spent.",
    "That evaluation cannot be repeated: the corpus is spent, and repeating it would destroy the property that makes it worth having. Specified: every other configuration measured in this project — the task-genre findings, the transfer ablations, the acoustic path, the threshold rule, the Arabic instrument — each with development-set evidence and none with external validation, nor able ever to obtain it, because the corpus that would provide it has been spent.")
rep("c1", "Chapter 5 reports the externally evaluated model first and the specified successor last, under its own heading, and Chapter 6 says which is which. The structure is deliberate: a specified configuration that outperforms the evaluated one is the proper output of a future-work section, not an embarrassment. One rule enforces the distinction mechanically, and it is never broken.",
    "Chapter 5 reports the externally evaluated model first and the specified successor last, under its own heading, and Chapter 6 says which is which: a specified configuration that outperforms the evaluated one is the proper output of a future-work section, not an embarrassment. One rule enforces the distinction mechanically, and it is never broken.")
rep("c1", "The moment the two share a table, the reader must hold the distinction themselves — and by the account of this field's own review literature, readers do not, which is part of how a decade of reported performance above ninety per cent coexists with no tool in clinical use (section 2.3).",
    "The moment the two share a table, the reader must hold the distinction themselves — and by the account of this field's own review literature, readers do not, which is part of how a decade of reported performance above ninety per cent coexists with no tool in clinical use (section 2.3).")

# ---- Chapter 2 ----
rep("c2", "Together these establish the premise every system in this chapter rests on: the linguistic signal is real, it precedes clinical presentation by years, and it is measurable in ordinary language production rather than only in formal testing. What they do not establish is that the signal can be read reliably in one short sample from one unknown speaker, which is the screening problem, and the distance between those two claims is much of what this thesis measures.",
    "Together these establish the premise every system in this chapter rests on: the linguistic signal is real, precedes clinical presentation by years, and is measurable in ordinary language production. What they do not establish is that the signal can be read reliably in one short sample from one unknown speaker, which is the screening problem, and the distance between those two claims is much of what this thesis measures.")
rep("c2", "This project's use of the first three is described in section 3.1; Wisconsin was excluded, and the exclusion has a published counter-case that deserves discussion rather than silence.",
    "This project's use of the first three is described in section 3.1; Wisconsin was excluded, and the exclusion has a published counter-case.")
rep("c2", "Whether external normative data helps a given model depends on whether its features can encode corpus identity and on whether the added corpus carries both classes; this project measured that for its own configuration, obtained a clear negative, did not pool, and proposes the measurement as a routine pre-pooling check (section 6.1).",
    "Whether external normative data helps a given model depends on whether its features can encode corpus identity and whether the added corpus carries both classes; this project measured that for its own configuration, obtained a clear negative, did not pool, and proposes the measurement as a routine pre-pooling check (section 6.1).")
rep("c2", "No comparison table in this field is neutral, so the terms of this one are stated before the numbers. The obvious argument for this project — that ungrouped cross-validation folds inflate published results by letting one participant's recordings appear in both training and test — is deliberately not made, because this project tested it on its own model and found nothing: grouped and ungrouped folds differed by −0.0025 despite 68.4% of ungrouped test recordings sharing a participant with training (section 3.6.1). Capacity is the uncontrolled variable — a tree ensemble over 64 aggregate features has far less ability to memorise a speaker than a transformer over raw text — so the null says nothing about other architectures, and this thesis has no evidence for the inflation claim and does not make it. What this project can demonstrate is the feature-level version of the same hazard, on its own data: an age-residualisation technique scored 0.853 on development until age proved recoverable from the supposedly age-free features at R² = 0.994, and the technique was discarded (section 5.8) — a measured demonstration of what an evaluation shortcut can buy, and the reason the comparison below rests on the column no shortcut can counterfeit. Most of this literature reports no external validation at all, and that difference, not any claim of error against any author, is the argument: the numbers answer different questions [8].",
    "No comparison table in this field is neutral, so the terms of this one are stated before the numbers. The obvious argument for this project — that ungrouped cross-validation folds inflate published results by letting one participant's recordings appear in both training and test — is deliberately not made, because this project tested it on its own model and found nothing: grouped and ungrouped folds differed by −0.0025 despite 68.4% of ungrouped test recordings sharing a participant with training (section 3.6.1). Capacity is the uncontrolled variable — a tree ensemble over 64 aggregate features has far less ability to memorise a speaker than a transformer over raw text — so the null says nothing about other architectures, and the inflation claim is not made. What this project can demonstrate is the feature-level version of the same hazard, on its own data: an age-residualisation technique scored 0.853 on development until age proved recoverable from the supposedly age-free features at R² = 0.994, and the technique was discarded (section 5.8) — a measured demonstration of what an evaluation shortcut can buy, and the reason the comparison below rests on the column no shortcut can counterfeit. Most of this literature reports no external validation at all, and that difference, not any claim of error against any author, is the argument [8].")
rep("c2", "The anticipated reply is also conceded in advance. A contextual transformer would very likely beat this feature set by several points under any fold protocol; nothing below disputes it. The choice was still right for this project's setting, for three reasons:",
    "The anticipated reply is conceded in advance: a contextual transformer would very likely beat this feature set by several points under any fold protocol. The choice was still right for this project's setting, for three reasons:")
rep("c2", "The cost is measured: the whole modelling apparatus buys about 4.5 points of AUC over a single hand-countable feature (section 5.1.1), and the modelling is modest and real, not state of the art.",
    "The cost is measured: the whole modelling apparatus buys about 4.5 points of AUC over a single hand-countable feature (section 5.1.1); the modelling is modest and real, not state of the art.")
rep("c2", "Read fairly, the table places this work without flattery. Among subject-independent results the published range runs roughly 0.75 to 0.87 accuracy, and the best comparable figure on extended Pittsburgh material located by this review is 0.797, obtained with 1,476 features [10]; at 0.759 this project sits at the challenge baseline and about four accuracy points below that figure — a real gap, and a small one, not the fifteen points the 0.93 headline suggests, because that headline was produced under a protocol that is not subject-independent and was never tested outside its corpus [9]. One line in the table belongs to this work alone: no system in the table reports an external validation of any kind, and on the locked external corpus the best accuracy any threshold could achieve is 0.792, collected by different investigators in a different setting and scored exactly once at a threshold fixed in advance. Figures above 0.90 are reached only by protocols that are not subject-independent, or by transformers, or both, and 0.93 is not the bar because it is not measuring the same thing.",
    "Read fairly, the table places this work without flattery. Among subject-independent results the published range runs roughly 0.75 to 0.87 accuracy, and the best comparable figure on extended Pittsburgh material located by this review is 0.797, obtained with 1,476 features [10]; at 0.759 this project sits at the challenge baseline and about four accuracy points below that figure — a real gap, and a small one, not the fifteen points the 0.93 headline suggests, because that headline was produced under a protocol that is not subject-independent and was never tested outside its corpus [9]. One line in the table belongs to this work alone: no system in it reports an external validation of any kind, and on the locked external corpus the best accuracy any threshold could achieve is 0.792, collected by different investigators in a different setting and scored exactly once at a threshold fixed in advance. Figures above 0.90 are reached only by protocols that are not subject-independent, or by transformers, or both; 0.93 is not the bar because it is not measuring the same thing.")
rep("c2", "The field's own review literature says the structural version of this out loud, and it is quoted because the review says it on the field's behalf [4]:",
    "The field's own review literature says the structural version of this out loud [4]:")
rep("c2", "A field at ninety per cent accuracy with zero deployments is precisely the gap between a reported number and a trustworthy one, and it is the gap this thesis's evaluation regime exists to close.",
    "A field at ninety per cent accuracy with zero deployments is the gap between a reported number and a trustworthy one, and the gap this thesis's evaluation regime exists to close.")
rep("c2", "Both are reported, in that order and with that framing: 0.8095 on the comparable task, and 0.7550 on a harder pooled task the literature does not attempt, which is the population a screening instrument actually meets.",
    "Both are reported, in that order: 0.8095 on the comparable task, and 0.7550 on a harder pooled task the literature does not attempt, which is the population a screening instrument actually meets.")
rep("c2", "One obvious benchmark is deliberately absent from the table, and the reason is stated rather than left to be inferred. ADReSS is curated from the Pittsburgh corpus,",
    "One obvious benchmark is deliberately absent from the table. ADReSS is curated from the Pittsburgh corpus,")
rep("c2", "The evaluation was considered and rejected on those grounds [7, 11]. The legitimate variant is specified for whoever continues this work: retrain on Pittsburgh minus the ADReSS test participants and evaluate on the ADReSS test set, as a reported experiment that never touches the deployed model — the cheapest route to true comparability that exists.",
    "The evaluation was considered and rejected on those grounds [7, 11]. The legitimate variant is specified for whoever continues this work: retrain on Pittsburgh minus the ADReSS test participants and evaluate on the ADReSS test set, as a reported experiment that never touches the deployed model — the cheapest route to true comparability.")
rep("c2", "What this licenses is stated exactly, because it is the sentence an examiner should test. It does not license the claim that Dhikra is more accurate than the models reporting 0.93 or 0.95 — that comparison is not available in either direction, and this thesis does not imply it. It licenses the claim that Dhikra's number was obtained under an evaluation condition the higher published numbers have not been tested under, and that when others tested that condition, performance collapsed. That is a claim about evidence, not about superiority.",
    "What this licenses is stated exactly. It does not license the claim that Dhikra is more accurate than the models reporting 0.93 or 0.95 — that comparison is not available in either direction, and this thesis does not imply it. It licenses the claim that Dhikra's number was obtained under an evaluation condition the higher published numbers have not been tested under, and that when others tested that condition, performance collapsed: a claim about evidence, not about superiority.")
rep("c2", "The nearest prior work is small enough to review in full, and none of it occupies this project's position. The closest is",
    "The nearest prior work is small enough to review in full, and none of it occupies this project's position. The closest is")
rep("c2", "This project is that parallel line — free connected speech into engineered features into a classifier — and their instrument-scoring line and this one are complements, not competitors [13].",
    "This project is that parallel line — free connected speech into engineered features into a classifier — and the two lines are complements, not competitors [13].")

for k, v in FILES.items():
    open(v, "w", encoding="utf-8").write(T[k]); print(k, "words", B[k], "->", len(T[k].split()))
