#!/usr/bin/env python3
"""cut2_flips2.py -- second flip pass: Chapter 2 (after Table 2.1), Chapter 3 (after Table 3.4), Chapter 4, Appendix B
(after Table B.5). Whitespace-normalised matching; every number, citation and caveat kept."""
import re
ROOT = "/home/claude/work/src/docs/chapters/"
FILES = {"c2": ROOT + "chapter2.md", "c3": ROOT + "chapter3.md", "c4": ROOT + "chapter4.md", "B": ROOT + "_pending/appendix_b.md"}
T = {k: open(v, encoding="utf-8").read() for k, v in FILES.items()}
Bw = {k: len(v.split()) for k, v in T.items()}
def ws(s): return r"\s+".join(re.escape(w) for w in s.split())
def rep(f, old, new):
    pat = ws(old); n = len(re.findall(pat, T[f]))
    assert n == 1, (f, old[:70], n)
    T[f] = re.sub(pat, lambda m: new, T[f])

# ---- Chapter 2 ----
rep("c2", "Read fairly, the table places this work without flattery. Among subject-independent results the published range runs roughly 0.75 to 0.87 accuracy, and the best comparable figure on extended Pittsburgh material located by this review is 0.797, obtained with 1,476 features [10]; at 0.759 this project sits at the challenge baseline and about four accuracy points below that figure — a real gap, and a small one, not the fifteen points the 0.93 headline suggests, because that headline was produced under a protocol that is not subject-independent and was never tested outside its corpus [9].",
    "Read fairly, the table places this work without flattery. Among subject-independent results the published range runs roughly 0.75 to 0.87 accuracy, and the best comparable figure on extended Pittsburgh material located by this review is 0.797, with 1,476 features [10]; at 0.759 this project sits at the challenge baseline and about four accuracy points below that figure — a real gap, and a small one, not the fifteen points the 0.93 headline suggests, since that headline was produced under a protocol that is not subject-independent and never tested outside its corpus [9].")
rep("c2", "Published Pittsburgh work measures dementia against control on a single corpus. The comparable figure from this project is therefore 0.8095 [0.7612, 0.8552] — the Pittsburgh subset — not the combined 0.7550 [0.7192, 0.7902], which additionally contains 439 mild-impairment recordings from a materially harder target that essentially nothing in Table (2.1) attempts. Both are reported, in that order: 0.8095 on the comparable task, and 0.7550 on a harder pooled task the literature does not attempt, which is the population a screening instrument actually meets.",
    "Published Pittsburgh work measures dementia against control on a single corpus, so the comparable figure from this project is 0.8095 [0.7612, 0.8552] — the Pittsburgh subset — not the combined 0.7550 [0.7192, 0.7902], which additionally contains 439 mild-impairment recordings from a materially harder target that essentially nothing in Table (2.1) attempts. Both are reported, in that order: 0.8095 on the comparable task, 0.7550 on the harder pooled task, which is the population a screening instrument actually meets.")
rep("c2", "ADReSS is curated from the Pittsburgh corpus, and this project's deployed model trains on all 548 Pittsburgh cookie recordings, so the ADReSS test participants are inside this model's training data: any figure produced by evaluating on ADReSS would be training performance wearing a benchmark's name. The evaluation was considered and rejected on those grounds [7, 11]. The legitimate variant is specified for whoever continues this work: retrain on Pittsburgh minus the ADReSS test participants and evaluate on the ADReSS test set, as a reported experiment that never touches the deployed model — the cheapest route to true comparability.",
    "ADReSS is curated from the Pittsburgh corpus, and this project's deployed model trains on all 548 Pittsburgh cookie recordings, so the ADReSS test participants are inside this model's training data and any figure produced by evaluating on ADReSS would be training performance wearing a benchmark's name; the evaluation was considered and rejected on those grounds [7, 11]. The legitimate variant is specified for whoever continues this work: retrain on Pittsburgh minus the ADReSS test participants and evaluate on the ADReSS test set, as a reported experiment that never touches the deployed model.")
rep("c2", "Dhikra's headline result is a cross-corpus result. Trained on Pittsburgh and Delaware and scored once on Lu — different speakers, different recording conditions, different clinical ascertainment, a different country — the frozen English screening model reached AUC 0.8533 [0.7371, 0.9458], under the governance and exposure history of section 3.9.",
    "Dhikra's headline result is a cross-corpus result: trained on Pittsburgh and Delaware and scored once on Lu — different speakers, recording conditions, clinical ascertainment and country — the frozen English screening model reached AUC 0.8533 [0.7371, 0.9458], under the governance and exposure history of section 3.9.")
rep("c2", "The features of this literature sort into three tiers by what a positive finding means. Clinically motivated measures — information units, idea density, lexical diversity, syntactic complexity, reference and cohesion — connect a classifier's behaviour to constructs the clinical literature already interprets, and they are the tier this project deploys (section 3.3). Standard clinical voice measures — fundamental frequency, jitter and shimmer, pause and timing statistics — are established and language-independent but require usable audio, which is why this project implements them in a separate acoustic model that never enters the deployed screening score. Convention features — MFCCs and their derivatives, and learned embeddings — carry discriminative power with little interpretive content; this project excludes them from deployment on interpretability and hardware grounds and reports the measured cost of that exclusion (section 5.1.2) [3, 4].",
    "The features of this literature sort into three tiers by what a positive finding means: clinically motivated measures — information units, idea density, lexical diversity, syntactic complexity, reference and cohesion — which connect a classifier's behaviour to constructs the clinical literature already interprets and are the tier this project deploys (section 3.3); standard clinical voice measures — fundamental frequency, jitter and shimmer, pause and timing statistics — established and language-independent but requiring usable audio, which is why this project implements them in a separate acoustic model that never enters the deployed screening score; and convention features — MFCCs and their derivatives, and learned embeddings — which carry discriminative power with little interpretive content and are excluded from deployment on interpretability and hardware grounds, at a measured cost (section 5.1.2) [3, 4].")
rep("c2", "The systematic review of cognitive assessment for Arabic speakers — 154 studies to late 2023 — found the validated instruments to be structured batteries and questionnaires throughout: 29 validation studies covering 20 tools, concentrated in Lebanon and Egypt, with no connected-speech instrument among them, and with screening tools performing poorly for mild impairment in Arabic speakers, the MoCA excepted [16].",
    "The systematic review of cognitive assessment for Arabic speakers — 154 studies to late 2023 — found only structured batteries and questionnaires among the validated instruments: 29 validation studies covering 20 tools, concentrated in Lebanon and Egypt, no connected-speech instrument, and screening tools performing poorly for mild impairment in Arabic speakers, the MoCA excepted [16].")
rep("c2", "the language this project serves has no corpus on which even the field's ordinary regime could be run, and the thesis therefore contributes, alongside its validated English instrument, the documented absence and the specification that would close it (sections 6.4 and 6.5). The methodology for the first argument is Chapter 3; the system built under it is Chapter 4; what was measured is Chapter 5; and what should be built next is Chapter 6.",
    "the language this project serves has no corpus on which even the field's ordinary regime could be run, and the thesis therefore contributes, alongside its externally evaluated English screening model, the documented absence and the specification that would close it (sections 6.4 and 6.5).")
rep("c2", "The nearest prior work is small enough to review in full, and none of it occupies this project's position. The closest is Rabaya, Qarariya, Abualhaija, Salah and Ashqar, who automate the scoring of the Montreal Cognitive Assessment for Arabic speakers from recorded administrations — 24 participants, with 83.3% agreement against clinician scoring — and whose public dataset supplied this project's acoustic feasibility pilot (section 5.10).",
    "The nearest prior work is small enough to review in full, and none of it occupies this project's position. The closest is Rabaya, Qarariya, Abualhaija, Salah and Ashqar, who automate the scoring of the Montreal Cognitive Assessment for Arabic speakers from recorded administrations — 24 participants, 83.3% agreement against clinician scoring — and whose public dataset supplied this project's acoustic feasibility pilot (section 5.10).")

# ---- Chapter 3 (after Table 3.4) ----
rep("c3", "The two sit 0.032 apart on the same 53 recordings, and 0.821 falls inside the confidence interval of 0.8533; that proximity **bounds** how large the selection effect can be, though the gap mixes selection with the genuine benefit of more training data and so bounds their sum. **One architectural decision** — which corpora entered the training pool — was made with knowledge of a score from the external corpus, and nothing else was: no hyperparameter, no operating threshold, no feature selection, no calibration method, no model form.",
    "The two sit 0.032 apart on the same 53 recordings, and 0.821 falls inside the confidence interval of 0.8533; that proximity **bounds** how large the selection effect can be, though the gap mixes selection with the genuine benefit of more training data and so bounds their sum. **One architectural decision** — which corpora entered the training pool — was made with knowledge of a score from the external corpus, and nothing else was: no hyperparameter, threshold, feature selection, calibration method or model form.")
rep("c3", "The rule was then tested by the project's own work, and section 5.4.1 reports the case in full. A calibration defect was found, the standard correction was derived — Cox logistic recalibration, two coefficients, no tuning, strictly monotone and therefore incapable of disturbing any locked result — and a transfer test was pre-registered on the development cohorts; it failed, because **the two development cohorts are miscalibrated in opposite directions**. The obvious test was the locked corpus, and the registration had declared before execution that the corpus would be scored descriptively afterwards and **would not enter the decision whatever it showed**. On that corpus the correction passed both criteria the development arms had failed.",
    "The rule was then tested by the project's own work, reported in full in section 5.4.1. A calibration defect was found, the standard correction was derived — Cox logistic recalibration, two coefficients, no tuning, strictly monotone and therefore incapable of disturbing any locked result — and a transfer test was pre-registered on the development cohorts; it failed, because **the two development cohorts are miscalibrated in opposite directions**. The obvious test was the locked corpus, and the registration had declared before execution that the corpus would be scored descriptively afterwards and **would not enter the decision whatever it showed**; on that corpus the correction passed both criteria the development arms had failed.")
rep("c3", "**A pre-registered check caught the analyst's own bug.** The probe of the referential deficit index registered a provenance check with nothing to do with the hypothesis — the recomputed pronoun-to-noun ratio must reproduce the committed feature to within one part in a million on at least 99% of recordings, failing which the run is void — and **it failed**, reproducing the committed feature on 36% of Pittsburgh and 82% of Delaware recordings.",
    "**A pre-registered check caught the analyst's own bug.** The probe of the referential deficit index registered a provenance check with nothing to do with the hypothesis — the recomputed pronoun-to-noun ratio must reproduce the committed feature to within one part in a million on at least 99% of recordings, failing which the run is void — and **it failed**, reproducing the committed feature on 36% of Pittsburgh and 82% of Delaware recordings.")
rep("c3", "**A criterion that failed on contact with the data.** The cross-corpus transfer analysis registered a retention ratio — transfer AUC over the within-corpus reference of the test corpus — which silently assumes its denominator is a working reference, and in one direction it is not: Delaware trained on itself scores 0.5474, an interval spanning chance (section 5.12.1), so the ratio came out at 1.18 and the registered rule stamped it **strong**, a meaningless verdict.",
    "**A criterion that failed on contact with the data.** The cross-corpus transfer analysis registered a retention ratio — transfer AUC over the within-corpus reference of the test corpus — which silently assumes its denominator is a working reference, and in one direction it is not: Delaware trained on itself scores 0.5474, an interval spanning chance (section 5.12.1), so the ratio came out at 1.18 and the registered rule stamped it **strong**, a meaningless verdict.")
rep("c3", "Three registrations in seventeen runs required amendment on contact with the data — the retention criterion above, the tokenisation of the referential-index probe, and the label rule of the task-count curve, where 6.25% of participants change label across visits — and Appendix H tabulates each with its timing relative to seeing the result. They share a shape: in none of the three was the defect in the hypothesis, the criterion band or the analysis set, the three things a registration template asks for.",
    "Three registrations in seventeen runs required amendment on contact with the data — the retention criterion above, the tokenisation of the referential-index probe, and the label rule of the task-count curve, where 6.25% of participants change label across visits — and Appendix H tabulates each with its timing relative to seeing the result. In none of the three was the defect in the hypothesis, the criterion band or the analysis set, the three things a registration template asks for.")
rep("c3", "**The lemma.** The area under the receiver-operating-characteristic curve is a function only of the *ranking* a score induces within the population being ranked, so any strictly monotone transform applied uniformly to a group leaves every within-group ranking, and therefore every within-group AUC, exactly unchanged. Discrimination is a property of how far two distributions overlap; recentring and rescaling move both distributions together.",
    "**The lemma.** The area under the receiver-operating-characteristic curve is a function only of the *ranking* a score induces within the population being ranked, so any strictly monotone transform applied uniformly to a group leaves every within-group ranking, and therefore every within-group AUC, exactly unchanged: recentring and rescaling move both distributions together.")
rep("c3", "Three corollaries follow. Cox logistic recalibration is strictly monotone, so it was never a candidate for improving separation, only for repairing probability estimates. Sex-stratified thresholding cannot close a sex gap in discrimination: it equalised specificity at 0.799 against 0.798 and *widened* the sensitivity gap from 0.176 to 0.348, because moving a threshold within a group redistributes errors rather than reducing them. And normative normalisation against local healthy controls cannot close it either: z-scoring the information-unit total within sex leaves the within-sex AUCs identical to four decimal places, moving only the pooled figure, and moving it *down* by 0.0015.",
    "Three corollaries follow. Cox logistic recalibration is strictly monotone, so it was never a candidate for improving separation, only for repairing probability estimates. Sex-stratified thresholding cannot close a sex gap in discrimination: it equalised specificity at 0.799 against 0.798 and *widened* the sensitivity gap from 0.176 to 0.348, because moving a threshold within a group redistributes errors rather than reducing them. And normative normalisation against local healthy controls cannot close it either: z-scoring the information-unit total within sex leaves the within-sex AUCs identical to four decimal places and moves only the pooled figure, *down* by 0.0015.")
rep("c3", "By construction this equals the ratio of the class-conditional densities, *f*₁(*x*) / *f*₀(*x*) — the **density ratio** between how impaired and healthy speakers distribute over the feature space — and deployment applies the local prior, so the posterior odds are LR(*x*) × *π* / (1 − *π*). **Prevalence independence becomes a theorem:** neither class-conditional density is a function of *π*, so LR(*x*) is invariant to prevalence, and every prevalence-dependent quantity — predictive values, the posterior bands — is an invariant evidence term multiplied by a local prior.",
    "By construction this equals the ratio of the class-conditional densities, *f*₁(*x*) / *f*₀(*x*) — the **density ratio** between how impaired and healthy speakers distribute over the feature space — and deployment applies the local prior, so the posterior odds are LR(*x*) × *π* / (1 − *π*). **Prevalence independence becomes a theorem:** neither class-conditional density is a function of *π*, so LR(*x*) is invariant to prevalence, and every prevalence-dependent quantity — predictive values, the posterior bands — is an invariant evidence term multiplied by a local prior.")
rep("c3", "**The multipliers are separate likelihood ratios**, and multiplying likelihood ratios is exactly correct provided the sources are conditionally independent given class; that proviso was tested where it is most at risk — age is recoverable from the deployed features at *R*² = 0.994 — and measured on the 987 development recordings the model's evidence is approximately age-flat within each class, with a residual drift of a factor of 0.87 across a twenty-year span that runs the wrong way for double-counting (Appendix H): **the information being present is not the same as the information being used**, and the age prior may be applied on top of the model's likelihood ratio.",
    "**The multipliers are separate likelihood ratios**, and multiplying likelihood ratios is exactly correct provided the sources are conditionally independent given class; that proviso was tested where it is most at risk — age is recoverable from the deployed features at *R*² = 0.994 — and on the 987 development recordings the model's evidence is approximately age-flat within each class, with a residual drift of a factor of 0.87 across a twenty-year span that runs the wrong way for double-counting (Appendix H): **the information being present is not the same as the information being used**, and the age prior may be applied on top of the model's likelihood ratio.")
rep("c3", "**The operating point is set by the control distribution; the reported risk is set by the likelihood ratio and the local prior. Two mechanisms, two jobs, no overlap.**",
    "**The operating point is set by the control distribution; the reported risk by the likelihood ratio and the local prior. Two mechanisms, two jobs, no overlap.**")

# ---- Chapter 4 ----
rep("c4", "The platform is not operated by the elderly person alone. A family member, nurse or health worker opens the application, enters age, sex, education and the referral context, and hands the device over; the participant simply talks, and a complete session takes about six minutes. The battery, specified in section 3.5 and reordered on the evidence of section 5.15, is administered in the order of Table (4.1): connected discourse first, because it is the stronger genre for the mild-impairment target; picture description retained unchanged, because it alone has an externally validated model behind it; then verbal fluency and, in Arabic sessions, Qur'anic recitation from a twelve-surah bank restricted to what the participant is known to have memorised.",
    "The platform is not operated by the elderly person alone: a family member, nurse or health worker opens the application, enters age, sex, education and the referral context, and hands the device over; the participant simply talks, and a complete session takes about six minutes. The battery, specified in section 3.5 and reordered on the evidence of section 5.15, is administered in the order of Table (4.1): connected discourse first, the stronger genre for the mild-impairment target; picture description retained unchanged, because it alone has an externally validated model behind it; then verbal fluency and, in Arabic sessions, Qur'anic recitation from a twelve-surah bank restricted to what the participant is known to have memorised.")
rep("c4", "Procedural discourse alone entered on this project's own measurement (section 5.15); its prompt asks for tea-making rather than the source corpus's sandwich because tea-making is culturally universal in the deployment setting.",
    "Procedural discourse alone entered on this project's own measurement (section 5.15); its prompt asks for tea-making rather than the source corpus's sandwich because tea-making is universal in the deployment setting.")
rep("c4", "Fluency and story recall are shown to the operator as clinical context and excluded from the screening decision, because the training corpus contains them for the dementia group only.",
    "Fluency and story recall are shown to the operator as context and excluded from the screening decision, because the training corpus contains them for the dementia group only.")
rep("c4", "The settings, dress and objects are Libyan rather than mid-century American, which the standard picture is: a participant who has never seen a cookie jar on a high shelf faces a harder task for reasons that have nothing to do with cognition [7].",
    "The settings, dress and objects are Libyan rather than mid-century American: a participant who has never seen a cookie jar on a high shelf faces a harder task for reasons that have nothing to do with cognition [7].")
rep("c4", "Rendering the artwork and reading the key unit by unit showed that two of the 23 — the curtain and the dishcloth — were not depicted at all, and three more — the tap, the running water and the overflow — were occluded by the standing figure; both faults were in the artwork, both were corrected, and no participant data existed to be invalidated. Every figure in Chapters 3 and 5 was computed on transcripts of the real Cookie Theft and is unaffected.",
    "Rendering the artwork and reading the key unit by unit showed that two of the 23 — the curtain and the dishcloth — were not depicted at all, and three more — the tap, the running water and the overflow — were occluded by the standing figure; both faults were in the artwork, both were corrected, and no participant data existed to be invalidated. Every figure in Chapters 3 and 5 was computed on transcripts of the real Cookie Theft and is unaffected.")
rep("c4", "The size of the omission was then measured — pre-registered, on the 548 Pittsburgh development recordings, perturbing only the inputs of the frozen model. Making the two absent units unearnable moves the mean probability by +0.0064, leaves sensitivity unchanged at 0.9869, and costs 2.88 percentage points of specificity (0.7119 to 0.6831), carrying seven recordings across the threshold. The registered grade is PRE-EDIT-DEFECT-CONTAINED, and it was contained for a checkable reason: the two units are rare even on the real picture, produced in 24.6% and 5.7% of recordings respectively (`results/stimulus_inventory_probe.json`).",
    "The size of the omission was then measured — pre-registered, on the 548 Pittsburgh development recordings, perturbing only the inputs of the frozen model. Making the two absent units unearnable moves the mean probability by +0.0064, leaves sensitivity unchanged at 0.9869, and costs 2.88 percentage points of specificity (0.7119 to 0.6831), carrying seven recordings across the threshold: grade PRE-EDIT-DEFECT-CONTAINED, for a checkable reason — the two units are rare even on the real picture, produced in 24.6% and 5.7% of recordings (`results/stimulus_inventory_probe.json`).")
rep("c4", "What cannot be corrected is the other half. The scene contains salient content with no slot in the key — a cat, a teapot, a stove, bread, a table, a palm tree — and the key cannot be extended to credit them, because the key computes the model's input and the model is frozen.",
    "What cannot be corrected is the other half: the scene contains salient content with no slot in the key — a cat, a teapot, a stove, bread, a table, a palm tree — and the key cannot be extended to credit them, because the key computes the model's input and the model is frozen.")
rep("c4", "What the operator receives is designed around the instrument's measured limits. The screening result is a band with the screening score behind it, and an indicator profile in plain language — each measured family against reference ranges estimated from the training controls, so a family member can see what was unusual rather than only that something was.",
    "What the operator receives is designed around the instrument's measured limits: a screening band with the screening score behind it, and an indicator profile in plain language — each measured family against reference ranges estimated from the training controls, so a family member can see what was unusual rather than only that something was.")
rep("c4", "The recitation probe is scored against the surah actually recited rather than the one assigned — a participant who launches into a better-known passage would otherwise be scored as impaired for an administration slip — and where both recall and recitation exist the report contrasts new learning with overlearned memory.",
    "The recitation probe is scored against the surah actually recited rather than the one assigned — a participant who launches into a better-known passage would otherwise be scored as impaired for an administration slip — and where both exist the report contrasts new learning with overlearned memory.")
rep("c4", "The system refuses to produce a result in four situations, each enforced in code rather than requested in documentation: a recording that fails the quality gate of Table (4.3); an Arabic session, for which no validated screening score exists — the indicator profile is computed by the Arabic engine, and no English reference range is ever applied to Arabic speech; a picture other than the calibrated kitchen scene, for which the trained model's screening score is withheld while the indicator profile stands; and any use outside the declared scope of the model card.",
    "The system refuses to produce a result in four situations, each enforced in code: a recording that fails the quality gate of Table (4.3); an Arabic session, for which no validated screening score exists — the indicator profile is computed by the Arabic engine, and no English reference range is ever applied to Arabic speech; a picture other than the calibrated kitchen scene, for which the screening score is withheld while the indicator profile stands; and any use outside the declared scope of the model card.")
rep("c4", "The split in the basis column is deliberate: the noise thresholds and clipping tolerance derive from the degradation experiment of section 5.9, so the gate polices noise strictly and everything else loosely, the opposite of a generic audio check, while the three minima were asserted and the pilot's feasibility outcomes are the place to revisit them.",
    "The split in the basis column is deliberate: the noise thresholds and clipping tolerance derive from the degradation experiment of section 5.9, so the gate polices noise strictly and everything else loosely, while the three minima were asserted and the pilot's feasibility outcomes are the place to revisit them.")
rep("c4", "A third caveat names any score lying within one standard error of measurement of the threshold as sitting in the least stable region of the instrument, quoting the measured decision reproducibility of section 5.14. None of the three alters a score; each states what the score is.",
    "A third caveat names any score within one standard error of measurement of the threshold as sitting in the least stable region of the instrument, quoting the measured decision reproducibility of section 5.14. None of the three alters a score; each states what the score is.")

# ---- Appendix B (after Table B.5) ----
rep("B", "**The scoring rule.** The automated information-unit scorer was graded INADEQUATE against a human on 20 transcripts, a near-constant undercount of about 1.5 units with rank order preserved (section 5.5.1). Every scorer is therefore trained against the committed coding rules (`docs/scorer_check/CODING_RULES.md`) before collection begins, a subsample of at least ten sessions is double-scored by a second person, and because a hand count arrives at roughly 1.5 more units than the software for the same speech, the paper instrument takes its cut-off from hand-scored local controls and never from the software's.",
    "**The scoring rule.** The automated information-unit scorer was graded INADEQUATE against a human on 20 transcripts, a near-constant undercount of about 1.5 units with rank order preserved (section 5.5.1), so every scorer is trained against the committed coding rules (`docs/scorer_check/CODING_RULES.md`) before collection begins, a subsample of at least ten sessions is double-scored by a second person, and the paper instrument takes its cut-off from hand-scored local controls and never from the software's.")
rep("B", "**Stimulus equivalence, a pre-registered secondary outcome.** The screening score was calibrated on descriptions of the Cookie Theft picture, which the system does not show, and one displaced information unit crosses 13.1% of control recordings over the threshold (section 4.3.1); this pilot is the first opportunity to measure the substitution on real speakers.",
    "**Stimulus equivalence, a pre-registered secondary outcome.** The screening score was calibrated on descriptions of the Cookie Theft picture, which the system does not show, and one displaced information unit crosses 13.1% of control recordings over the threshold (section 4.3.1); this pilot is the first opportunity to measure the substitution on real speakers.")
rep("B", "**The minimal probe, a pre-registered secondary outcome.** The total number of words the participant speaks across the two connected-discourse tasks, under the fixed elicitation above, is one number counted from the transcript with no software; on Delaware it reaches AUC 0.6420 [0.5786, 0.7052] for mild impairment against control, while estimated alike the fair single-feature comparator is 0.6018, so the modelling apparatus buys about +0.036 and the hand count does not match it (section 5.16). This pilot is not powered to test it, so what is registered is descriptive: the distribution of total discourse words in healthy Libyan participants, the first such normative observation in Arabic; the impaired group's distribution beside it, with no significance test and no AUC; and the fraction of sessions in which the fixed elicitation was achieved. Markedly fewer words than the English reference distribution would be expected, since Arabic conveys in fewer orthographic words what English spreads across more, and would be a reason to derive the threshold from local controls, not to doubt the measure.",
    "**The minimal probe, a pre-registered secondary outcome.** The total number of words across the two connected-discourse tasks, under the fixed elicitation above, is one number counted from the transcript with no software; on Delaware it reaches AUC 0.6420 [0.5786, 0.7052] for mild impairment against control, while estimated alike the fair single-feature comparator is 0.6018, so the modelling apparatus buys about +0.036 and the hand count does not match it (section 5.16). This pilot is not powered to test it, so what is registered is descriptive: the distribution of total discourse words in healthy Libyan participants, the first such normative observation in Arabic; the impaired group's distribution beside it, with no significance test and no AUC; and the fraction of sessions in which the fixed elicitation was achieved. Fewer words than the English reference distribution would be expected, since Arabic conveys in fewer orthographic words what English spreads across more, and would be a reason to derive the threshold from local controls, not to doubt the measure.")
rep("B", "The collaborating clinician is asked for permission to approach patients attending their service, administration or supervision of the Arabic Montreal Cognitive Assessment, confirmation of existing diagnoses from the medical record, a quiet room for about 20 minutes per participant, clinical oversight including the authority to stop any session, and co-authorship on any publication — and is not asked to use the system, act on its output, change any aspect of patient care, or take responsibility for the analysis. The realistic timeline is one week to prepare the ethics submission, two to eight weeks of committee review outside the researcher's control, one to two weeks of clinic scheduling, three to six weeks of collection for 20 to 40 participants and one week of analysis; it cannot be completed before the thesis deadline, so the protocol is submitted as a completed, ethics-ready study design constituting the principal future work of the project. A completed protocol is itself a contribution: it converts \"Arabic validation is future work\" from an aspiration into a specified, costed, ethically framed plan that another researcher could execute.",
    "The collaborating clinician is asked for permission to approach patients attending their service, administration or supervision of the Arabic Montreal Cognitive Assessment, confirmation of existing diagnoses from the medical record, a quiet room for about 20 minutes per participant, clinical oversight including the authority to stop any session, and co-authorship on any publication — and is not asked to use the system, act on its output, change any aspect of patient care, or take responsibility for the analysis. The realistic timeline is one week to prepare the ethics submission, two to eight weeks of committee review outside the researcher's control, one to two weeks of clinic scheduling, three to six weeks of collection for 20 to 40 participants and one week of analysis; it cannot be completed before the thesis deadline, so the protocol is submitted as a completed, ethics-ready study design, which converts \"Arabic validation is future work\" from an aspiration into a specified, costed, ethically framed plan that another researcher could execute.")
rep("B", "This study cannot test the referential deficit index, and the arithmetic belongs in the protocol rather than being discovered later. The index's pronoun-free form, structurally what the Arabic index is, reaches AUC 0.596 on Pittsburgh and 0.625 on the age- and sex-matched subset (section 5.10.1), so the expectation for an Arabic dementia sample is roughly 0.60; detecting a true AUC of 0.60 at 80% power requires 130 participants per group, and this study's 20 per group detects only a true AUC of 0.748 or larger (Hanley–McNeil, two-sided α = 0.05; Table (B.5)), so a null result here would be uninterpretable and must not be reported as evidence against the index. No effect this project has measured is that large; the sizes that could test either effect are about 130 per group for the mild-impairment discourse effect and 141 for the dementia referential effect (Appendix I).",
    "This study cannot test the referential deficit index, and the arithmetic belongs in the protocol rather than being discovered later. The index's pronoun-free form, structurally what the Arabic index is, reaches AUC 0.596 on Pittsburgh and 0.625 on the age- and sex-matched subset (section 5.10.1), so the expectation for an Arabic dementia sample is roughly 0.60; detecting a true AUC of 0.60 at 80% power requires 130 participants per group, and this study's 20 per group detects only a true AUC of 0.748 or larger (Hanley–McNeil, two-sided α = 0.05; Table (B.5)), so a null result here would be uninterpretable and must not be reported as evidence against the index. The sizes that could test either effect are about 130 per group for the mild-impairment discourse effect and 141 for the dementia referential effect (Appendix I).")

for k, v in FILES.items():
    open(v, "w", encoding="utf-8").write(T[k]); print(k, "words", Bw[k], "->", len(T[k].split()))
