#!/usr/bin/env python3
"""cut_ch6.py -- Chapter 6 rewritten in points: 6.1 absorbs 6.1.1; 6.2 limitations paired with fixes; 6.3 trimmed;
6.3.1 retitled; 6.4, 6.5, 6.6 shortened; reviewer corrections (opening sentence, 'stronger position', RDI candidate,
closing line). Old section numbers are used for cross-references into Chapter 5 (renumber.py maps them)."""
import re
SRC = "/home/claude/work/src/docs/chapters_backup_v2/chapter6.md"
DST = "/home/claude/work/src/docs/chapters/chapter6.md"
raw = open(SRC, encoding="utf-8").read()
tail = raw[raw.index("\n**References Cited In This Chapter.**"):]
old = raw[:raw.index("\n**References Cited In This Chapter.**")]
tab62 = re.search(r"\*\*Table \(6\.2\) :.*?\n\n(\|.*?\n)+", old, re.S).group(0).rstrip()

new = r"""# Chapter 6 — Conclusion and Future Work

This chapter states what the thesis has established, what limits it, and what should be built next. One result in it is externally validated — the locked evaluation of section 3.9 — and everything that concerns the successor rests on development evidence alone, under the rule of section 1.7, sharing no table with a validated figure. The claim the whole thesis has been assembling is stated first, as one claim: every costly decision in this work lowered a number. Participant grouping forgave nothing to the easier evaluation much of this literature uses (section 3.6); age and sex matching set aside every recording that could not be pair-matched after age alone was measured to classify Pittsburgh at 0.707 (section 5.2); the corpus-compatibility rule declined a pooling measured to manufacture performance (section 3.2.1); the lock permanently excluded a known improvement, the pause and timing measures (section 6.2); the age-residualisation technique that scored 0.853 on development data was discarded when age proved recoverable from the supposedly age-free features at R² = 0.994 (section 5.8); the external corpus could be spent once, and was (section 3.9); and fifteen claims were tested, did not survive, and are reported in full (section 5.8). Two disciplines keep that list from congratulating itself: this work tested its own favourite version of the argument and declines it, since ungrouped folds inflate nothing on this model class (section 3.6.1), and section 5.1.1 concedes that the whole modelling apparatus buys about 4.5 points of AUC over one hand-countable quantity. The development figure of 0.7550 was produced under every constraint above at once; it is not a modest result but an expensive one. The instrument that produced it extracts 117 speech and language measures across five families; its externally evaluated English screening model uses a frozen 64-feature transcript-derived subset of linguistic, information-content and discourse-semantic measures, and 53 acoustic measures support a separate language-independent pathway.

## 6.1 Conclusions

The contributions are listed with the methodological ones first, because they are exactly derived, usable by other groups, and independent of whether this particular model is any good. Appendix F grades every component on a levels-of-evidence register; each point below carries its evidential status in the same breath.

1. **Control-referenced thresholding, with its exact precision result — the principal methodological contribution (section 5.18).** A screening threshold fixed on one population does not transport, and every obvious re-fixing rule reads the unlabelled marginal score distribution, which makes it arithmetically a referral-rate rule that moves with local prevalence. The rule that transports by construction sets the threshold at a fixed percentile of the local healthy-control distribution: specificity becomes a design parameter, sensitivity the reported variable, and the measured 79.8 / 79.9 / 77.8 across three cohorts illustrate the construction behaving as derived. The companion result converts the rule into a sample-size calculation — prospective specificity follows a Beta(k, n+1−k) law, so 20 controls buy [0.56, 0.91], about 59 buy ±10 points and about 108 buy ±7.5 — and the rule needs healthy speakers and no patients, inverting the deployment economics of a low-resource setting. Its status: post hoc on the frozen model, not pre-registered, not deployed; the operating point remains 0.367 and the primary external result remains the one reported at it.
2. **A screening system evaluated across corpora with a locked, one-shot external test, and the governance record around it** — the contamination identified by external review, the lock that answered it, the retraining, the single scoring at a threshold fixed in advance, and the exposure history reported rather than smoothed (section 3.9). The frozen English screening model reached external AUC 0.8533 [0.7371, 0.9458].
3. **What the modelling apparatus is worth, measured with both sides estimated alike.** The calibrated ensemble over 64 engineered features is the expensive part of the system — it needs a computer and cannot run on paper — and against a single-feature comparator selected inside each training fold it buys +0.0455 on the development target (0.7550 against 0.7096) and +0.0361 on mild-impairment discourse (0.6379 against 0.6018): roughly four points of AUC on both, and no "four points versus nothing", since the earlier appearance that the apparatus bought nothing on discourse came entirely from a comparator estimated differently from the model (section 5.28).
4. **The right task depends on whether the computer is present.** On picture description the best single feature is the information-unit total in five folds of five, with selection optimism exactly zero, so the paper instruction — count the information units — is stable; on discourse no measure is stably best, so a field worker could not reliably be told what to count. Section 5.25 establishes that for mild impairment the discourse genre carries the signal and the picture task performs at chance, while the paper fallback is more dependable on the picture than on discourse. Table (6.1) states the resolution, which the pilot protocol of Appendix B implements: administer both genres, score discourse when the software is present, and count information units on the picture when it is not.
5. **Corpus-compatibility testing as a named, cheap pre-pooling check.** Before pooling two corpora, test whether a classifier can separate their healthy speakers; this project measured 0.930 between two healthy groups, traced it to transcription convention, and derived the rule that corpora are combined only when each contributes both classes (section 3.2.1). The answer is model-dependent — a published counter-case pooled the same corpora successfully under a contextual representation (section 2.3) — which is exactly why the test must be run per project.
6. **An Arabic contribution in three parts — an instrument for the dementia target, a documented resource gap, and a corpus specification** (sections 6.4 and 6.5). The adaptation alone would overstate it; the gap alone would undersell it.
7. **A refusal architecture, enforced in code.** The system declines to produce a result for audio below the level at which pause extraction was measured to fail, for a stimulus other than the calibrated one, for an Arabic session — no validated Arabic screening score exists — and for any use outside the model card's declared scope (sections 3.8 and 4.5). Encoding a competence boundary and enforcing it at runtime is rare in this literature, and it is a biomedical-engineering contribution rather than a machine-learning one.
8. **A deployable, quality-gated assessment platform that degrades to paper** (Chapter 4): a screening score where computer, model and recogniser are present, an indicator profile without the model, a hand-countable checklist without any device; and an exploratory overlearned-memory probe adapted to the deployment culture, Qur'anic recitation scored against the surah actually recited, framed throughout as exploratory (section 4.2).
9. **Fifteen documented negative results in one register** (section 5.8): three changed a design decision, four bounded what is reachable, two removed arguments this thesis would otherwise have made, two settled a specification question, one produced the project's strongest positive finding by failing, one redrew the boundary of a contribution before it was written in, and the final two each bounded a component's claim.
10. **A pre-registration practice with a stated failure mode and a stated remedy.** Four defects arose in seventeen registered runs, every one in something the registration did not think it needed to state — a tokenisation rule, a denominator's interpretability, a label rule, and a comparison whose two sides were estimated by different procedures (section 3.10) — and the remedy is a rule any project can adopt: register a sanity gate on every derived quantity an analysis depends on, including its labels. The failure mode is this project's most transferable lesson: every defect this work found in its own analysis, artwork and deployment was silent — a tokenisation filter differing from the committed extractor, a label rule taking the first row in file order, bootstrap intervals 1.09 to 1.31 times too narrow, a stimulus missing two of the units scored against it, nine of sixty-four features silently median-imputed on every machine the installer configured. Not one raised an error, because each component met its contract — return a number — while the number's meaning had changed; a component whose contract is to return a value cannot report that the value has stopped meaning what it meant, so something outside it must (sections 3.10 and 4.5.1).

**Table (6.1) : The task choice depends on whether the computer is present**

| | With the software | Without it, on paper |
|---|---|---|
| Which task | connected discourse | picture description |
| Why | the genre effect: +0.0788 [0.0042, 0.1579] for two discourse tasks over three picture tasks, on the target where early detection changes management (section 5.25) | one countable quantity, selected in five folds of five, keeps the field instruction stable; on discourse no measure is reliably best (section 5.28) |
| What it costs | a device, an extractor and the frozen model | about 4.5 points of AUC against the deployed ensemble (section 5.1.1) |

## 6.2 Limitations

Each limitation is stated with what would be needed to remove it.

1. **The instrument is wrong about roughly one person in three at its operating point** — accuracy about 67% on development data and 34 of 53 on the locked external set; the AUC of 0.7550 means that, given one impaired and one healthy recording, the model ranks the pair correctly about three times in four. What removes it: a better model, which the frozen-model constraint forbids until a fourth both-class corpus exists to validate one.
2. **The external specificity of 33.3% at the pre-specified threshold**, diagnosed in section 5.13 as a threshold-referencing failure — the threshold landed at 96.2% sensitivity where the design intent was near 75%, and the eighteen misclassified controls had genuinely described the picture less well, so the model was not malfunctioning — and recovered to 77.8% by control-referenced thresholding. What remains after the diagnosis: the deployed system still carries 0.367; the remedy is analysed, not implemented, and was chosen after seeing the data; and the task-administration explanation for the false positives is a hypothesis, confounded with an 8.4-year age difference in a sample of 27. What removes it: the pilot's healthy arm, which derives the local threshold prospectively and tests the administration hypothesis under a fixed elicitation protocol (Appendix B).
3. **The deployed picture-description architecture performs weakly for mild impairment, and no threshold rule can change that**: the specificity ceiling at 75% sensitivity on that cohort is 0.376 (section 5.15), and the cohort cannot be learned from its own recordings at all (section 5.12.1). Within the available multi-task corpus, connected discourse is the more promising elicitation genre — one the deployed model was never fitted on (section 5.25). What removes it: the successor corpus of section 6.5, which carries both genres from every speaker.
4. **The instrument is not validated in Libya and has never been used with a real patient**; the Arabic engine's word lists are drafted against Modern Standard Arabic and unvalidated against Libyan dialect. What removes it: the pilot, then the powered study.
5. **The external test set's exposure**, stated in the canonical form: the corpus was excluded from the training data of the final model and from every modelling decision after the lock. Before the lock, five exploratory scorings occurred, one of which informed the decision to include Delaware in the development pool. That one architectural decision was made with knowledge of a score from that corpus, so 0.8533 validates the frozen English screening model on data absent from its training but is not free of that one prior exposure (section 3.9). What removes it: nothing on this corpus; only a fourth corpus, under the staged design of section 6.3.
6. **The picture the deployed system shows is not the picture the model was fitted on.** The residual mismatch that cannot be corrected graded DISPLACEMENT-MATERIAL: if the substituted picture costs a speaker even one information unit, 13.1% of control recordings cross the screening threshold (section 4.3.1). Whether it costs real speakers anything is unknown, and this is the largest single untested assumption standing between the reported external figure and the deployed instrument — larger than the threshold-transfer problem beside it. What removes it: the pilot's pre-registered stimulus-equivalence endpoint.
7. **A measured sex disparity of sixteen AUC points**, a specificity failure with a measured mechanism (section 5.2.1) that no threshold or rescaling can repair, as the invariance result of section 3.11 proves. What removes it: a feature set that does not conflate *said less* with *impaired*, or sex-specific normative reference ranges, carried into section 6.5 as a design requirement on the successor.
8. **The cost of the lock.** Freezing the model bought a one-shot external evaluation and permanently excluded a known improvement: a pause-and-timing feature module is implemented, tested and deliberately unwired, kept outside the deployed package in `future_work/pause_features.py`, while pause and timing measures are among the strongest reported predictors in this literature and the first thing background noise destroys (section 5.9). What removes it: a fourth corpus carrying both classes, because the existing external test is spent.
9. **The recitation probe's motivating dissociation** — overlearned material preserved while episodic memory fails — has no data behind it, and its nearest English analogue, the story retell of section 5.25, points the other way to the extent it bears on the question at all. The probe remains exploratory, and nothing in this thesis treats it otherwise.

## 6.3 Future Work

The future work follows from the limitations, and its first sentence is a boundary rather than a plan: the same properties that make the instrument administrable in a Libyan home without a clinic — no network, no specialist, a paper fallback — make it administrable in a displacement or post-disaster setting, where cognitive screening is least available and cognitive harm most concentrated, and whether it is *useful* there is entirely untested.

The principal future work is the Libyan study, and its pathway is reported at exactly the strength it has. Clinical validation has not been performed. A pathway toward it has been established through engagement with a national patient organisation, and that engagement is stakeholder engagement, not clinical validation: it is confined to recruitment feasibility and cultural acceptability, the organisation has not reviewed, assessed or endorsed the instrument, and no patient data has been involved. The reference standard requires clinician-confirmed diagnosis; contact has been initiated and no arrangement is in place, so the protocol's reference-standard section is written as what would be required — the Arabic Montreal Cognitive Assessment administered blind to the system's output — rather than as an arrangement. The feasibility pilot is submitted as a completed, ethics-ready protocol (Appendix B) with its endpoint structure fixed in advance: the eventual study's powered primary endpoint is dementia against healthy controls, with a pre-specified mild-impairment arm that is explicitly underpowered and descriptive only. What the pilot delivers is deliberately modest — battery feasibility with elderly Libyan participants, the first Libyan healthy normative distributions, validation of the Arabic word lists against dialect actually spoken, a provisional control-referenced threshold reported at its exact interval width, the elicitation-administration measurements no existing corpus records, and the pre-registered stimulus-equivalence check of the substituted picture — and it cannot test discrimination: at 20 per group it detects only a true AUC of 0.748 or larger, above every effect this project has measured, and the protocol says so in its own words.

For the model itself, the staged validation design below is this project's own prescription for what it could not do, and it follows from the measured transport failures of section 5.13: one global threshold does not transport, and one global recalibration cannot repair it. The stages are strict and ordered: a development pool for fitting and feature decisions, as now; a dedicated calibration cohort, used openly and repeatedly to set the operating threshold and the recalibration map and declared as spent — the locked corpus is the natural candidate, since its scores are already on the record, and what it may never again be called is an external test set; a freeze of everything, model, threshold, calibration map and feature set, recorded as at the lock; and one evaluation on a corpus never touched, pre-registered, single execution, reported whatever it says. Candidate corpora for the last stage were checked for provenance. TAUKADIAL — 169 participants and 507 picture-description recordings in Mandarin and English, targeting mild impairment, whose English arm even uses the standard kitchen-scene stimulus — is not clean until checked, because that arm is a University of Delaware community cohort recruited under the same programme as the Delaware corpus in this project's training pool, so its English participant identifiers would have to be checked against the 291 Delaware training participants and any overlap removed, or the evaluation restricted to the Mandarin arm, a different language and therefore a different claim [1]. The Framingham Heart Study voice archive — digitally recorded neuropsychological examinations linked to clinically adjudicated dementia outcomes, independent of DementiaBank — would need a diarisation stage the pipeline does not have, and access runs through formal application and committee review [2]. ADReSS and ADReSSo are excluded, because ADReSS is, in its organisers' words, "a curated subset of DementiaBank's Pitt Corpus, matched for age and gender": evaluating a model trained on all 548 Pittsburgh recordings against it would be direct test-set contamination, and ADReSSo draws on the same pool [3]. Three further directions close the list: pretrained speech and text representations remain the principal untested modelling direction, unattemptable in the development environment and forfeiting the paper fallback if adopted wholesale (section 5.1.2); per-deployment threshold derivation on local healthy controls is the operational form of the first contribution (section 5.18); and the pause-and-timing module is wired in only after a fourth both-class corpus exists to validate the enlarged model.

### 6.3.1 The Instrument That Could Be Deployed First

Three instruments exist in this work, and a Libyan clinic could deploy exactly one of them in the near term. Table (6.2) states the three paths and what each requires.

""" + tab62 + r"""

The acoustic model needs no transcription, no tagger, no lexicon and no normative ranges, and its cost relative to the linguistic instrument is measured: 0.708 against 0.755 on the matched English comparison, about five points of AUC. Its provenance is stated precisely: the original training script is lost, the configuration was recovered by introspection of the deployed artifact, the protocol was confirmed by a pre-registered signature test, and the embedded figure reproduces from a fresh fit run by committed code to within 6.0 × 10⁻⁵ — a reconstruction that has been verified rather than merely trusted, though a verified reconstruction is a weaker guarantee than a committed training script would have given. The caveat belongs in the same paragraph as the recommendation: 0.708 was measured on a matched English subset of 373 recordings, its transfer to Arabic is exactly as unvalidated as everything else in section 6.4, and the one measured Arabic figure — 0.622 [0.378, 0.857] on the 24-speaker pilot, an interval spanning chance — comes from this same acoustic model. Two instruments were built, and the weaker one is the deployable one; what changes that is an Arabic corpus meeting the specification of section 6.5, at which point the linguistic instrument becomes available and the acoustic one becomes its fallback.

## 6.4 The Arabic Contribution

The Arabic contribution is stated as what it is — an instrument for the dementia target, a documented resource gap, and a corpus specification — because the English construct probe changed what may be claimed. The referential deficit index discriminates in a dementia cohort: 0.596 [0.541, 0.652] on Pittsburgh, improving to 0.625 [0.562, 0.690] on the age- and sex-matched subset — within the literature identified by this search, the first computation of the construct on the speech of diagnosed patients in any language (section 5.10.1). On mild impairment it sits at chance on all five tasks of the one corpus permitting the test, and so does the English pronoun marker it replaces (section 5.27). The failure is in the construct, not the implementation and not the language: on this English evidence, target and stage are the dominant explanation — the index separates at the dementia stage and not at the mild-impairment stage — and nothing measured here supports it as an early marker in any language. The pro-drop argument survives unchanged: Arabic normally omits the subject pronoun because the verb carries person, number and gender, so pronoun counts sit on a different baseline for grammatical rather than clinical reasons, and the English pronoun-overuse marker cannot be carried across (section 3.4). The referential deficit index remains the candidate replacement for it, measured so far in English only; what changed is not whether the candidate works but what it is for. The cost is this: mild impairment is where early detection changes management and is the future study's most valuable target, and the Arabic component as designed cannot address it. Making it a mild-impairment instrument requires an Arabic lemmatiser, because morphological richness confounds surface lexical-diversity measures, an Arabic dependency parser, and Arabic embeddings, all running offline on the target hardware — a substantially different engineering problem from the one this project solved, and naming its three components exactly is worth more than claiming coverage the measurement does not support.

What the measurement saved exceeds what it cost. It arrived before 240 Libyan participants were recruited against a marker that cannot detect what the study most needs to screen for; had the Arabic study run to the earlier specification — a single-task picture-description corpus sized for the referential index — it would have returned a correctly powered null that was uninterpretable, because a single-task, single-language study cannot distinguish a wrong marker from a wrong task from a wrong implementation. The English probes separate all three (sections 5.27 and 5.25), and the finding changed what the corpus must contain — both genres from every speaker.

The resource gap is documented rather than asserted, with its scope stated first: at the time of the search, no publicly available corpus could be identified that pairs cognitively impaired and cognitively healthy Arabic speakers on a connected-speech task with transcripts. Each qualifier does work — clinical archives surely hold such recordings, the claim concerns what a researcher can obtain; word-list, naming and repetition batteries do not elicit the referential behaviour the index measures; and audio without transcripts supports no lexical or syntactic measurement, since Arabic speech recognition is not dependable on dialectal elderly speech. The evidence is a documented search, not a systematic review, and it brackets the gap from both sides: DementiaBank lists English, German, Greek, Korean, Mandarin, Spanish and Taiwanese sections and no Arabic; a survey of the field names twelve datasets, none of them Arabic [2]; the newest benchmark for early cognitive impairment is British English only, named by its authors as a limitation [4]; the one Arabic dataset with both classes — the 24-speaker collection this project's acoustic pilot used — elicits Montreal Cognitive Assessment subtest responses, word lists rather than connected speech [5]; a systematic review of cognitive assessment for Arabic speakers, 154 studies, found no connected-speech instrument among the validated ones [6]; and Arabic connected speech exists in quantity in speech-recognition corpora that carry no clinical labels. Data with both classes and no connected speech; connected speech with no labels; never the join. A search returning both halves and never the intersection is far stronger evidence of a missing join than a search returning nothing, and the claim is falsifiable: one counterexample retires it, and that would be good news. Against that gap, the contribution is the three parts named above: a working Arabic engine that computes the candidate marker, its evidential status stated exactly; the documented absence, stated at the strength the search supports and no more; and the specification of section 6.5, which is the part another group could act on tomorrow.

## 6.5 The Corpus Specification

What the successor corpus must contain is specified in full in Appendix I, derived entirely from this project's own measurements. It is led by genre rather than by named tasks — connected discourse for the mild-impairment target, picture description retained for the dementia target — and requires both genres from every participant, because a single-genre corpus cannot separate a marker failure from a task failure; it fixes elicitation, because word count is the strongest single mild-impairment measure on discourse and under variable administration it measures the examiner; it requires transcription that preserves the dialectal demonstratives and vague nouns the dementia measurement is made of; it splits the marker families by target; and it requires the healthy arm to recruit both sexes in numbers sufficient for sex-specific reference ranges, the design requirement carried from section 5.2.1. Its sample sizes come from the measured effects — 141 per group for the dementia referential effect, 130 for the mild-impairment discourse effect powered on the conservative end of its range, 108 healthy controls for a threshold precise to ±7.5 points — and Appendix I states how the recommended feasibility floor of 120 per group relates to them. The specification is the actionable third of the Arabic contribution, with the pilot of Appendix B as its first increment.

## 6.6 The Closing Claim

The frozen English screening model reached external AUC 0.8533 [0.7371, 0.9458] on data absent from its training, at a threshold fixed in advance, scored once, under the exposure history of section 3.9; at that threshold it was sensitive and unspecific, and the specificity is diagnosed and its recovery specified in section 5.13 — a post-hoc methodological contribution, not pre-registered, not deployed, and requiring prospective validation. The apparatus that produces the score — sixty-four engineered features, a calibrated ensemble, the whole modelled part of the system — is worth about four points of AUC over counting one quantity by hand, measured the same way on both targets (section 6.1). That is a real gain, and a small one.

> **The entire modelling apparatus is worth about four points of AUC, and everything else this thesis contains is worth more than that.**

The lock that made one external number mean something, and cost three results to enforce. The fifteen negative results, three of which changed a design decision and two of which removed arguments this thesis would otherwise have made. The pre-registration discipline, with its four disclosed failures and the working rules derived from them. The reconciliation of every figure that has ever held more than one value. The measurement that the Arabic instrument addresses dementia rather than the target the future study most needs — made before two hundred and forty people were recruited against it. None of that is accuracy, and all of it is what makes the accuracy readable; a number without those things is the field's present situation — more than a decade of reported performance above ninety per cent, a minority of studies reporting statistical significance, and no tool in routine clinical use (section 2.3). What this thesis leaves behind is a screening method whose every number can be traced to the file that produced it, whose weaknesses are measured rather than suspected, and whose next study is specified to the participant — which is what an instrument for a setting without memory clinics has to be before it can be allowed to matter.

---
"""
open(DST, "w", encoding="utf-8").write(new + tail)
print("chapter6.md:", len(re.findall(r"\S+", re.sub(r"\|", " ", new))), "words")
