#!/usr/bin/env python3
"""cut_ch5.py -- assemble the cut Chapter 5 from the pre-cut source (chapters_backup_v2) and new merged text.
Old table/figure/section numbers are kept in the text here; renumber.py maps them afterwards."""
import re
SRC = "/home/claude/work/src/docs/chapters_backup_v2/chapter5.md"
DST = "/home/claude/work/src/docs/chapters/chapter5.md"
raw = open(SRC, encoding="utf-8").read()
body = raw.split("\n**References Cited In This Chapter.**")[0]
tail = raw[len(body):]

# ---- slice the old file by heading ----
lines = body.split("\n")
heads = [(i, l) for i, l in enumerate(lines) if re.match(r"^#{2,3} \d", l)]
def section(title_prefix):
    """text of the old section whose heading starts with title_prefix, heading line included, up to the next heading of any level"""
    for k, (i, l) in enumerate(heads):
        if l.startswith("## " + title_prefix) or l.startswith("### " + title_prefix):
            j = heads[k + 1][0] if k + 1 < len(heads) else len(lines)
            return "\n".join(lines[i:j]).rstrip() + "\n"
    raise KeyError(title_prefix)
def between(text, start, end=None):
    """slice of text from the line starting with `start` to (not including) the line starting with `end`"""
    L = text.split("\n")
    a = next(k for k, l in enumerate(L) if l.startswith(start))
    b = next(k for k, l in enumerate(L) if k > a and l.startswith(end)) if end else len(L)
    return "\n".join(L[a:b]).rstrip() + "\n"
def table(text, caption_prefix):
    """the caption line plus the table that follows it"""
    L = text.split("\n")
    a = next(k for k, l in enumerate(L) if l.startswith(caption_prefix))
    b = a + 1
    while b < len(L) and (L[b].startswith("|") or not L[b].strip()): b += 1
    return "\n".join(L[a:b]).rstrip() + "\n"
def sub1(s, old, new):
    assert s.count(old) == 1, (old[:60], s.count(old))
    return s.replace(old, new)

out = []
out.append("# Chapter 5 — Results and Discussion\n")

# ═════════ preamble ═════════
out.append("""
This chapter reports what the instrument was found to do, in the order an examiner needs it. Four findings carry it. First, external discrimination held: the frozen English screening model reached AUC 0.8533 [0.7371, 0.9458] on a corpus collected by different investigators, scored once, at a threshold fixed before the run, under the exposure history of section 3.9 (section 5.3). Second, at that threshold sensitivity was 96.2% and specificity was low — a threshold-transport failure rather than a model failure, diagnosed in section 5.13, where a threshold referenced to local healthy controls recovers specificity to 77.8% on the same corpus; that rule is post-hoc, undeployed and awaiting prospective validation, and its status is stated once, where it is owned. Third, the instrument carries a measured sex disparity of sixteen AUC points with a mechanism that no threshold or rescaling can close (section 5.2). Fourth, fifteen pre-registered successor ideas were tested against the frozen model and none beat it; Table (5.11) names each one, what it established and where its full output lives (section 5.8).

The chapter reports the negative results in the same detail as the positive ones, and it uses the repository as a third layer, once and deliberately: a probe that changes nothing about what Dhikra can claim is reported as one row — its registration, its result and the repository path to its full output — rather than as a section, and Appendix J is the map to those paths. Sections 5.1 to 5.12 report the externally evaluated model: development performance and its confounds, the external evaluation and calibration, the scorer check against a human, the negative results, the measurement properties, the Arabic construct probe and the cross-corpus evidence behind the pooling decision. Section 5.13 is the operating point — why the threshold did not transport and what recovers it. Sections N5.14 to N5.16 are the probes that belong to the specified successor, reported under the rule of section 1.7: development evidence, none of it externally validated, none of it in a table with a validated figure. Two findings among them reshaped the successor: the mild-impairment cohort cannot be learned from its own picture descriptions (section 5.12.1), and within the one corpus that administers several tasks to both classes the recoverable signal lives in connected discourse (section 5.25). One measurement is named as a contribution because the literature identified by this search does not report it: the reproducibility of the screening decision itself, 0.8355 (section 5.26.1).
""")

# ═════════ 5.1 ═════════
s = section("5.1 Development Performance")
s = sub1(s, "what the same architecture achieves on Delaware alone is reported in section 5.12.1, and the distance between those two numbers is one of this chapter's principal findings.",
         "what the same architecture achieves on Delaware alone is reported in section 5.12.1, and the distance between those two numbers is one of this chapter's principal findings.")
out.append("\n" + s)
out.append("\n" + section("5.1.1 The Simplest"))
out.append("""
### 5.1.2 The Search For A Better Number And What It Found

Whether anything within the project's constraints could improve the deployed figure was searched under four fixed conditions: deployed model, features and threshold unchanged; the external corpus left unscored; deployability preserved; and any gain real rather than an evaluation artefact. One real gain was found, and it is a protocol change rather than a model change: averaging a participant's repeat recordings raises participant-level discrimination from 0.8095 at recording level to 0.8551 when every participant's scores are averaged, with the qualification that single-visit participants alone already reach 0.8198, so part of the span is the removal of weighting toward frequent attenders, and section 5.24 decomposes the remainder. A pretrained-representation arm neither refutes nor confirms a ceiling claim: replacing all 64 handcrafted features with a 300-dimensional mean document vector from pretrained static word embeddings — same cohort, architecture and folds — gives 0.8018 against the handcrafted 0.8095 on Pittsburgh, graded CEILING-CLAIM-QUALIFIED under its pre-registered criteria; sixty-four interpretable features match three hundred opaque dimensions, but a static, order-discarding representation is a floor, not a ceiling, and a contextual transformer, untestable on this hardware, would very likely do better. Hyperparameter tuning was rejected because any configuration selected on development performance inflates the development estimate, the external corpus is spent, and the defensible version — nested tuning inside training folds, roughly 180 fits of a calibrated three-member ensemble — was unaffordable in the time remaining. Under the four constraints the space is close to empty: a protocol change worth about 0.045, a representation that matches rather than beats, two inert features that cost nothing (section 3.2.2), a transcription artefact whose correction lowers the headline by 0.010, and a task-genre finding the deployed instrument cannot act on because its training corpus has healthy controls on one task only (section 5.25). The remaining gap to the best comparably evaluated published result is about four accuracy points, and closing it means more features or contextual embeddings, both of which forfeit the paper fallback, the explainable indicators and the operator-facing reference ranges that are the point of the design. The lower number is taken, and the reasons are measured.
""")

# ═════════ 5.2 ═════════
out.append("\n" + section("5.2 Confound Control"))
old521 = section("5.2.1 The Sex Disparity")
t53 = table(old521, "**Table (5.3)"); t54 = table(old521, "**Table (5.4)")
out.append(f"""
### 5.2.1 The Sex Disparity And Its Mechanism

Subgroup performance by sex is reported because it is routine for clinical prediction models and because this project's own audit found it to be the largest disparity the instrument carries. Table (5.3) gives the headline: on Pittsburgh out-of-fold predictions with participant-clustered bootstrap, female participants are classified at 0.8687 and male at 0.7041, a difference of +0.1646 [0.0535, 0.2736], the female figure exceeding the male in 1,998 of 2,000 replicates; Delaware points the same way, 0.6425 against 0.5958 (`results/reconstruction/phase0_free_f_capture.txt`). Sixteen AUC points is not a rounding difference: a screening instrument with that gap will miss more male cases at any shared threshold, and in deployment nobody would notice.

{t53}
Part of the gap is severity composition, and that part is measurable: within the impaired group, women in this cohort are more severely affected (MMSE 18.77 against 21.35, p = 0.0002) and 2.9 years older, while controls are equivalent, and since sensitivity falls steeply with MMSE (section 5.7) a female impaired group weighted toward severe cases is mechanically easier to detect. Composition explains less than it first appears: across the committed matching procedure's ten seeds, age and sex matching shrinks the gap only to a mean of +0.140 (seed range +0.092 to +0.191). The residual is not a sensitivity failure — sensitivity within MMSE band is equal or better for men in three of four bands, as Table (5.4) shows — but a specificity failure, 0.545 for female controls against 0.438 for male, with the two distributions compressed toward each other for men from both directions: male controls score higher (0.447 against 0.382) and impaired men score lower (0.586 against 0.641), which is exactly what lowers a ranking measure.

{t54}
The mechanism has nothing to do with cognition. Healthy men in this cohort simply say less about the picture — 13.01 information units against 14.14 (p = 0.018), 3.43 actions against 3.95 (p = 0.0075) — while impaired men say more than impaired women (word count 103.9 against 90.6; 10.66 information units against 9.81). The model's dominant feature is information content (section 5.1.1), so a healthy man who is less expansive looks impaired and a fluent impaired man looks healthy; sex differences in narrative verbosity are well documented and benign, and the instrument does not know the difference. A threshold rule cannot fix this: sex-stratified control-referenced thresholds at an 80% specificity target equalise specificity (0.799 female against 0.798 male) but raise the male threshold to 0.625 against 0.481, so fewer impaired men clear it and the sensitivity gap widens from 0.176 to 0.348. A discrimination gap cannot be thresholded away, exactly as section 5.15 establishes for Delaware, and within-sex rescaling does nothing either, as the invariance result of section 3.11 requires (−0.0015 on the pooled figure, −0.0052 on the model score — noise). The deployed pooled choice over-refers men (specificity 0.438 against 0.545) rather than under-detecting them; that error direction favours sensitivity over missed cases, but excess false positives remain an equity, anxiety and resource-use concern, and the property was measured after the fact, not designed.

This disparity leads the limitations of Chapter 6; sex-stratified performance is reported wherever it can be computed; and the fix is named as future work — a feature set that does not conflate *said less* with *impaired*, or sex-specific normative reference ranges, which the pilot's healthy arm can supply if it recruits both sexes in sufficient number. Performance is flat across transcript-length quartiles (0.781 / 0.822 / 0.820 / 0.797 on Pittsburgh), so the instrument is not merely measuring how much someone said.
""")

# ═════════ 5.3 ═════════
s = section("5.3 External Validation")
s = sub1(s, "the 33.3% specificity is a threshold-referencing failure diagnosed in sections 5.15 to 5.19, with a remedy analysed but not deployed.**",
         "the specificity at the pre-specified threshold is a threshold-referencing failure diagnosed in section 5.18, with a remedy analysed but not deployed.**")
s = sub1(s, "0.376 for Delaware (section 5.15)", "0.376 for Delaware (section 5.15)")
s = sub1(s, "Sections 5.15 to 5.19 establish what that figure actually was — a threshold that landed at the wrong point of the external cohort's curve, and eighteen control speakers whose descriptions were genuinely impoverished — and the reader is directed there now rather than left with the number for twelve pages.",
         "Section 5.18 establishes what that figure actually was — a threshold that landed at the wrong point of the external cohort's curve, and eighteen control speakers whose descriptions were genuinely impoverished — and what recovers it (`results/summary/locked_external_validation.json`).")
out.append("\n" + s)

# ═════════ 5.4 ═════════
out.append("\n" + section("5.4 Calibration"))
old541 = section("5.4.1 Calibration Meets")
t58 = table(old541, "**Table (5.8)")
out.append(f"""
### 5.4.1 Calibration Meets The Bayesian Chain

A defect was found, the standard correction was derived, and a pre-registered test said do not apply it. The defect: section 3.12 derives the likelihood ratio by dividing the model's odds by the training prevalence, a step exact only for a calibrated score, and the score is not calibrated; with slope 1.2887 the derived ratio is pulled toward one and the speech evidence is systematically under-weighted, by up to 0.16 of posterior probability and always understating at the top (Appendix H, Table (H.1)). The correction is a derivation, not a tuning exercise — two-coefficient logistic recalibration, maximum likelihood, no search — and because the fitted slope is positive it is strictly monotone, so discrimination, both operating points, the locked external result and the deployed decision would all have been invariant [1, 2, 3]. The obvious test was forbidden: trying the correction on the locked corpus would be exactly the contamination section 3.9 documents. The decision was therefore made on development data alone, by cross-cohort transfer of the recalibration itself — fit the two coefficients on one development cohort, apply to the other, in both directions, under criteria fixed in writing beforehand: apply the correction only if it moves the slope toward one in both directions without worsening the Brier score by more than 0.005. Table (5.8) reports the result: it fails in both directions on both criteria, grade CORRECTION-DOES-NOT-TRANSFER (`results/reconstruction/recalibration_decision.json`).

{t58}
The reason is the finding. Pittsburgh's own slope is 1.516 and Delaware's is 0.823: the two development cohorts are miscalibrated in opposite directions, the pooled 1.2887 is an average of two numbers pointing opposite ways, and no single recalibration can fit both, because the miscalibration is a property of the cohort and not of the model — the third independent line of evidence, with the threshold and recalibration analyses of section 5.13, that a single global map does not serve multiple cohorts, and a further argument for control-referenced thresholding, which is calibration-independent by construction. The coda is the part written most carefully. The locked corpus was scored, descriptively, after the decision was made, under a declaration fixed before execution that whatever it showed would not enter the decision: its raw slope is 1.886, the most compressed of the three, and the development-fitted correction moves it to 1.464 — toward one, on both criteria the development arms failed. Had the locked corpus been consulted, the correction would have been applied; the rule that forbade consulting it changed the decision, which is what the rule is for. The arithmetic is unchanged, and the defect, its magnitude, direction and containment are reported: it is a reporting error and not a triage error, since everyone above 0.367 is referred either way, and the banded output absorbs it in 13 of 14 representative comparisons, the exception being a score of 0.70 at age 65, which moves one band.
""")

# ═════════ 5.5 ═════════
out.append("\n" + section("5.5 Feature Contribution"))
out.append("""
### 5.5.1 The Information Unit Scorer Checked Against A Human

The scorer behind the instrument's most important feature family was compared against a human under a pre-registered, report-and-stop protocol: twenty Pittsburgh transcripts, stratified across the range of automated counts, scored blind by hand against the 23-unit scheme, with a registered criterion of a mean absolute difference of at most 1.200 units per transcript. The result is 1.600 and the grade is INADEQUATE (`results/reconstruction/scorer_check_grade.json`); what follows says what kind of failure it is. It is a systematic undercount, not disagreement: the bias is −1.500, misses outnumber false credits 41 to 11, so the synonym lists are too tight, and the water unit is worst (nine misses). Yet the software agrees with the human about who scores higher than whom — intraclass correlation 0.904, against a published human-to-human figure on this task of 0.347 [−0.30, 0.69], Spearman 0.920, 6.8% discordant pairs [4] — and the offset is flat: a mechanism proposed in advance, that speakers who point rather than name would be undercounted more, was refuted (the difference is uncorrelated with the human total, −0.005, p = 0.982). Four consequences follow. The rank-based results survive, because every AUC resting on these features depends on ordering and the ordering is preserved. The absolute scale does not: the operator-facing reference ranges are calibrated against a scorer that runs about 1.5 units low. The paper fallback is directly affected — a health worker counting by hand lands about 1.5 units above the software for the same speech, so a threshold derived from software counts does not transfer to hand counts and the paper instrument needs its own cut-off from hand-scored local controls, a second, independent argument for control-referenced thresholding. And the successor protocol needs scorer training and double-scoring of a subsample, because one rater gives agreement, not human reliability.
""")

# ═════════ 5.6, 5.7 ═════════
out.append("\n" + section("5.6 Analysis Across Tasks"))
out.append("\n" + section("5.7 Severity Estimation"))

# ═════════ 5.8 ═════════
old58 = section("5.8 The Fifteen")
rows = between(old58, "| # | What was hoped for", "What the first thirteen did").rstrip() + "\n"
rows = rows.replace("| # | What was hoped for | What was found | What it established |\n|---|---|---|---|",
                    "| # | What was hoped for | What was found | What it established | Record |\n|---|---|---|---|---|")
REC = {1: "`results/wls/findings.json`", 2: "`results/wls/findings.json`", 3: "`results/reconstruction/age_leakage_evidence.json`",
       4: "`results/fusion/results.json`", 5: "`results/fusion/results.json`", 6: "`results/summary/review2_actions.json`",
       7: "`results/reconstruction/domain_shift_and_errors.json`", 8: "`results/reconstruction/leakage_demonstration.json`",
       9: "`results/reconstruction/phase0_free_recovery.json`", 10: "`results/reconstruction/sample_adequacy_probe.json`",
       11: "`results/reconstruction/phase0_free_c_capture.txt`", 12: "`results/reconstruction/task_count_curve.json`",
       13: "`results/reconstruction/rdi_cross_task_probe.json`", 14: "`results/reconstruction/age_adjustment_discrimination.json`",
       15: "`results/reconstruction/vector_matching_probe.json`"}
newrows = []
for ln in rows.split("\n"):
    m = re.match(r"^\| (\d+) \|", ln)
    if m:
        n = int(m.group(1)); assert ln.endswith(" |"); ln = ln + " " + REC[n] + " |"
    newrows.append(ln)
rows = "\n".join(newrows)
# shorten the four longest cells and repoint the section references
rows = sub1(rows, "The instrument detects present impairment, not future risk; the scope was fixed by measurement, not preference", "The instrument detects present impairment, not future risk")
rows = sub1(rows, "Corpus identity is a stronger signal than disease; pooling classes across corpora lets a model learn the archive instead of the condition", "Corpus identity is a stronger signal than disease; a model pooled that way learns the archive, not the condition")
rows = sub1(rows, "Residualising a variable out of a feature set does not remove it; the technique was discarded. Recoverability is not use — within class, the model's evidence is age-flat (section 3.12)", "Residualising a variable out of a feature set does not remove it; the technique was discarded (recoverability is not use: within class the model's evidence is age-flat, section 3.12)")
rows = sub1(rows, "Domain shift is not repaired by deleting the features that carry it; the reverse direction's +0.014 is not claimable — the ranking saw the target (section 5.21)", "Domain shift is not repaired by deleting the features that carry it; the reverse direction's +0.014 is not claimable — the ranking saw the target (section 5.21)")
out.append(f"""
## 5.8 The Fifteen Negative Results In One Place

A reader should be able to see on one page every claim this project tested and did not get to make. Fifteen successor ideas were pre-registered and tested before or against the frozen model, and none beat it; Table (5.11) names each one, what it established and where its full output lives, and this section says what they have in common rather than walking through them. Three changed a design decision (1, 2, 3); four bounded what is reachable (5, 6, 7, 10); two removed an argument the thesis would otherwise have made (8, 11); two settled a specification question (4, 9); one produced the project's strongest positive finding by failing (12); one redrew the boundary of a contribution before it was written into the thesis (13); and the last two each bounded a component's claim — the risk layer's value is interpretive rather than discriminative (14), and word lists survive their obvious replacement (15). None was discovered after the fact: results 8 through 15 were pre-registered with grades fixed before execution; 7 records a criterion defect found on contact with the data and left unchanged (section 3.10); 12 records a label-rule defect found after its first output was seen, disclosed as such, with both results reported. A results chapter containing only successes is indistinguishable from one with the failures removed; the table is the evidence that this one is not, and a null that establishes nothing is a wasted experiment, which none of these is.

**Table (5.11) : Every claim tested and not made — the fifteen negative results, with the repository record of each. Fifteen claims were tested and not made; three changed a design decision, and none was a wasted experiment.**

{rows}
Two results need a sentence the others do not. Negative result 8 pairs with the visit-to-visit agreement of section 5.9.1: among controls that agreement is 0.465 — visits months to years apart, so it includes real change and is a lower bound on reliability — and a person whose own two recordings barely resemble each other offers a model little to memorise, so the null and the instability are the same fact measured two ways; the capacity limitation stops this being a claim about other people's work, since a tree ensemble over 64 aggregate features is not a transformer over raw text. Results 3 and 8 are kept apart deliberately, because only one of them found leakage — result 3 demonstrated a feature-level channel (age reconstructable at R² = 0.994), result 8 tested a fold-structure channel and found nothing (−0.0025) — and writing "leakage inflates results, as was shown" would collapse a demonstrated mechanism into an absent one.
""")

# ═════════ 5.9 (5.9.1 moves to 5.26) ═════════
out.append("\n" + section("5.9 Robustness"))

# ═════════ 5.10 + M2 ═════════
s = section("5.10 Arabic Evaluation")
out.append("\n" + s)
old5101 = section("5.10.1 The Referential")
t513 = table(old5101, "**Table (5.13)")
out.append(f"""
### 5.10.1 The Referential Deficit Index Probed In English

The Arabic instrument replaces the English pronoun-overuse marker with a referential deficit index — demonstratives and vague nouns relative to specific naming — because Arabic is pro-drop (section 3.4). The index is a candidate replacement whose behaviour was measured in English, where the components exist and 987 labelled recordings are on disk; within the literature identified by this search it had not previously been computed on the speech of a diagnosed patient in any language, and it cannot yet be tested in Arabic. The test was pre-registered with its provenance check — the recomputed pronoun-to-noun ratio reproduces the committed feature on 100% of recordings — and Table (5.13) reports the three measures (`results/reconstruction/rdi_english_probe.json`).

{t513}
The pre-registered grades: PRIMARY, PARTIAL — the pronoun-free index discriminates on Pittsburgh, improves to 0.625 under age and sex matching so it is not an age artefact, and fails on Delaware; SECONDARY, NEUTRAL — adding demonstratives and vague nouns to the established marker neither helps nor hurts; TERTIARY — the pronoun-free and established measures correlate 0.556 to 0.631 within class, so they read the same construct. The comparison that must accompany the PARTIAL grade: the established pronoun marker also fails on Delaware (0.551, spanning chance), so the Delaware failure is a property of that cohort's target, not a defect of the new measure. The probe fixes a falsifiable expectation for an Arabic dementia sample — the pronoun-free form is a lossy substitute in English, 0.596 against 0.656, so the prediction is an AUC near 0.6, not near 0.8 — and it found a defect in the Arabic engine: matching demonstratives by bare string match drops Delaware to exactly chance (0.5005 against 0.535) because existential and complementiser uses are noise, and the Arabic word هناك does the same double duty, a limitation recorded against the engine, which cannot filter those uses without an offline Arabic parser. This is construct evidence in English only, and it does not validate the Arabic index.

Off the picture the index does not travel. Pre-registered on the same 288 participants as section 5.25, with the sanity gate passed on all five tasks, the pronoun-free index clears chance on none of the five Delaware tasks (0.535, 0.489, 0.570, 0.498, 0.460), the genre contrast includes zero (−0.0523 [−0.1098, +0.0054]), and the grade is RDI-DOES-NOT-TRAVEL, negative result 13 (`results/reconstruction/rdi_cross_task_probe.json`); the established English pronoun marker is equally silent on all five. The task change is not what breaks the index; the target change is: its only positive evidence is the dementia cohort, and in English the construct carries weak signal for dementia and none detectable for mild impairment on any task. What carries the mild-impairment signal on discourse instead, over the same 43 shared features, is volume and structure — word count is the single strongest feature at 0.631 against 0.554 on picture description, with sentence count, lexical richness, dependency distance, semantic dispersion and reformulation behind it — a coherent clinical picture of reduced output, thinner lexis, simpler syntax and weaker semantic progression, and the opposite of what the index was designed to catch. One protocol requirement follows: if word count is the strongest single marker, any protocol that lets elicitation time vary is measuring examiner behaviour, so the successor fixes the prompt, the maximum duration and the re-prompt rule, and records elicitation time (Appendix B).

Whether the stage dissociation was already known was searched. A systematic review and meta-analysis of 54 studies pools speech-based detection of mild cognitive impairment at 0.78 [0.70, 0.86], names lexical diversity, syntactic complexity, acoustic properties and semantic content as the informative domains — the families found moving on discourse above — and does not isolate referential measures at all [9]; where referential measures have been tested head-on they have not separated even dementia [10]; and the strongest apparent counter-case, pronoun-use differences a decade before diagnosis in six later-diagnosed cases against six matched controls, is a group-level finding whose authors state that it does not support individual-level discrimination [11]. The reviews' silence is absence of evidence; this probe is evidence of absence, resting on one corpus, one target, n = 288. The index remains a defensible candidate dementia marker on picture description; it is not supported as a mild-impairment marker; and Chapter 6 splits the specification by target rather than pretending one instrument serves both.
""")

# ═════════ 5.11 ═════════
s = section("5.11 Predictive Values")
s = sub1(s, " Figure (5.7) draws both curves against prevalence.", " The full curves against prevalence are in the repository (`results/reconstruction/metric_suite_participant_ci.json`).")
s = sub1(s, "\n**Figure (5.7) : Positive and negative predictive value against assumed prevalence at the deployed threshold.**\n", "")
out.append("\n" + s)

# ═════════ 5.12 + 5.12.1 folded ═════════
s = section("5.12 Transfer Between Corpora")
s = sub1(s, "Table (5.15) reports both directions with their within-corpus references.", "Table (5.15) reports both directions with their within-corpus references (`results/reconstruction/cross_corpus_transfer.json`).")
out.append("\n" + s)
out.append("""
### 5.12.1 Delaware Cannot Be Learned From Itself

Trained on Delaware alone and validated within Delaware, the same architecture reaches 0.547 [0.485, 0.605] — an interval spanning chance — while a model trained on Pittsburgh reaches 0.646 on the same cohort. The foreign model beats the native one, so within this cohort connected-speech features carry no reliably learnable signal separating mild cognitive impairment from healthy ageing: a substantive negative claim about the reach of the whole method, and one that qualifies the project's central premise. Four explanations were candidates — intrinsic difficulty of the mild target, whose speech sits close to healthy; training-set size; instability of the MCI label itself, since a pooled analysis reports 15% reversion to normal across clinic and community samples, so a fraction of the labels belong to people who are or will become cognitively normal [6]; and task administration, the mechanism section 5.19 documents on the external corpus. Size was tested and ruled out: Pittsburgh subsampled by participant to Delaware's exact recording count and re-run under the identical within-cohort protocol over three seeds gives a mean of 0.8083 against 0.8137 for full Pittsburgh, grade SIZE-RULED-OUT (`results/reconstruction/pitt_subsample_probe.json`). Three explanations remain live and this design cannot separate them; the finding is not to be softened into "MCI is harder" — it is stronger and stranger than that, and it is why the task-genre result of section 5.25 matters. The original pre-lock pooling comparison asked whether adding Delaware improves generalisation to an unseen corpus, which now needs a third two-class corpus that no longer exists; this is a weaker proposition and is not presented as a reproduction of it.
""")

# ═════════ 5.13 The Operating Point (M1) ═════════
old513 = section("5.13 Threshold Transportability"); t516 = table(old513, "**Table (5.16)")
old514 = section("5.14 Recalibration"); t517 = table(old514, "**Table (5.17)")
old518 = section("5.18 Control Referenced"); t518 = table(old518, "**Table (5.18)"); t519 = table(old518, "**Table (5.19)")
old519 = section("5.19 The False Positives"); t520 = table(old519, "**Table (5.20)"); t521 = table(old519, "**Table (5.21)")
old523 = section("5.23 A Minimum Length"); t524 = table(old523, "**Table (5.24)")
fig511 = "**Figure (5.11) : Specificity delivered to target in all three cohorts under control-referenced thresholding; sensitivity is the variable quantity.**\n"
out.append(f"""
## 5.13 The Operating Point

The model is frozen and its threshold, 0.367, stands throughout this section, which reads the stored predictions as data and asks one question in three parts: why the pre-specified threshold did not transport, which part of the specificity problem a threshold can address at all, and what rule recovers specificity where it can be recovered. The answer is the chapter's principal methodological result, and its status is fixed once, here: control-referenced thresholding is a post-hoc analysis on a frozen model — not pre-registered, not deployed, not what produced the primary result of section 5.3 — and it requires prospective validation, which the pilot of Appendix B is designed to supply. Every figure in the section comes from the stored predictions read descriptively (`results/reconstruction/threshold_transportability.json`, `relative_threshold_rules.json`); nothing was re-scored and no decision followed.

### 5.13.1 The Threshold Does Not Transport

One number cannot serve three cohorts, and the single most important line in Table (5.16) says why: Delaware's impaired mean (0.409) is indistinguishable from Pittsburgh's healthy mean (0.406) and below the external cohort's healthy mean (0.471). The three cohorts do not share a score scale, so one cut-point cannot mean the same thing in all three: at the deployed threshold sensitivity runs 0.856, 0.569 and 0.962 across them, and the Delaware figure does not reach the 0.75 floor the threshold was chosen to satisfy on the pooled set. Forcing a single global threshold makes it worse — a joint rule requiring 75% sensitivity in every cohort lands at 0.286 and keeps only 18.5% worst-case specificity, and in 48.2% of bootstrap resamples at an 0.85 floor no threshold satisfies the floor everywhere — while the three cohorts, allowed to choose alone at a 0.75 floor, pick 0.510, 0.291 and 0.607, a spread of 0.32 on a unit scale that is structural rather than noise. Per-deployment threshold setting on local data is therefore a requirement of the method, not a refinement of it.

{t516}
The companion question — whether one calibration map can serve three cohorts — has the same answer, measured. A single logistic recalibration fitted on the pooled development predictions (slope 1.2887, intercept 0.1376; the external corpus played no part in the fit) improves Pittsburgh, worsens Delaware on the very data the map was fitted on, and on the external corpus improves the slope while worsening the intercept and the Brier score, as Table (5.17) reports; the mechanism is section 5.4.1's finding again, two development cohorts miscalibrated in opposite directions, and discrimination is unchanged everywhere, as a monotone transformation requires (section 3.11). Both the threshold and the calibration map are local quantities, which is the empirical case for the staged deployment design of Chapter 6. Rules that read only the target cohort's unlabelled score distribution — percentile, mean-matching, z-normalisation, quantile mapping — are diagnostics, not candidates: mean-matching collapses exactly where prevalence differs most (transported from Pittsburgh to Delaware at a 90% sensitivity target it lands at 99.4% sensitivity and 1.1% specificity, the worst cell in the grid), because it treats a prevalence difference as a calibration difference; and a percentile rule is arithmetically identical to fixing the referral rate, which transported acceptably here only because the external cohort's prevalence sits within two points of development's — in a Libyan community clinic at 5% to 15% prevalence it would refer over half of everyone.

{t517}
### 5.13.2 Two Specificity Problems Not One

The external corpus has a threshold problem: 33.3% specificity against a 77.8% ceiling, the most any threshold could deliver at 75% sensitivity, so roughly 44 points of achievable specificity were left untaken because that cohort's scores sit higher than development's. Delaware has a discrimination problem: at AUC 0.629 its ceiling at the same sensitivity is 0.376, so no threshold rule of any kind can help it (Pittsburgh's ceiling is 0.770). The division fixes which cohort each remedy can apply to, and nothing that follows rescues Delaware. The transported rules were not inefficient — they landed in the wrong place. Scored by recovery fraction, the specificity a rule achieved divided by the cohort's ceiling at the sensitivity actually reached, the median across all eighty rule-by-target-by-direction cells is 0.981, with 58 of 80 at 0.93 or above and 0.989 on the Lu-free development directions; a fixed threshold set for 75% sensitivity on Pittsburgh lands at 88.5% sensitivity on the external cohort, the percentile rule at 80.8%, mean-matching at 84.6%, so specificity was spent on sensitivity nobody asked for, and the 22 cells below 0.93 are all overshoot cells at the far-left edge of the curve — failures of placement, not of efficiency.

The false positives were also real. The eighteen external controls the fixed threshold misclassified, compared descriptively against the nine it cleared, had described the picture less well: Table (5.20) gives the continuous measures with Hedges' g and its interval, because with eighteen against nine a bare standardised difference overstates what is known, and Table (5.21) the binary content items with an exact test. The multiplicity position is stated rather than left to be found: no single comparison among the 64 screened features survives Bonferroni correction, only the falling stool survives a false-discovery correction among the binary items, and the age difference does not reach significance at n = 27, so the argument rests on the coherence of the pattern — sixteen of 64 features at an absolute effect of 0.8 or more, against roughly three expected under a null, all pointing toward thinner description — and on the descriptive facts, 11.5 units against 14.9 and 44% mentioning the falling stool against 100%, which are not in dispute. Four things follow: the model was not malfunctioning, since these transcripts carry the signature it was trained to find; no threshold rule can repair it, because the eighteen sit inside the impaired distribution on the features themselves; the most likely cause is task administration — a control who misses the scene's central event reads most simply as someone who stopped early — stated as a hypothesis with the 8.4-year age confound named beside it; and it is testable in the pilot, prospectively, by fixing the prompt and probing rule and recording elicitation time (Appendix B).

{t520}
{t521}
A validity rule on transcript length was the obvious remedy, and it was pre-registered and refused. The 215 development controls above the fixed threshold differ from the 307 correctly passed almost entirely in brevity — 103.2 words against 127.4, information-unit total 11.89 against 16.11 — while age and cognitive score are near-identical, so declaring short recordings non-reportable, as standard instruments carry validity criteria, would change no model, feature or threshold. Table (5.24) shows why the grade is GATE-NOT-JUSTIFIED, negative result 10: gates that keep enough of the sample buy almost nothing, the gate that buys most discards 44% of controls and 49% of the impaired for +0.069 specificity and −0.058 sensitivity, the AUC never leaves 0.739 to 0.757, and the equity co-criterion passed — the rule simply does not work. Brevity in a healthy speaker is signal the model is right to weigh, and the specificity ceiling is intrinsic to a sixty-second picture description rather than an artefact of inadequate sampling, which redirects the remedy from data collection to task design (section 5.25). This probe cannot be externally validated, since testing it on the spent corpus would be a second evaluation — the third occasion on which the lock rule has cost the project a result, after the recalibration decision of section 5.4.1 and the feature set frozen before it was complete.

{t524}
### 5.13.3 Control Referenced Thresholding Recovers Specificity

The rule that does transport reads labels from nobody: set the threshold at a fixed percentile of the local healthy-control score distribution. Table (5.18) and Figure (5.11) show the result at an 80% specificity target — specificity is delivered to target in all three cohorts, to within two points, and what varies is sensitivity, exactly as the AUCs predict. Specificity becomes a design parameter that is set, sensitivity becomes the measured, reported quantity, and Delaware's 0.356 is the discrimination problem of section 5.15 reappearing in the only place it can, not a failure of the rule. On the external corpus the bootstrap gives specificity 0.774 [0.69, 0.80], strikingly tight, against sensitivity 0.769 [0.44, 0.96], loose because 26 impaired recordings cannot pin it down; the tight interval is an in-sample quantity, since the same 27 controls defined the threshold and were scored against it. The prospective quantity has an exact, distribution-free answer: with the threshold at the k-th order statistic of n controls, prospective specificity follows a Beta(k, n+1−k) law, which for 27 controls gives 0.786 [0.62, 0.91] — the number a clinician actually cares about — and Table (5.19) turns that law into the pilot's sample-size justification: a ±10-point interval needs about 59 healthy speakers, ±7.5 points about 108 (`results/reconstruction/control_threshold_precision.json`). The assumption the pilot will not fully satisfy is stated with its direction: the law assumes the control sample is drawn from the population the threshold will serve, and a healthier-than-typical convenience sample sets the threshold too low, which over-refers; that error direction favours sensitivity over missed cases, but excess false positives remain an equity, anxiety and resource-use concern.

{t518}
{fig511}
{t519}
Three properties order the argument. The rule is prevalence-independent by construction, where every marginal rule of section 5.17 is implicitly a referral-rate rule. It makes specificity the fixed quantity and sensitivity the reported variable. And it needs a normative sample, not patients — a materially cheaper and more ethically tractable collection problem, and one the Libyan pilot already performs: its healthy arm is exactly this normative sample, so the study that validates the Arabic feature set is the study that supplies the threshold. The reported form follows from the same distributions. Band edges from the development distribution alone (tertiles at 0.334 and 0.533) produce an impairment rate that rises monotonically across bands in every cohort, which a binary flag cannot show, and band occupancy that differs sharply between cohorts — the external cohort's low band contains no impaired speaker at all, Pittsburgh's contains 21% — so banded reporting is the recommended primary presentation, with the reliability argument of section 5.26.1 behind it. Decision-curve analysis shows positive net benefit across the clinically relevant range in all three cohorts at their own prevalence, 36% to 56% impaired, which is not the deployment setting; recomputed at assumed community prevalences of 5%, 10% and 15% the curves remain positive but assume the operating characteristics transport, which section 5.13 shows they do not, so they are read as an upper bound [7]. None of this is deployed: it is the specified successor's operating rule, and the deployed instrument's threshold remains 0.367.
""")

# ═════════ 5.24/5.26 → M3 (with 5.9.1) ═════════
out.append("""
## 5.24 Repeat Recordings And Decision Reproducibility

Everything from here to section 5.30 is specified-successor material: development-set evidence for the next iteration, none of it externally validated, none of it able to become so — the corpus that would validate it is spent — and none of it shares a table with a validated figure, under the rule of section 1.7.

No clinical instrument should be proposed without its measurement error, and this one's was computed from the corpus's own structure: controls recorded at successive annual visits should not change, so their between-visit score movement estimates the instrument's noise. Among control pairs with gaps up to 1.5 years (123 pairs) the standard error of measurement is 0.103 and the minimal detectable change at 95% confidence is 0.286 (`results/reconstruction/instrument_properties.json`). On a zero-to-one score with the deployed threshold at 0.367, a person's score can cross the threshold and move two reported bands with nothing about them having changed: this is a screening test and not a monitoring test, and 0.286 is the number that establishes it. Impaired participants' scores rise +0.045 per visit (113 pairs) while controls' do not move, so progression is visible in aggregate and not in an individual; the estimate is an upper bound on the deployed error, since the two visits were scored by different fold models and a median gap of a year puts genuine change inside it. Visit-to-visit agreement among controls is 0.465, labelled exactly that — not test–retest reliability — and it is the conservative quantity behind both this section and negative result 8.

Averaging repeat recordings buys less than it appears to. Participant-level discrimination rises from 0.7643 at the first visit to 0.8467 when every visit is averaged, but the decomposition is negative result 11: averaging controls alone, who cannot progress, isolates pure noise reduction and is worth +0.0076, while averaging the impaired alone is worth +0.0565, seven times more, and the Spearman–Brown prediction from an agreement of 0.465 at 2.73 visits per participant (0.8122) falls short of the observed 0.8467 by +0.0345 — the gain is mostly the disease, not the instrument, which forbids describing the span as a measurement-precision result anywhere in this thesis. Men gain more from averaging (+0.0915 against +0.0764) but the sex gap closes only from 0.2346 to 0.2196, so repeat averaging is not the fairness fix. Averaging k recordings does cut measurement error by root-k in principle — the minimal detectable change falls to 0.202 at two recordings and 0.090 at ten — but root-k assumes independent errors, two recordings minutes apart share the room and the speaker's day, and with error correlation of 0.2 to 0.6 the two-recording figure is 0.222 to 0.256; and it does not make individual tracking viable, since the impaired group drifts +0.0372 per year and detecting one year of average progression would need the error of 59 averaged recordings. At the fixed threshold averaging also shifts the whole distribution upward (specificity 0.533 to 0.446, sensitivity 0.797 to 0.920), so a repeat protocol needs its threshold re-derived — which control-referenced thresholding does automatically, since a percentile of averaged controls is still a percentile.

### 5.26.1 Decision Reproducibility Is A Contribution

The probability that a fresh recording falls on the same side of the threshold as the first is 0.8355 — one screening decision in six would reverse on a repeat recording — rising to 0.8759 for the mean of two; within one standard error of the threshold it is 0.669, and outside that band 0.954 (`results/reconstruction/repeat_sampling_analysis.json`). Within the speech-based screening literature identified by this search that quantity appears not to be reported, and the strongest available counter-case confirms the gap: a study of remote speech assessment in fifty cognitively unimpaired adults, retested at two to three weeks, reports feature-level intraclass correlations from −0.06 to 0.97 and leaves open whether feature-level associations translate into stable classification decisions [8]. That open question is the one this figure answers, at the level of the thing the instrument actually outputs; a field that reports accuracy above 90% routinely and reliability almost never is a field whose accuracy figures have an unmeasured denominator, and naming the quantity, giving the method — any study with repeat recordings can compute it — and supplying one worked value is the contribution. It is also the reason the three-band report exists: at the recommended half-width of half a standard error the band declines to call 23.7% of cases, raises sensitivity among the rest by +0.052 for −0.012 of specificity, and lifts decision reproducibility to 0.911; a second recording is offered for indeterminate results only, since repeating everyone spends 100% of the sessions for +0.040 of reproducibility while repeating the grey zone spends 42% for 56% of that benefit; no repeat protocol is offered for monitoring; and the band is defined against the local control-referenced threshold, so it travels with the rule of section 5.18.
""")

# ═════════ 5.25 Which Task And How Many (trimmed) ═════════
old525 = section("5.25 Which Task"); t525 = table(old525, "**Table (5.25)")
fig514 = between(old525, "**Figure (5.14)").split("\n")[0] + "\n"
out.append(f"""
## 5.25 Which Task And How Many

This section is the attack on the project's weakest number. Delaware sits at 0.629 pooled and 0.547 within-corpus, and the one lever that does not touch the deployed model is the task itself: which task the instrument should be reading, and how many are worth administering. The probe was pre-registered with its amendments recorded, the third disclosed as post-result; the design holds the 288 participants with all five Delaware tasks at their earliest common visit with that visit's label, uses the 43 features shared by all five task extractors, and combines tasks by averaging predicted scores so that no subset carries more columns than another — the two corrections that negative result 12's predecessor lacked (section 5.6). Table (5.25) reports the task-count curve and the single-task ranking together, and Figure (5.14) draws the genre separation (`results/reconstruction/task_count_curve.json`).

{t525}
{fig514}
The finding is the genre separation, and the partition was declared from the corpus protocol before the contrast was computed: the two connected-discourse tasks occupy the top two places and the three picture tasks the bottom three, with no overlap. The battery contrast answers the design question, because a clinic administers a set of tasks rather than a mean of AUCs: two discourse tasks administered together beat three picture tasks together by +0.0788 [+0.0042, +0.1579], while the mean-AUC genre contrast (+0.0518 [−0.0014, +0.1062]) includes zero and is said to. The paired contrasts that survive both label conventions are the citable core: procedure beats the standard picture by +0.1010 [+0.0192, +0.1847], story retelling by +0.0938 [+0.0106, +0.1739], the two together by +0.1319 [+0.0541, +0.2147] — for detecting mild impairment, the standard picture task is the worst of the five and performs at chance. The registered outcomes are BATTERY-NOT-CONFIRMED (five tasks against the best single task: +0.0102 [−0.0579, +0.0818], saturation at one to two tasks) and COOKIE-DISPENSABLE (the best subset contains no picture task).

What must not be claimed travels with the finding. It says nothing about the picture task for dementia, where it works and where the external evaluation stands; the named best pair is selected in-sample and is an upper-bound claim, while what is robust is that the picture task is worst, its own interval includes chance, and both discourse tasks beat it with intervals excluding zero; the claim that adding the picture task actively degrades a battery does not survive the corrected label rule and is not made; and 18 of the 288 participants (6.25%) change label across visits, including reversion, which places a ceiling on any classifier evaluated against these labels [6]. The reframing is the contribution: Delaware's weakness has been written up as a limitation of the model, and it is substantially a limitation of the task — picture description was never chosen on evidence, because the training corpus allowed nothing else, and this is the measurement of what that constraint cost. The design consequence is a requirement: a screening battery aimed at mild impairment administers a narrative retelling and a procedural-discourse task, picture description earns its place only for the dementia target, and two tasks are enough. The deployed battery order of section 4.2 follows it; what is scored does not change, for the reason the code states.
""")

# ═════════ 5.30 Further Successor Probes (M4) ═════════
out.append("""
## 5.30 Further Successor Probes

Five further probes belong to the specified successor and are reported at the length their results warrant; each has a row in Table (5.11) with its grade and its repository record, and none changes what the frozen model can claim.

**Domain shift and the pruning remedy that failed (negative result 7).** The shift between the two development cohorts' controls is small on the deployed features — median absolute standardised difference 0.22, six features above 0.5, none at 0.8 — because the 0.930 corpus-separability figure of section 3.2.1 was measured with transcription markup that the deployed 64 exclude. Removing the most-shifted features and retraining throwaway transfer models made the direction that matters, toward the mild-impairment cohort, worse at every k (0.6460 with all features; 0.6424, 0.6421 and 0.6434 with 5, 10 and 15 removed), while the opposite direction's +0.014 is not claimable because the shift ranking used both cohorts' controls and so saw the target: a remedy aimed at a 0.22 median shift has almost nothing to work on, and drops useful signal with it.

**Information efficiency does not beat information count (negative result 9).** If impaired speakers produced fewer information units per word rather than simply fewer, density would beat the raw count and the paper fallback would get stronger; measured single-feature and directed on the development set, density reaches 0.6031 against the count's 0.7096, a paired participant-clustered difference of −0.1074 [−0.1673, −0.0464] with no resample favouring density. The count is strong and sex-unequal (gap +0.083), density weak and sex-fair (+0.006), and raw word count nearly uninformative (0.5552), so the sex gap of section 5.2.1 lives in the information-content effect itself, not in verbosity, and the paper fallback stays a count. The dynamic variants — time to first unit, units by thirty seconds, retrieval slope — are unmeasurable, because the corpus the whole field trains on carries no word-level timings. A redundancy found on the way: the proportion feature is the count divided by a constant, so the deployed set has 64 columns and 63 distinct quantities, left in place because the model is frozen (section 3.2.2).

**The minimal probe, and a claim withdrawn before it reached the thesis.** The first version of this analysis said that counting words ties the calibrated ensemble on mild-impairment discourse; that claim is withdrawn as a selection artefact, because word count was the argmax over 43 features on the same participants while the ensemble's architecture was fixed before the data were seen. Estimated alike — the best single feature chosen inside each training fold and scored on the held-out fold — the fair comparator is 0.6018 against the ensemble's 0.6379, a selection optimism of +0.0455, so the apparatus buys +0.0361 on this target (section 6.1; `results/reconstruction/selection_optimism.json`); word count remains the right hand-computable measure on discourse, its true value lies between about 0.60 and 0.647, and the successor's power calculation runs on the conservative end.

**The age-adjusted posterior and discrimination (negative result 14).** The risk layer's output had never been scored for discrimination, and the invariance result of section 3.11 does not dispose of the question because the posterior is monotone in the score only at fixed age. On the combined development set the age-adjusted posterior gains +0.0163 [−0.0127, +0.0446] over the raw score, ADJUSTMENT-NEUTRAL; Pittsburgh's apparent gain of +0.0356 [+0.0035, +0.0694] is not a gain, because its dementia group is 6.6 years older than its controls by construction and under age matching the gain reverses to −0.0346. The layer's value is interpretive, not discriminative — converting a screening score into an age-appropriate absolute risk is a calibration job, which is what it was built for — and family history could not be tested at all, since no corpus in this project records it, so that multiplier rests on published relative risks.

**Vector matching for information units (negative result 15).** Whether word-vector similarity could loosen the scorer's too-tight lists (section 5.5.1) was tested at nine declared thresholds against the twenty hand-scored transcripts: the word-list baseline has a mean absolute difference of 0.550 with 7 false credits, and every vector threshold inflates false credits by an order of magnitude — 74 at the best threshold, 144 at the loosest — grade VECTORS-HURT. Static vectors encode topical relatedness, not synonymy, and everything in a picture description is topically related to everything else, so no cut-off separates a synonym from a co-occurring object; a larger static model fails the same way, and contextual judgement needs a runtime this deployment target does not have. The undercount lives in the six action units, which contribute nearly half the misses from a quarter of the units, so the remedy is better lists and a dependency-aware action rule, neither deployable without changing the frozen model.
""")

text = "".join(out).replace("\n\n\n", "\n\n") + tail
open(DST, "w", encoding="utf-8").write(text)
words = len(re.findall(r"\S+", re.sub(r"\|", " ", text.split("**References Cited")[0])))
print("chapter5.md written:", words, "words (incl. tables)")
