#!/usr/bin/env python3
"""cut_ch4.py -- Chapter 4 trims: 4.1, 4.2, 4.3.1, 4.5, 4.6 (Table 4.4 does the work); 4.5.1 untouched."""
import re
P = "/home/claude/work/src/docs/chapters/chapter4.md"
t = open(P, encoding="utf-8").read()
def sub1(old, new):
    global t
    assert t.count(old) == 1, (old[:70], t.count(old)); t = t.replace(old, new)

# preamble
sub1("Section 4.3.1 examines the one assumption in the deployed pipeline that could not remain unexamined — the picture the system shows is not the picture the model was fitted on — section 4.5.1 states the property both of this chapter's defects shared — neither announced itself — and section 4.6 closes the chapter with a one-page summary of every verification the system as built received.",
     "Section 4.3.1 examines the one assumption in the deployed pipeline that could not remain unexamined — the picture the system shows is not the picture the model was fitted on — and section 4.6 closes the chapter with a one-page summary of every verification the system as built received.")

# 4.1
sub1("Automatic transcription is used when the recogniser's weights are present; when they are not — they must be downloaded once, which the target setting cannot assume — the platform does not fail and does not invent text but asks the operator to type the transcript, which is how the reference corpora themselves were produced. A missing network therefore costs convenience, never validity, and a missing model bundle still leaves a working platform that reports an indicator profile and never claims a screening score it cannot justify.",
     "Automatic transcription is used when the recogniser's weights are present; when they are not, the platform does not invent text but asks the operator to type the transcript, which is how the reference corpora themselves were produced, so a missing network costs convenience, never validity, and a missing model bundle still leaves a working platform that reports an indicator profile and never claims a screening score it cannot justify.")
sub1("Figure (4.2) shows what feeds it. Dhikra extracts 117 speech and language measures across five families. Its externally evaluated English screening model uses a frozen 64-feature transcript-derived subset of linguistic, information-content and discourse-semantic measures; 53 acoustic measures support a separate language-independent pathway. Of the 117 measures extracted per session, the 64 language measures — 31 information-unit, 24 lexical and syntactic, 9 semantic-coherence — form the screening model's input, while the 53 acoustic measures feed a separate language-independent model that never enters the screening score. As section 3.3 records, the reduction to 64 is not a selection on performance but the set computable from a transcript alone — the property that makes the paper fallback examined in Chapter 5 possible.",
     "Figure (4.2) shows what feeds it. Dhikra extracts 117 speech and language measures across five families. Its externally evaluated English screening model uses a frozen 64-feature transcript-derived subset of linguistic, information-content and discourse-semantic measures — 31 information-unit, 24 lexical and syntactic, 9 semantic-coherence — and 53 acoustic measures support a separate language-independent pathway that never enters the screening score. As section 3.3 records, the reduction to 64 is not a selection on performance but the set computable from a transcript alone, the property that makes the paper fallback examined in Chapter 5 possible.")

# 4.2
sub1("Each task has a published basis, recorded so the battery is an argument rather than a habit: delayed story recall probes the earliest-declining domain and predicts progression from mild impairment to dementia, with the examiner-supplied story a project-authored instrument in that paradigm rather than a normed test [3]; sixty-second animal fluency is the standard batteries' own form, with age- and education-stratified norms [4, 5]; and the recitation probe rests on the documented survival of early-acquired, long-rehearsed material — musical memory is the strongest published analogue — while the task itself is validated nowhere, is framed as exploratory with six documented confounders, and its practical properties are design arguments, not evidence [6]. Procedural discourse alone entered on this project's own measurement, reported in section 5.25; its prompt asks for tea-making rather than the source corpus's sandwich because tea-making is culturally universal in the deployment setting.",
     "Each task has a published basis: delayed story recall probes the earliest-declining domain and predicts progression from mild impairment to dementia, with the examiner-supplied story a project-authored instrument in that paradigm rather than a normed test [3]; sixty-second animal fluency is the standard batteries' own form, with age- and education-stratified norms [4, 5]; and the recitation probe rests on the documented survival of early-acquired, long-rehearsed material, musical memory being the strongest published analogue, while the task itself is validated nowhere and is framed as exploratory [6]. Procedural discourse alone entered on this project's own measurement (section 5.25); its prompt asks for tea-making rather than the source corpus's sandwich because tea-making is culturally universal in the deployment setting.")
sub1("The report repeats the same fact to the operator in plain language, naming the discourse tasks as administered first, recorded, and contributing nothing to the result.\n\nRepeat visits do not reuse material: selection from the three matched pictures, three twelve-proposition stories and the surah bank rotates deterministically from participant code and session number, so a repeat visit receives a different form while any session reproduces exactly from its recorded stimulus identifiers. The first English visit is the exception — the validated scene is shown by default, because rotating away from it would trade a calibrated result for protection against a practice effect that cannot yet exist. Fluency and story recall are shown to the operator as clinical context and excluded from the screening decision, because the training corpus contains them for the dementia group only, with no healthy controls from which a threshold could have been learned.",
     "The report repeats the same fact to the operator in plain language. Repeat visits do not reuse material: selection from the three matched pictures, three twelve-proposition stories and the surah bank rotates deterministically from participant code and session number, so a repeat visit receives a different form while any session reproduces exactly from its recorded stimulus identifiers; the first English visit is the exception, since the validated scene is shown by default. Fluency and story recall are shown to the operator as clinical context and excluded from the screening decision, because the training corpus contains them for the dementia group only.")

# 4.3.1
sub1("Substituting a stimulus while keeping a model fitted on the original was the single largest unexamined assumption in the deployed pipeline, and it was examined [7, 8, 9].\n\nWhat inspection found is recorded first. Rendering the artwork and reading the key unit by unit showed that two of the 23 — the curtain and the dishcloth — were not depicted at all: no speaker, however intact, could earn them. Three more — the tap, the running water and the overflow — were drawn but occluded by the standing figure. Both faults were in the artwork; both were corrected the same day; and no participant data existed to be invalidated. Every figure in Chapters 3 and 5 was computed on transcripts of the real Cookie Theft and is unaffected by this defect.",
     "Substituting a stimulus while keeping a model fitted on the original was the single largest unexamined assumption in the deployed pipeline, and it was examined [7, 8, 9]. Rendering the artwork and reading the key unit by unit showed that two of the 23 — the curtain and the dishcloth — were not depicted at all, and three more — the tap, the running water and the overflow — were occluded by the standing figure; both faults were in the artwork, both were corrected, and no participant data existed to be invalidated. Every figure in Chapters 3 and 5 was computed on transcripts of the real Cookie Theft and is unaffected.")
sub1("What cannot be corrected is the other half. The scene contains salient content with no slot in the key — a cat, a teapot, a stove, bread, a table, a palm tree. The key cannot be extended to credit them, because the key computes the model's input and the model is frozen: adding a unit would change the information-unit features of every training transcript and void the calibration. The only possible effect of the unscored content is behavioural — attention spent naming what earns nothing is attention not spent naming what the scorer counts — and its magnitude on real speakers is unknowable without Libyan data. The pre-registered analysis therefore asked the inverse question: how many units would the substitution have to cost a speaker before the screening decision changes? Table (4.2) is the answer.",
     "What cannot be corrected is the other half. The scene contains salient content with no slot in the key — a cat, a teapot, a stove, bread, a table, a palm tree — and the key cannot be extended to credit them, because the key computes the model's input and the model is frozen. The only possible effect of the unscored content is behavioural — attention spent naming what earns nothing is attention not spent naming what the scorer counts — and its magnitude on real speakers is unknowable without Libyan data, so the pre-registered analysis asked the inverse question: how many units would the substitution have to cost a speaker before the screening decision changes? Table (4.2) is the answer.")
sub1("One displaced unit is enough to matter. Against a criterion fixed before execution — material if two displaced units move ten percent of controls across the threshold — the result graded DISPLACEMENT-MATERIAL from the first row. The result is in the direction the project did not want, and it is reported at full strength: whether the substituted picture costs real speakers anything is unknown, and cannot be known without Libyan data, which is why the pilot protocol carries a pre-specified stimulus-equivalence endpoint rather than a hope.\n\nOne diagnostic was declared post hoc and does not change the grade. The report already refuses a confident call within 0.1032 of the threshold, a band holding 45.3% of control recordings at baseline; 93.6% of the controls that cross at one displaced unit were already inside it, so the borderline caveat absorbs almost the whole small-displacement effect, leaving roughly two recordings per replicate moving from a confident negative to a positive. At six displaced units the protection fails — 46.1% — so the existing safeguard covers the likely case and not the worst one, which is why the substitution caveat of section 4.5 attaches to every score rather than to borderline ones.\n\nOne observation is recorded at exactly the weight it deserves: the author's impression, on viewing both scenes, is that this project's picture is harder to describe. That impression is n = 1, not blinded, and made by the person who commissioned the artwork — not evidence, and not written as evidence. It is recorded because it points the same way as the measurement, and because an impression written down before data arrive can be checked against them; the pilot's stimulus-equivalence endpoint is that check.\n\nFinally, this section must not be conflated with the scorer-agreement check of section 5.5.1, which asks a different question of different data: it compares a hand count with the software count on transcripts of the real Cookie Theft, measuring the lexical matching rule rather than the picture. The two act on the same quantity in opposite directions — a hand count runs about 1.5 units above the software, a substituted picture may cost a speaker units — but the offsets are not designed to cancel, have never been measured together, and nothing may be inferred from their opposite signs.",
     "One displaced unit is enough to matter: against a criterion fixed before execution — material if two displaced units move ten percent of controls across the threshold — the result graded DISPLACEMENT-MATERIAL from the first row, in the direction the project did not want. Whether the substituted picture costs real speakers anything is unknown and cannot be known without Libyan data, which is why the pilot protocol carries a pre-specified stimulus-equivalence endpoint. One post-hoc diagnostic does not change the grade: the report already refuses a confident call within 0.1032 of the threshold, a band holding 45.3% of control recordings at baseline, and 93.6% of the controls that cross at one displaced unit were already inside it, so the borderline caveat absorbs almost the whole small-displacement effect; at six displaced units the protection fails (46.1%), which is why the substitution caveat of section 4.5 attaches to every score rather than to borderline ones. This section must not be conflated with the scorer-agreement check of section 5.5.1, which measures the lexical matching rule on transcripts of the real Cookie Theft rather than the picture: a hand count runs about 1.5 units above the software and a substituted picture may cost a speaker units, but the offsets have never been measured together and nothing may be inferred from their opposite signs.")

# 4.5
sub1("The premise is stated in the quality module itself: a system that always returns a number is more dangerous than one that sometimes declines, because a score computed from ten seconds of mumbling in a noisy corridor is formatted exactly like a valid one.",
     "A system that always returns a number is more dangerous than one that sometimes declines, because a score computed from ten seconds of mumbling in a noisy corridor is formatted exactly like a valid one.")
sub1("The split in the basis column is deliberate. The noise thresholds and clipping tolerance derive from the degradation experiment of section 5.9 — the pipeline is robust to compression, an eight-kilohertz sampling rate, low volume and clipping, and broken by background noise — so the gate polices noise strictly and everything else loosely, the opposite of a generic audio check. The three minima were asserted, no experiment derives them, and the pilot's feasibility outcomes are the place to revisit them. A tool intended for a Libyan clinic must tolerate a cheap phone; it must not tolerate an open window onto a busy street.\n\nBeyond refusing, the system confesses. Every screening score from the validated picture is delivered alongside the statement that the picture is a substitute, with the measured consequence of section 4.3.1 attached — the system has no evidence that would justify withholding the score, and no evidence that would justify presenting it as though the substitution were free, so it says which of the two situations it is in. The caveat is quoted in full, because it is submitted text — the deployed system saying aloud what this chapter measured:",
     "The split in the basis column is deliberate: the noise thresholds and clipping tolerance derive from the degradation experiment of section 5.9, so the gate polices noise strictly and everything else loosely, the opposite of a generic audio check, while the three minima were asserted and the pilot's feasibility outcomes are the place to revisit them. Beyond refusing, the system confesses. Every screening score from the validated picture is delivered alongside the statement that the picture is a substitute, with the measured consequence of section 4.3.1 attached, because the system has no evidence that would justify withholding the score and none that would justify presenting it as though the substitution were free. The caveat is quoted in full, because it is submitted text:")
sub1("A second caveat appears whenever the word-vector model behind nine of the sixty-four features is absent from the machine, and it exists because of this chapter's second defect:",
     "A second caveat appears whenever the word-vector model behind nine of the sixty-four features is absent from the machine:")

# 4.6 — the table does the work
sub1("Table (4.4) collects on one page every verification activity the project performed on the system as built, with the method and the outcome of each. The sections and appendices named in the table own the detail; the table adds no result of its own, and it closes the chapter that describes the system so that a reader sees what was checked before reading what was measured.",
     "Table (4.4) collects on one page every verification activity the project performed on the system as built, with the method and the outcome of each; the sections and appendices named in the table own the detail, and the table adds no result of its own.")
for old, new in [
 ("| Architecture recovered by introspection of the deployed artefact under the pinned scikit-learn 1.8.0, no training script having been committed, and checked against seven pre-registered signatures of the locked outputs (section 3.9, Appendix C); the acoustic model's protocol confirmed by a pre-registered signature test (Appendix F) | 7 of 7 signatures matched; the acoustic model's embedded figure reproduces from a fresh fit by committed code |",
  "| Architecture recovered by introspection of the deployed artefact under the pinned scikit-learn 1.8.0, no training script having been committed, and checked against seven pre-registered signatures of the locked outputs (Appendix C) | 7 of 7 signatures matched; the acoustic model's embedded figure reproduces from a fresh fit by committed code (Appendix F) |"),
 ("| Eight controlled degradations applied to the recordings, each of nine acoustic measures correlated with its clean value (section 5.9) | Robust to compression, 8 kHz resampling, low volume, clipping and distance; pause measures degrade at 20 dB (worst correlation 0.59) and extraction fails at 10 dB, which sets the refusal threshold of Table (4.3) |",
  "| Eight controlled degradations applied to the recordings, each of nine acoustic measures correlated with its clean value (section 5.9) | Robust to compression, 8 kHz resampling, low volume, clipping and distance; pause measures degrade at 20 dB and extraction fails at 10 dB, which sets the refusal threshold of Table (4.3) |"),
 ("| The automated scorer against a human rater on 20 blind transcripts, graded against a pre-registered criterion of mean absolute difference ≤ 1.200 (section 5.5.1) | 1.600, grade INADEQUATE, reported first; the disagreement is a near-constant undercount of about 1.5 units with rank order preserved (ICC 0.904), which is why the AUC results survive and why the pilot's scoring rule binds (Appendix B) |",
  "| The automated scorer against a human rater on 20 blind transcripts, graded against a pre-registered criterion of mean absolute difference ≤ 1.200 (section 5.5.1) | 1.600, grade INADEQUATE; a near-constant undercount of about 1.5 units with rank order preserved (ICC 0.904), so the AUC results survive and the pilot's scoring rule binds (Appendix B) |"),
 ("| Controls at successive annual visits taken as the estimate of instrument noise (123 pairs, gaps up to 1.5 years), and the probability that a repeat recording lands on the same side of the threshold (sections 5.9.1 and 5.26.1) | Standard error of measurement 0.103 and minimal detectable change 0.286; decision reproducibility 0.8355, 0.669 within one standard error of the threshold and 0.954 outside it — the basis of the three-band report |",
  "| Controls at successive annual visits taken as the estimate of instrument noise (123 pairs), and the probability that a repeat recording lands on the same side of the threshold (section 5.26.1) | Standard error of measurement 0.103, minimal detectable change 0.286; decision reproducibility 0.8355, 0.669 near the threshold and 0.954 away from it — the basis of the three-band report |"),
 ("| The Bayesian chain evaluated over a 1,440-case grid — twelve ages, three contexts, five family-history states, eight speech scores — against nine registered properties (section 3.7, Appendix H) | 1,440 of 1,440 cases passed with zero failures; the relative-risk-as-odds defect at the oldest ages is disclosed, not patched (Appendix H) |",
  "| The Bayesian chain evaluated over a 1,440-case grid against nine registered properties (section 3.7, Appendix H) | 1,440 of 1,440 cases passed; the relative-risk-as-odds defect at the oldest ages is disclosed, not patched (Appendix H) |"),
 ("| Four refusal conditions enforced in code; the noise and clipping thresholds derived from the degradation experiment, the three minima asserted (section 4.5) | The passing path was exercised end to end by the demonstration session of Appendix E, every recording clearing the gate; the refusal branches themselves have no committed test, and that test is assigned to the pilot |",
  "| Four refusal conditions enforced in code; the noise and clipping thresholds derived from the degradation experiment, the three minima asserted (section 4.5) | The passing path was exercised end to end by the demonstration session of Appendix E; the refusal branches themselves have no committed test, and that test is assigned to the pilot |"),
 ("| At startup the platform reports whether the word-vector model behind nine of the sixty-four features is present, and every report names any feature substituted by a training average (section 4.5.1) | Implemented in the shipped code after the installer defect was found; the demonstration session's report carried the stimulus caveat only, so no feature was substituted in that run (Appendix E) |",
  "| At startup the platform reports whether the word-vector model behind nine features is present, and every report names any feature substituted by a training average (section 4.5.1) | Implemented after the installer defect was found; the demonstration session's report carried the stimulus caveat only, so no feature was substituted in that run (Appendix E) |"),
 ("| One execution on the external corpus at the threshold fixed in advance, under the governance of section 3.9, then reproduced once under a protocol permitting one execution and no decision (sections 3.9.2 and 5.3) | AUC 0.8533 [0.7371, 0.9458], sensitivity 96.2%, specificity 33.3%; the reproduction matched to ten decimal places and cell for cell, and a tombstone file blocks any further run; the specificity is diagnosed in sections 5.15 to 5.19 |",
  "| One execution on the external corpus at the threshold fixed in advance, under the governance of section 3.9, then reproduced once under a protocol permitting one execution and no decision (sections 3.9.1 and 5.3) | AUC 0.8533 [0.7371, 0.9458], sensitivity 96.2% and specificity at the pre-specified threshold diagnosed in section 5.13; the reproduction matched to ten decimal places and cell for cell, and a tombstone file blocks any further run |"),
]: sub1(old, new)

t = re.sub(r"\n{3,}", "\n\n", t)
open(P, "w", encoding="utf-8").write(t)
print("chapter4.md:", len(re.findall(r"\S+", re.sub(r"\|", " ", t.split("**References Cited")[0]))), "words")
