import re
P="/home/claude/work/src/docs/chapters/appendix_f.md"; t=open(P,encoding='utf-8').read()
def sub1(old,new):
    global t; assert t.count(old)==1,(old[:60],t.count(old)); t=t.replace(old,new)
sub1("This appendix grades every component of the project by the evidence behind it, so that an examiner can see what is externally validated, what is measured, what is reconstructed, what is only implemented and what is only specified, without having to work it out from six chapters. It is the register the thesis rule of section 1.7 exists to make possible: nothing in it is stated more strongly than its file supports, every figure is the canonical value of `docs/NUMBERS.md` or of the result file named in the chapter that owns it, and the registered grade words — CONFIRMED, NOT-CONFIRMED, RETRACTED, MATCH, CANNOT-CONFIRM and the rest — are reproduced as the result files record them. Where a figure appears in a chapter but in no result file, the register says so rather than repeating it.",
     "This appendix grades every component of the project by the evidence behind it, so that an examiner can see what is externally validated, what is measured, what is reconstructed, what is only implemented and what is only specified. Every figure is the canonical value of `docs/NUMBERS.md` or of the result file named in the chapter that owns it, the registered grade words are reproduced as the result files record them, and where a figure appears in a chapter but in no result file the register says so.")
# F.1: keep the seven definitions, shorten the framing
sub1("Seven levels are used, and they are defined by the procedure that produced the evidence rather than by its size, because in this project the procedure is what decides what a number means. Level A is external validation: a single evaluation, at a threshold fixed in advance, scored once, on a corpus whose exposure is stated in the canonical form (section 3.9): the corpus was excluded from the training data of the final model and from every modelling decision after the lock. Before the lock, five exploratory scorings occurred, one of which informed the decision to include Delaware in the development pool. Exactly one figure holds it, and its exposure history travels with it.",
     "Seven levels are used, defined by the procedure that produced the evidence rather than by its size. Level A is external validation: a single evaluation, at a threshold fixed in advance, scored once, on a corpus whose exposure is stated in the canonical form of section 3.9; exactly one figure holds it, and its exposure history travels with it.")
sub1("Three things follow from the table and are stated so that they are not left to be inferred. First, one figure in the project holds level A, and it holds it with an exposure history attached: 0.8533 [0.7371, 0.9458] validates the frozen English screening model on data absent from its training, and section 3.9 records the one earlier scoring that informed the pool from which that system was trained. Everything else the thesis reports about performance is development evidence, and the thesis says so wherever the figures appear. Second, the pre-registered grades are reported as the criteria produced them: of the level-B rows, the grades that went against the project — INADEQUATE, NOT-DEMONSTRATED, GATE-NOT-JUSTIFIED, ADJUSTMENT-NEUTRAL, VECTORS-HURT, RDI-DOES-NOT-TRAVEL, BATTERY-NOT-CONFIRMED, CORRECTION-DOES-NOT-TRANSFER, DISPLACEMENT-MATERIAL and one retraction — outnumber the ones that went for it, and section 5.8 collects them. Third, nothing in the Arabic arm rises above level D: the one measured Arabic figure is a feasibility probe whose interval spans chance, the engine is verified on constructed examples, and the specification and the protocol are documents. The instrument is English-validated, culturally adapted for Libyan validation, and not validated in Libya — which is the claim Chapter 6 makes, and the only one this register licenses.",
     "Three things follow from the table. First, one figure in the project holds level A, with an exposure history attached: 0.8533 [0.7371, 0.9458] validates the frozen English screening model on data absent from its training, and section 3.9 records the one earlier scoring that informed the pool from which it was trained; everything else the thesis reports about performance is development evidence. Second, the pre-registered grades are reported as the criteria produced them, and of the level-B rows the grades that went against the project outnumber the ones that went for it (section 5.8). Third, nothing in the Arabic arm rises above level D: the one measured Arabic figure is a feasibility probe whose interval spans chance, the engine is verified on constructed examples, and the specification and the protocol are documents. The frozen English screening model is externally evaluated, the instrument is culturally adapted for Libyan validation, and it is not validated in Libya — the claim Chapter 6 makes, and the only one this register licenses.")
t=re.sub(r"\n{3,}","\n\n",t); open(P,'w',encoding='utf-8').write(t)
print('F', len(re.findall(r"\S+", re.sub(r"\|", " ", t))), 'rows', sum(1 for l in t.split('\n') if l.startswith('| ') and not l.startswith('| Component')))
