import re
# ---- Chapter 2
P="/home/claude/work/src/docs/chapters/chapter2.md"; t=open(P,encoding='utf-8').read()
def sub1(old,new):
    global t; assert t.count(old)==1,(old[:60],t.count(old)); t=t.replace(old,new)
sub1("The two findings are not in conflict, and the reason is worth stating precisely because it generalises. Their model fine-tunes a contextual representation on raw text, which can absorb surface transcription-convention differences as incidental variation; this project's model reads hand-crafted count features, which are made of exactly the conventions that differ between transcription teams. Their outside data enters as training signal for a representation learner; here it would have entered the same feature matrix as the labelled corpora, where corpus identity is directly available to the classifier. And the class composition decides the matter: the Wisconsin corpus is 100% healthy speakers, so pooling it makes corpus membership nearly equivalent to class membership — this project measured two studies' healthy speakers as separable at AUC 0.930 on transcription convention alone (section 3.2.1) and derived the rule that corpora are combined only when each contributes both classes. The general form is that external normative data can help, and has been shown to; whether it helps a given model depends on whether its features can encode corpus identity and on whether the added corpus carries both classes. This project measured that for its own configuration, obtained a clear negative, and did not pool — and proposes the measurement itself as a routine pre-pooling check (section 6.1).",
     "The two findings are not in conflict. Their model fine-tunes a contextual representation on raw text, which can absorb transcription-convention differences as incidental variation; this project's model reads hand-crafted count features, which are made of exactly the conventions that differ between transcription teams, and the Wisconsin corpus is 100% healthy speakers, so pooling it makes corpus membership nearly equivalent to class membership — this project measured two studies' healthy speakers as separable at AUC 0.930 on transcription convention alone (section 3.2.1) and derived the rule that corpora are combined only when each contributes both classes. Whether external normative data helps a given model depends on whether its features can encode corpus identity and on whether the added corpus carries both classes; this project measured that for its own configuration, obtained a clear negative, did not pool, and proposes the measurement as a routine pre-pooling check (section 6.1).")
sub1("What this project can demonstrate is the feature-level version of the same hazard, on its own data: an age-residualisation technique scored 0.853 on development until the supposedly age-free features were tested and age proved recoverable from them at R² = 0.994, and the technique was discarded (section 5.8). That is a measured demonstration of what an evaluation shortcut can buy — a large, spurious, entirely internal gain — and it is the reason the comparison below rests on the column no shortcut can counterfeit. A model evaluated only within the corpus it was fitted on has produced no evidence about a patient from anywhere else. Most of this literature reports no external validation at all, and that difference, not any claim of error against any author, is the argument: the numbers answer different questions [8].",
     "What this project can demonstrate is the feature-level version of the same hazard, on its own data: an age-residualisation technique scored 0.853 on development until age proved recoverable from the supposedly age-free features at R² = 0.994, and the technique was discarded (section 5.8) — a measured demonstration of what an evaluation shortcut can buy, and the reason the comparison below rests on the column no shortcut can counterfeit. Most of this literature reports no external validation at all, and that difference, not any claim of error against any author, is the argument: the numbers answer different questions [8].")
sub1("Read fairly, the table places this work without flattery. Among subject-independent results the published range runs roughly 0.75 to 0.87 accuracy; the challenge baseline sits at 0.750 to 0.768, and the best comparable subject-independent figure on extended Pittsburgh material located by this review is 0.797, obtained with 1,476 features [10]. At 0.759 this project sits at the challenge baseline and about four accuracy points below that best comparable figure: a real gap, and a small one — not the fifteen points the 0.93 headline suggests, because that headline was produced under a protocol that is not subject-independent and was never tested outside its corpus [9]. One line in the table belongs to this work alone. On the locked external corpus the best accuracy any threshold could achieve is 0.792 — numerically the same figure the feature-selection study reports on the ADReSS held-out set — except that the external corpus was collected by different investigators, in a different setting, and was scored exactly once at a threshold fixed in advance [10]. No system in the table reports an external validation of any kind. A realistic target for a system evaluated the way this one is, on this material, is 0.80 to 0.85 accuracy under subject-independent validation; figures above 0.90 are reached only by protocols that are not subject-independent, or by transformers, or both, and 0.93 is not the bar because it is not measuring the same thing.",
     "Read fairly, the table places this work without flattery. Among subject-independent results the published range runs roughly 0.75 to 0.87 accuracy, and the best comparable figure on extended Pittsburgh material located by this review is 0.797, obtained with 1,476 features [10]; at 0.759 this project sits at the challenge baseline and about four accuracy points below that figure — a real gap, and a small one, not the fifteen points the 0.93 headline suggests, because that headline was produced under a protocol that is not subject-independent and was never tested outside its corpus [9]. One line in the table belongs to this work alone: no system in the table reports an external validation of any kind, and on the locked external corpus the best accuracy any threshold could achieve is 0.792, collected by different investigators in a different setting and scored exactly once at a threshold fixed in advance. Figures above 0.90 are reached only by protocols that are not subject-independent, or by transformers, or both, and 0.93 is not the bar because it is not measuring the same thing.")
sub1("The legitimate variant is specified for whoever continues this work: retrain on Pittsburgh minus the ADReSS test participants and evaluate on the ADReSS test set, as a reported experiment that never touches the deployed model. It requires the challenge's participant list, which is not among this project's holdings, and one further model fit; it would give the one directly comparable number against every ADReSS paper, and it is the cheapest route to true comparability that exists.",
     "The legitimate variant is specified for whoever continues this work: retrain on Pittsburgh minus the ADReSS test participants and evaluate on the ADReSS test set, as a reported experiment that never touches the deployed model — the cheapest route to true comparability that exists.")
sub1("Dhikra's headline result is a cross-corpus result. Trained on Pittsburgh and Delaware and scored once on Lu — different speakers, different recording conditions, different clinical ascertainment, a different country — the deployed model reached AUC 0.8533 [0.7371, 0.9458], under the governance and exposure history of section 3.9.",
     "Dhikra's headline result is a cross-corpus result. Trained on Pittsburgh and Delaware and scored once on Lu — different speakers, different recording conditions, different clinical ascertainment, a different country — the frozen English screening model reached AUC 0.8533 [0.7371, 0.9458], under the governance and exposure history of section 3.9.")
t=re.sub(r"\n{3,}","\n\n",t); open(P,'w',encoding='utf-8').write(t)
print('chapter2', len(re.findall(r"\S+", re.sub(r"\|", " ", t.split("**References Cited")[0]))))
