#!/usr/bin/env python3
"""cut_ch3.py -- Chapter 3: 3.9.x → 3.9 + two subsections, 3.10 absorbs 3.10.1, 3.12 keeps the result and the
equation (derivation to Appendix H), 3.7 tightened, trims elsewhere, Figure 3.1 retired (its numbers stay in the text)."""
import re
P = "/home/claude/work/src/docs/chapters/chapter3.md"
t = open(P, encoding="utf-8").read()
def ws(s): return r"\s+".join(re.escape(w) for w in s.split())
def sub1(old, new):
    global t
    n = len(re.findall(ws(old), t)); assert n == 1, (old[:70], n)
    t = re.sub(ws(old), lambda m: new, t)
def replace_section(heading_prefix, new_text, upto=None):
    """replace from the heading line through the line before the next heading (or the `upto` heading)"""
    global t
    L = t.split("\n")
    a = next(k for k, l in enumerate(L) if l.startswith(heading_prefix))
    if upto: b = next(k for k, l in enumerate(L) if k > a and l.startswith(upto))
    else: b = next(k for k, l in enumerate(L) if k > a and re.match(r"^#{2,3} ", l))
    # keep a trailing "---" separator convention out of it
    L[a:b] = new_text.strip("\n").split("\n") + [""]
    t = "\n".join(L)

# ── 3.1: shorter exclusions sentence
sub1("Eight further DementiaBank corpora — Baycrest, Baycrest-PPA, DePaul, Holland, Hopkins, Kempler, Lanzi and VAS — were obtained and not used: the design required picture description with diagnostic labels at a scale supporting cross-validated fitting, which Pittsburgh, Delaware and Lu alone meet, and the eight were not audited individually against it.",
     "Eight further DementiaBank corpora were obtained and not used, because the design required picture description with diagnostic labels at a scale supporting cross-validated fitting, which Pittsburgh, Delaware and Lu alone meet.")

# ── 3.2.1: retire Figure 3.1, keep its numbers
sub1("It survived a guard that was correct in principle. The deployed feature set contains no markup-derived features, because transcription convention alone separates *healthy* speakers of different corpora at an AUC of 0.930, as Figure (3.1) shows. **That exclusion removed markup features; it did not remove markup from the transcript text the linguistic features are computed on.**",
     "It survived a guard that was correct in principle. The deployed feature set contains no markup-derived features, because transcription convention alone separates *healthy* speakers of different corpora at an AUC of 0.930, falling to 0.783 once the markup is removed — the finding that made naive corpus pooling invalid — and across the 64 deployed features the median absolute shift between the two development cohorts' controls is 0.22 (`results/wls/findings.json`, `results/reconstruction/domain_shift_and_errors.json`). **That exclusion removed markup features; it did not remove markup from the transcript text the linguistic features are computed on.**")
sub1("**Figure (3.1) : The corpus effect. Left: two groups of healthy speakers from different studies are separable at AUC 0.930 on the full feature set, falling to 0.783 once CHAT transcription markup is removed — the finding that made naive corpus pooling invalid. Right: the same comparison restricted to the 64 deployed features, none of which are CHAT markup; the median absolute shift is 0.22 and only six features exceed 0.5.**", "")
sub1("The registered grade is *negligible*, by one ten-thousandth, and reporting the grade without the margin would be exactly the rounding this work exists not to perform. The application transcribes",
     "The registered grade is *negligible*, by one ten-thousandth. The application transcribes")
sub1("The external corpus was checked for the same pattern, under a check declared descriptive before it ran — counting a text pattern is metadata inspection of the same category as reading the header fields that supply ages and diagnoses — and **eight** such forms exist in the entire corpus. The inference favours this work and is volunteered: the model was fitted where the artefact is common and correlates with diagnosis, and evaluated where it is effectively absent.",
     "The external corpus was checked for the same pattern under a check declared descriptive before it ran, and **eight** such forms exist in the entire corpus: the model was fitted where the artefact is common and correlates with diagnosis, and evaluated where it is effectively absent.")

# ── 3.5
sub1("Elicitation is fixed and logged — a verbatim prompt, an enforced maximum duration, a stated re-prompt rule, elicitation time and probe count recorded per session — because word count is the strongest single marker for mild impairment on connected discourse, and variable administration would make the battery's primary signal an artefact of the examiner. Chapter 5 supplies the other half: a minimum-length filter was tested and **refused**, so thin samples must be prevented at elicitation rather than removed afterwards. The Qur'anic task is **exploratory** throughout, with six documented confounders, and is not claimed as a validated biomarker.",
     "Elicitation is fixed and logged — a verbatim prompt, an enforced maximum duration, a stated re-prompt rule, elicitation time and probe count recorded per session — because word count is the strongest single marker for mild impairment on connected discourse, and a minimum-length filter was tested and **refused** (Chapter 5), so thin samples must be prevented at elicitation rather than removed afterwards. The Qur'anic task is **exploratory** throughout and is not claimed as a validated biomarker.")

# ── 3.6.1
sub1("Much published work on this corpus uses stratified folds without grouping. The claim that the two protocols measure different things was **replaced with a measurement**, on the principle that a methodological claim which can be tested and is not tested is an opinion. Everything was held constant except the splitter, as Table (3.3) reports.",
     "Much published work on this corpus uses stratified folds without grouping, and the claim that the two protocols measure different things was **replaced with a measurement**: everything was held constant except the splitter, as Table (3.3) reports.")
sub1("Three conclusions follow, and the third takes the most discipline. Participant grouping **remains correct practice**: whether a risk materialised is not the test of whether guarding against it was right. This work **may not claim published figures are inflated by fold leakage**: capacity is the uncontrolled variable — a tree ensemble over 64 aggregate features has far less ability to memorise a speaker than a transformer over raw text — so Chapter 2's comparison rests on the external-validation column, not the fold-protocol column. And **the null is reported prominently rather than buried**: this is the work testing for an advantage it expected, failing to find it, and declining to claim it.",
     "Three conclusions follow. Participant grouping **remains correct practice**: whether a risk materialised is not the test of whether guarding against it was right. This work **may not claim published figures are inflated by fold leakage**, because capacity is the uncontrolled variable — a tree ensemble over 64 aggregate features has far less ability to memorise a speaker than a transformer over raw text — so Chapter 2's comparison rests on the external-validation column. And the null is reported prominently: this is the work testing for an advantage it expected, failing to find it, and declining to claim it.")

# ── 3.7
replace_section("## 3.7 Risk Adjustment", """
## 3.7 Risk Adjustment

The model output is a screening score: a development-calibrated probability estimate conditioned on the class balance of the training pool, 465 impaired recordings in 987, or 0.4711, and almost nobody is screened at a prevalence of 47%. The risk-adjustment stage therefore divides out the training prior, applies an age-specific population prevalence, a multiplier for why the person is being tested and one for family history, and returns a context-adjusted estimated risk — not a probability clinically calibrated for Libya. Section 3.12 derives the chain; Appendix H holds the evidence base for every constant, the prevalence and multiplier tables, and the property-based verification. Two parameters changed during this work, and each carries a methodological point.

**One referral multiplier was retained and one removed.** The retained multiplier is ×2.5, applied when the person or their family has noticed a change; it was asserted as an engineering assumption before any source was sought, and support was found afterwards — a published meta-analysis gives a positive likelihood ratio of 2.29 for the same evidence, within rounding of the asserted figure [4, 5, 6]. The removed multiplier is ×4.0 for clinician referral, and **it was not removed because the evidence went against it** — the available indirect comparison implies an odds ratio of roughly 4 to 8 once the clinic cohorts' higher mean age is allowed for [7, 8, 9, 10, 11] — but because **referral is not a diagnostic test and has no stable operating characteristics**: the same national audit that yields the highest of those figures found dementia yield ranging from 22% to 100% across 85 services, in one country, in one year, so a referral rate is a local policy variable, and no value calibrated on British or Dutch memory clinics would transport to a setting where referral pathways for cognitive complaint are largely absent. **A quantity can be well evidenced in direction, large in magnitude, and still not be a parameter, because it has no stable referent** [9]. A clinician-referred session now receives the same ×2.5 as a reported concern, declared as a **floor rather than an estimate**, since nearly everyone referred also reports a change and the indirect evidence says the true uplift is larger; removing an overstated figure without saying so would simply have converted it into an understated one. The referral contexts are mutually exclusive branches, one per session, and a multiplier and its baseline are a matched pair: the ×1.0 baseline presumes an unselected population, so against an age-conditioned prior the implied clinic uplift shrinks from roughly eight to roughly four to five.

Family history enters as a multiplier of 1.73 for one affected first-degree relative and 3.98 for two or more, with a reported *no* leaving the prior unchanged rather than lowering it, because in a low-diagnosis setting *no* very often means *nobody in this family was ever diagnosed* [12]. That branch carries a defect which is disclosed rather than patched: the published figures are **relative risks**, the chain multiplies prior **odds**, and the two diverge once baseline risk is large, so the composition **overstates familial risk at the oldest ages**; the prior cap of 0.85 is the symptom rather than a prudence measure, binding in exactly 4 of 135 prior combinations — all two-first-degree-relative cases at ages 80 and above with a referral uplift — and Appendix H sets out the defect, its direction across the age range, the reason the arithmetic is left unpatched, and an objection to the family-history branch itself that was tested and withdrawn. The chain was verified mechanically over 1,440 cases against nine properties, **all 1,440 passing with zero failures**; the same speech score of 0.90 yields a posterior of 4.8% at age 25 and 92.5% at age 85, and a 72-year-old scoring 0.70 receives 0.316 with no context multiplier, 0.536 under the ×2.5 uplift, and would have received 0.649 under the retired ×4.0.

---
""")

# ── 3.9 block (3.9, 3.9.0, 3.9.1, 3.9.2, 3.9.3 → 3.9 with two subsections)
old39 = t[t.index("## 3.9 External Test Set Governance"):t.index("## 3.10 Preregistration")]
fig32 = re.search(r"\*\*Figure \(3\.2\) :.*?\*\*", old39, re.S).group(0)
tab34 = re.search(r"\*\*Table \(3\.4\) :.*?\n\n(\|.*?\n)+", old39, re.S).group(0).rstrip()
tab34 = tab34.replace("| **0.8533** [0.7371, 0.9458] | Deployed model | The deployed system, on data absent from its training, at a threshold fixed in advance, scored once |",
                      "| **0.8533** [0.7371, 0.9458] | Frozen English screening model | The frozen model, on data absent from its training, at a threshold fixed in advance, scored once |")
assert "Frozen English screening model" in tab34
replace_section("## 3.9 External Test Set Governance", f"""
## 3.9 External Test Set Governance And The Failure That Produced It

This is the methodological centre of the chapter. The Lu corpus was obtained to serve as an external test set, and in the hours before the lock it was scored five times while training configurations were compared. The first scoring, of a Pittsburgh-trained model, gave **0.821** before any modelling decision had been informed by the corpus, and that figure is clean. A subsequent scoring of a Pittsburgh-plus-Delaware model gave 0.859, and **that comparison is what admitted Delaware to the training pool**; a corpus used to choose between training configurations is a model-selection set, not a held-out test set. A third error followed: the corpus was added to the training pool, and a cross-validated figure obtained *within* that pool, 0.849, was reported as external validation. It was not caught by an internal check. An adversarial external review of the draft claims identified the contamination, and **this work's own governance did not catch it**, which is stated plainly rather than presenting the correction as foresight.

### 3.9.1 The Correction And What Each External Figure Validates

The corpus was then locked out. The final model was retrained on the development pool alone, 987 recordings from 581 participants, the operating threshold was fixed at 0.367 on development data **before** the run, and the corpus was scored exactly once, after the lock: **AUC 0.8533, 95% confidence interval [0.7371, 0.9458], sensitivity 96.2% at 25 of 26, specificity 33.3% at 9 of 27.** The specificity collapse is reported in full because exposing it is what a locked test set is for; its diagnosis — a threshold referenced to the wrong distribution, with a remedy analysed but not deployed — is section 5.13. Subsequently the evaluation was reproduced under a protocol permitting one execution and no decision in either direction; the AUC matched to ten decimal places and the confusion matrix cell for cell, and a tombstone file now blocks any further run. Figure (3.2) places this sequence alongside every approach that was tested and rejected, and both external figures are reported, because each validates something the other does not (Table (3.4)).

{fig32}

{tab34}

The two sit 0.032 apart on the same 53 recordings, and 0.821 falls inside the confidence interval of 0.8533; that proximity **bounds** how large the selection effect can be, though the gap mixes selection with the genuine benefit of more training data and so bounds their sum. **One architectural decision** — which corpora entered the training pool — was made with knowledge of a score from the external corpus, and nothing else was: no hyperparameter, no operating threshold, no feature selection, no calibration method, no model form. That is a fact about the *scope* of the contamination, recorded after the problem was volunteered; it is not a defence. The pooling decision was also re-examined without touching the locked corpus: the exact pre-lock comparison cannot be reproduced Lu-free, so a weaker proposition was pre-registered and tested instead — whether the two development corpora are mutually informative — and they are, in both directions (section 5.12).

### 3.9.2 The Day The Lock Rule Changed A Decision

The rule was then tested by the project's own work, and section 5.4.1 reports the case in full. A calibration defect was found, the standard correction was derived — Cox logistic recalibration, two coefficients, no tuning, strictly monotone and therefore incapable of disturbing any locked result — and a transfer test was pre-registered on the development cohorts; it failed, because **the two development cohorts are miscalibrated in opposite directions**. The obvious test was the locked corpus, and the registration had declared before execution that the corpus would be scored descriptively afterwards and **would not enter the decision whatever it showed**. On that corpus the correction passed both criteria the development arms had failed. **Had the locked corpus been consulted, the correction would have been applied. The rule that forbade consulting it changed the decision, and changed it rightly** — a case in which the rule and the analyst's judgement diverged and the rule was correct, which is more than arguing that a rule is prudent.

---
""", upto="## 3.10 Preregistration")

# ── 3.10 + 3.10.1 → 3.10
replace_section("## 3.10 Preregistration", """
## 3.10 Preregistration As A Working Method Including Where It Failed

The pattern used throughout the post-lock work is uniform: the criteria, tolerances and stop rule for a run are written into the driver script's docstring and committed **before the run**, the grading is mechanical, failure is reported rather than iterated away, and the interpretive direction is registered too — for the acoustic protocol test, failure meant *the protocol is not confirmed*, never *the model is wrong*. Two worked examples show the machinery catching a defect in a **rule** and a defect in the **analyst**.

**A pre-registered check caught the analyst's own bug.** The probe of the referential deficit index registered a provenance check with nothing to do with the hypothesis — the recomputed pronoun-to-noun ratio must reproduce the committed feature to within one part in a million on at least 99% of recordings, failing which the run is void — and **it failed**, reproducing the committed feature on 36% of Pittsburgh and 82% of Delaware recordings. The defect was in the **new script**, not the tagger, the environment or the committed extractor (Appendix H), and fixing it **honoured** the pre-registration rather than relaxing it; one cohort's result had appeared in terminal output before the fix, and that is recorded in the driver's registration history in those words. The check that caught it was a provenance formality nobody expected to fail: the value of pre-registration is concentrated in the checks written when the author is not worried.

**A criterion that failed on contact with the data.** The cross-corpus transfer analysis registered a retention ratio — transfer AUC over the within-corpus reference of the test corpus — which silently assumes its denominator is a working reference, and in one direction it is not: Delaware trained on itself scores 0.5474, an interval spanning chance (section 5.12.1), so the ratio came out at 1.18 and the registered rule stamped it **strong**, a meaningless verdict. **The criterion was left exactly as registered and the arm was not re-run**, because **a rule rewritten after seeing the result is the result wearing a rule's clothes**; the first criterion, that transfer exceeds chance, passed on its own terms, so the transfer finding stands and only the retention framing is void. **Neither failure was found by a reviewer; both were found by the machinery, which is the only test of whether the machinery is real.**

Three registrations in seventeen runs required amendment on contact with the data — the retention criterion above, the tokenisation of the referential-index probe, and the label rule of the task-count curve, where 6.25% of participants change label across visits — and Appendix H tabulates each with its timing relative to seeing the result. They share a shape: in none of the three was the defect in the hypothesis, the criterion band or the analysis set, the three things a registration template asks for. **A pre-registration protects the parts of a design its author already knows are contestable; it does not protect the parts they have not thought of, and in practice those are where the defects are.** The working discipline this produced is four rules, derived in Appendix H: never adjust the rule to reach the assertion; record when an amendment was made relative to seeing the result; report both versions whenever an amendment changes an answer; and register a sanity gate on every derived quantity an analysis depends on, including its labels. A fourth case extends the last rule to comparisons: a claim that a hand-countable feature matched the calibrated ensemble **reversed sign once both sides were estimated alike** (section N5.16), because one side had been selected as the best of 43 on the same participants and the other not selected at all — so the rule extends to refusing any comparison whose sides were produced by procedures with different numbers of free parameters.

---
""", upto="## 3.11 Monotone")

# ── 3.11 trim
sub1("Three separate methodological questions in this work have the same answer, and stating the reason once turns three empirical findings into one argument with three corollaries.",
     "Three separate methodological questions in this work have the same answer.")
sub1("**These were not close calls; they are the lemma being observed.**", "")
sub1("The positive half matters more. The lemma says what normative normalisation *is* good for — calibration and thresholds, which are exactly ranking-position questions. Control-referenced thresholding, this work's principal methodological contribution, is a normative normalisation, and it works precisely because a threshold is a calibration property rather than a discrimination property: **the lemma is not a limitation on the contribution but the reason it is correctly aimed.** It also settles the sex gap: if no monotone transform can close it, only a different feature set or model can, and under the frozen-model constraint neither is available, so the gap is reported, explained mechanistically in Chapter 5, and carried into Chapter 6 as a design requirement rather than repaired by a step that provably cannot repair it.",
     "The positive half matters more. The lemma says what normative normalisation *is* good for — calibration and thresholds, which are ranking-position questions — so control-referenced thresholding, this work's principal methodological contribution, works precisely because a threshold is a calibration property rather than a discrimination property: **the lemma is not a limitation on the contribution but the reason it is correctly aimed.** It also settles the sex gap: if no monotone transform can close it, only a different feature set or model can, and under the frozen-model constraint neither is available, so the gap is reported, explained mechanistically in Chapter 5, and carried into Chapter 6 as a design requirement.")

# ── 3.12: result and equation stay; the Cox decomposition, its table and the age-flatness measurement go to Appendix H
replace_section("## 3.12 The Calibration Architecture", """
## 3.12 The Calibration Architecture Is A Density Ratio Likelihood Ratio

The system converts a speech sample into a screening score, then re-applies a deployment-specific prevalence, and the chain is derived rather than merely asserted so that its prevalence-independence claim is provable. A calibrated classifier trained at prevalence *π*₀ outputs *p*(*x*); dividing out the prior it was trained with gives the Bayes factor the speech sample contributes:

> **LR(*x*) = [ *p*(*x*) / (1 − *p*(*x*)) ] × [ (1 − *π*₀) / *π*₀ ]**

By construction this equals the ratio of the class-conditional densities, *f*₁(*x*) / *f*₀(*x*) — the **density ratio** between how impaired and healthy speakers distribute over the feature space — and deployment applies the local prior, so the posterior odds are LR(*x*) × *π* / (1 − *π*). **Prevalence independence becomes a theorem:** neither class-conditional density is a function of *π*, so LR(*x*) is invariant to prevalence, and every prevalence-dependent quantity — predictive values, the posterior bands — is an invariant evidence term multiplied by a local prior. In deployment the likelihood ratio functions as an empirical evidence estimator rather than an exact density ratio: it inherits whatever miscalibration *p*(*x*) carries, and with the development calibration slope above one (section 5.4.1) it conservatively underweights extreme values, understating strong evidence rather than overstating it.

Three consequences are derived in Appendix H and stated here. **Cox recalibration decomposes into two distinct failures** that must never be reported as one number: the slope *b* rescales the log-likelihood ratio, the strength of the evidence, and the intercept *a* the implied prior, so Pittsburgh's slope of 1.516 against Delaware's 0.823 means that *evidence strength itself is corpus-dependent and in opposite directions*, one global recalibration cannot repair two errors of opposite sign, and section 3.9.2's pre-registered decision and the mathematics reached the same conclusion independently. **The multipliers are separate likelihood ratios**, and multiplying likelihood ratios is exactly correct provided the sources are conditionally independent given class; that proviso was tested where it is most at risk — age is recoverable from the deployed features at *R*² = 0.994 — and measured on the 987 development recordings the model's evidence is approximately age-flat within each class, with a residual drift of a factor of 0.87 across a twenty-year span that runs the wrong way for double-counting (Appendix H): **the information being present is not the same as the information being used**, and the age prior may be applied on top of the model's likelihood ratio. And control-referenced thresholding and the likelihood ratio are complementary rather than competing: a threshold at a fixed percentile of the local healthy-control distribution fixes the false-positive rate by construction and needs no prevalence estimate, while the likelihood ratio supplies how much evidence a given sample carries, with prevalence entering only at the final step. **The operating point is set by the control distribution; the reported risk is set by the likelihood ratio and the local prior. Two mechanisms, two jobs, no overlap.**

---
""", upto="**References Cited In This Chapter.**")

t = re.sub(r"\n{3,}", "\n\n", t)
open(P, "w", encoding="utf-8").write(t)
words = len(re.findall(r"\S+", re.sub(r"\|", " ", t.split("**References Cited")[0])))
print("chapter3.md:", words, "words")
