import re
P="/home/claude/work/src/docs/chapters/chapter1.md"; t=open(P,encoding='utf-8').read()
def sub1(old,new):
    global t; assert t.count(old)==1,(old[:60],t.count(old)); t=t.replace(old,new)
sub1("Chapter 5, Results and Discussion, reports the validated instrument: the development and external evaluations with their confounds and calibration, the diagnosis of the instrument's weakest number, fifteen negative results in one register, the measurement properties, and the probes that belong to the successor, reported under the rule of section 1.7. Chapter 6, Conclusion and Future Work, states what was learned and what it is worth, the limitations, the staged validation design and deployment path, the Arabic contribution in its three parts, and the closing claim; nothing in it is externally validated, and its first sentence says so.",
     "Chapter 5, Results and Discussion, reports the externally evaluated model — the development and external evaluations with their confounds and calibration, the operating point and its diagnosis, fifteen negative results in one register, the measurement properties — and the probes that belong to the successor, reported under the rule of section 1.7. Chapter 6, Conclusion and Future Work, states what was learned and what it is worth, each limitation with what would remove it, the staged validation design, the Arabic contribution in its three parts, and the closing claim.")
sub1("Validated: the frozen English screening model was evaluated exactly once, on an external corpus, at a threshold fixed in advance. Locked external performance: AUC 0.8533 [0.7371, 0.9458], sensitivity 96.2%, specificity 33.3%. Subsequent threshold-transport analysis recovered external specificity to 77.8% by control-referenced thresholding — a post-hoc methodological contribution, not preregistered, not deployed, and requiring prospective validation. The corpus was excluded",
     "Validated: the frozen English screening model was evaluated exactly once, on an external corpus, at a threshold fixed in advance — AUC 0.8533 [0.7371, 0.9458] — and the operating point, its low specificity and the post-hoc rule that recovers it are owned by sections 5.3 and 5.13. The corpus was excluded")
sub1("Chapter 5 reports the validated instrument. Chapter 6 reports the specified successor, and its first sentence says that nothing in it is externally validated. The structure is deliberate: a specified configuration that outperforms the validated one is the proper output of a future-work chapter, not an embarrassment. A thesis organised as the deployed system plus its experiments would invite the question of why the weaker configuration was deployed, and would force a governance argument into the middle of a results chapter; organised as validated and specified, the same finding is the deliverable it should be. One rule enforces the distinction mechanically, and it is never broken.",
     "Chapter 5 reports the externally evaluated model first and the specified successor last, under its own heading, and Chapter 6 says which is which. The structure is deliberate: a specified configuration that outperforms the evaluated one is the proper output of a future-work section, not an embarrassment. One rule enforces the distinction mechanically, and it is never broken.")
sub1("Different chapters, different tables, every time. The moment the two share a table, the reader must hold the distinction themselves — and by the account of this field's own review literature, readers do not, which is part of how a decade of reported performance above ninety per cent coexists with no tool in clinical use (section 2.3).",
     "The moment the two share a table, the reader must hold the distinction themselves — and by the account of this field's own review literature, readers do not, which is part of how a decade of reported performance above ninety per cent coexists with no tool in clinical use (section 2.3).")
t=re.sub(r"\n{3,}","\n\n",t); open(P,'w',encoding='utf-8').write(t)
print('chapter1', len(re.findall(r"\S+", re.sub(r"\|", " ", t.split("**References Cited")[0]))))
