#!/usr/bin/env python3
"""cut_ch3b.py -- further Chapter 3 trims (preamble, 3.3, 3.4 stale claim, 3.6, 3.8)."""
import re
P = "/home/claude/work/src/docs/chapters/chapter3.md"
t = open(P, encoding="utf-8").read()
def ws(s): return r"\s+".join(re.escape(w) for w in s.split())
def sub1(old, new):
    global t
    n = len(re.findall(ws(old), t)); assert n == 1, (old[:70], n)
    t = re.sub(ws(old), lambda m: new, t)
sub1("Sections 3.1 to 3.5 cover the material — the corpora, the preparation of the transcripts, the measures computed from them, and the task battery; sections 3.6 to 3.8 the evaluation protocol, the risk adjustment that converts a model output into a statement about a person, and the quality gate; sections 3.9 to 3.12 governance and derivation. The last group is why this chapter is longer than its counterparts: a speech-based screening result is easy to produce and hard to trust, and what a reader must assess is not the number reported but the number of decisions taken with knowledge of the data the number was computed on. This work makes that quantity auditable — an external corpus locked and scored once, a pre-registration practice applied to every post-lock analysis, and a written record of the occasions on which both mechanisms failed. A governance account that reports only successes is indistinguishable from no governance account at all, so three of these sections report a failure. Sections 3.11 and 3.12 are derivations rather than measurements, placed here because they constrain what the results of Chapter 5 can mean.",
     "Sections 3.1 to 3.5 cover the material — the corpora, the preparation of the transcripts, the measures computed from them, and the task battery; sections 3.6 to 3.8 the evaluation protocol, the risk adjustment that converts a model output into a statement about a person, and the quality gate; sections 3.9 to 3.12 governance and derivation. A speech-based screening result is easy to produce and hard to trust, and what a reader must assess is not the number reported but the number of decisions taken with knowledge of the data the number was computed on. This work makes that quantity auditable — an external corpus locked and scored once, a pre-registration practice applied to every post-lock analysis, and a written record of the occasions on which both mechanisms failed, because a governance account that reports only successes is indistinguishable from no governance account at all.")
sub1("Two qualifications travel with the table. The 64 columns are **63 distinct quantities**, because the information-unit proportion is the unit total divided by a constant, and two of the 24 lexical columns are the inert features of section 3.2.2; neither was removed, because any change to the frozen feature vector would void the external validation. Acoustic measures were implemented and evaluated but are **not deployed**: they require clean audio, and a system that produces no result without it fails the setting this work targets. The information-content family follows the established information-unit inventories for this task, scoring the presence of 23 canonical scene units [2, 3].",
     "The 64 columns are **63 distinct quantities**, because the information-unit proportion is the unit total divided by a constant, and two of the 24 lexical columns are the inert features of section 3.2.2; neither was removed, because any change to the frozen feature vector would void the external validation. The 53 acoustic measures were implemented and evaluated but are **not deployed**: they require clean audio, and a system that produces no result without it fails the setting this work targets. The information-content family follows the established information-unit inventories for this task, scoring the presence of 23 canonical scene units [2, 3]; Appendix A defines every measure.")
sub1("**Its evidential status must be stated exactly**: implemented and verified on constructed examples; never computed on the speech of a diagnosed patient in any language; discriminative validity untested — the 24-recording Arabic pilot evaluated the acoustic model, not this index. It is a literature-consistent hypothesis that the protocol of Chapter 6 is designed to test, not an established marker.",
     "**Its evidential status must be stated exactly**: implemented and verified on constructed examples; probed in English on the speech of diagnosed patients, where it behaves as a candidate dementia-stage marker and not an early one (section 5.10.1); never computed in Arabic on a diagnosed patient — the 24-recording Arabic pilot evaluated the acoustic model, not this index. It is a candidate the protocol of Chapter 6 is designed to test, not an established marker.")
sub1("The same clustering governs every uncertainty statement: each confidence interval in this thesis is **participant-clustered**, resampling participants rather than recordings, because repeat visits are correlated within a person. The resampling unit of every interval-bearing result file is audited in a committed registry (`results/BOOTSTRAP_UNITS.json`), which declares the five files whose units could not be verified because their producing code was not committed; every headline figure traces to a verified unit or to one that coincides with the participant by construction.",
     "The same clustering governs every uncertainty statement: each confidence interval in this thesis is **participant-clustered**, resampling participants rather than recordings, because repeat visits are correlated within a person; the resampling unit of every interval-bearing result file is audited in a committed registry (`results/BOOTSTRAP_UNITS.json`), and every headline figure traces to a verified unit.")
sub1("Its thresholds are empirical, set from the degradation study of Chapter 5, in which real recordings were subjected to eight controlled degradations and each feature family's stability measured against the clean original. Background noise is the condition that matters and it attacks pause measurement first; at a 10 dB signal-to-noise ratio extraction fails outright, which is the basis for the refusal threshold.",
     "Its thresholds are empirical, set from the degradation study of section 5.9: background noise is the condition that matters and it attacks pause measurement first, and at a 10 dB signal-to-noise ratio extraction fails outright, which is the basis for the refusal threshold.")
t = re.sub(r"\n{3,}", "\n\n", t)
open(P, "w", encoding="utf-8").write(t)
print("chapter3.md:", len(re.findall(r"\S+", re.sub(r"\|", " ", t.split("**References Cited")[0]))), "words")
