#!/usr/bin/env python3
"""trim_ch5.py -- second pass on the assembled Chapter 5 (run after cut_ch5.py): tighten to ~10,000 words."""
import re
P = "/home/claude/work/src/docs/chapters/chapter5.md"
t = open(P, encoding="utf-8").read()
def sub1(old, new):
    global t
    assert t.count(old) == 1, (old[:70], t.count(old)); t = t.replace(old, new)
def replace_section(heading_prefix, new_text):
    """replace the whole section (heading through the line before the next heading) with new_text"""
    global t
    L = t.split("\n")
    a = next(k for k, l in enumerate(L) if l.startswith(heading_prefix))
    b = next((k for k, l in enumerate(L) if k > a and re.match(r"^#{2,3} ", l)), None)
    if b is None: b = next(k for k, l in enumerate(L) if k > a and l.startswith("**References Cited"))
    L[a:b] = new_text.strip("\n").split("\n") + [""]
    t = "\n".join(L)
def drop_table(caption_prefix):
    global t
    L = t.split("\n")
    a = next(k for k, l in enumerate(L) if l.startswith(caption_prefix))
    b = a + 1
    while b < len(L) and (L[b].startswith("|") or not L[b].strip()): b += 1
    del L[a:b]
    t = "\n".join(L)

# preamble
sub1("Sections 5.1 to 5.12 report the externally evaluated model: development performance and its confounds, the external evaluation and calibration, the scorer check against a human, the negative results, the measurement properties, the Arabic construct probe and the cross-corpus evidence behind the pooling decision. Section 5.13 is the operating point — why the threshold did not transport and what recovers it. Sections N5.14 to N5.16 are the probes that belong to the specified successor, reported under the rule of section 1.7: development evidence, none of it externally validated, none of it in a table with a validated figure.",
     "Sections 5.1 to 5.12 report the externally evaluated model; section 5.13 is the operating point; sections N5.14 to N5.16 are the probes that belong to the specified successor, reported under the rule of section 1.7 — development evidence, none of it externally validated, none of it in a table with a validated figure.")

# 5.1.1
sub1("The reading favours the design. Every comparable system in this literature is a model, and none of them degrades to anything; this one degrades to a piece of paper. A health worker with a checklist of the scene's information units reaches an AUC near 0.75 for dementia with no computer and no network — the setting the project exists for — and the instrument has that property only because it was built on features with clinical meaning instead of embeddings. What the 4.5 points buy is stated with equal directness: the full model adds the lexical, syntactic and coherence families, which is what keeps the score robust when a single count is distorted by a talkative or taciturn participant, and it is what makes calibration, and therefore the risk layer of section 3.7, possible at all. Modest and real is the accurate description.",
     "The reading favours the design. Every comparable system in this literature is a model, and none of them degrades to anything; this one degrades to a piece of paper: a health worker with a checklist of the scene's information units reaches an AUC near 0.75 for dementia with no computer and no network, and the instrument has that property only because it was built on features with clinical meaning instead of embeddings. What the 4.5 points buy is the lexical, syntactic and coherence families, which keep the score robust when a single count is distorted by a talkative or taciturn participant and make calibration, and therefore the risk layer of section 3.7, possible at all.")

# 5.1.2
sub1("A pretrained-representation arm neither refutes nor confirms a ceiling claim: replacing all 64 handcrafted features with a 300-dimensional mean document vector from pretrained static word embeddings — same cohort, architecture and folds — gives 0.8018 against the handcrafted 0.8095 on Pittsburgh, graded CEILING-CLAIM-QUALIFIED under its pre-registered criteria; sixty-four interpretable features match three hundred opaque dimensions, but a static, order-discarding representation is a floor, not a ceiling, and a contextual transformer, untestable on this hardware, would very likely do better. Hyperparameter tuning was rejected because any configuration selected on development performance inflates the development estimate, the external corpus is spent, and the defensible version — nested tuning inside training folds, roughly 180 fits of a calibrated three-member ensemble — was unaffordable in the time remaining.",
     "A pretrained-representation arm neither refutes nor confirms a ceiling claim: replacing all 64 handcrafted features with a 300-dimensional mean document vector from pretrained static word embeddings, same cohort, architecture and folds, gives 0.8018 against the handcrafted 0.8095 on Pittsburgh, graded CEILING-CLAIM-QUALIFIED — sixty-four interpretable features match three hundred opaque dimensions, but a static representation is a floor, not a ceiling, and a contextual transformer, untestable on this hardware, would very likely do better. Hyperparameter tuning was rejected because any configuration selected on development performance inflates the development estimate, the external corpus is spent, and the defensible nested version was unaffordable in the time remaining.")

# 5.2.1 — drop Table 5.4, keep the claim
drop_table("**Table (5.4)")
sub1("The residual is not a sensitivity failure — sensitivity within MMSE band is equal or better for men in three of four bands, as Table (5.4) shows — but a specificity failure,",
     "The residual is not a sensitivity failure — sensitivity within MMSE band is equal or better for men in three of four bands — but a specificity failure,")

# 5.3
sub1("The claim is stability, not superiority, and it is led with rather than retreated to. The external evaluation does not demonstrate improved performance: with 53 participants, the interval on 0.8533 [0.7371, 0.9458] cannot be separated from the combined development figure of 0.7550 [0.7192, 0.7902], and an examiner who notices that a model apparently improved out of sample will rightly ask what is wrong with the development estimate. What the evaluation establishes is narrower:",
     "The claim is stability, not superiority. With 53 participants the interval on 0.8533 [0.7371, 0.9458] cannot be separated from the combined development figure of 0.7550 [0.7192, 0.7902], and a model that apparently improved out of sample invites the question of what is wrong with the development estimate. What the evaluation establishes is narrower:")
sub1("The clean figure is 0.821, from a Pittsburgh-only model that predates every exposure, and the two are reported together in exactly the relation Chapter 3 fixed — the accurate scope is this: the corpus was excluded",
     "The clean figure is 0.821, from a Pittsburgh-only model that predates every exposure, and the two are reported together in the canonical form: the corpus was excluded")

# 5.4.1
sub1("The coda is the part written most carefully. The locked corpus was scored, descriptively, after the decision was made, under a declaration fixed before execution that whatever it showed would not enter the decision: its raw slope is 1.886, the most compressed of the three, and the development-fitted correction moves it to 1.464 — toward one, on both criteria the development arms failed. Had the locked corpus been consulted, the correction would have been applied; the rule that forbade consulting it changed the decision, which is what the rule is for. The arithmetic is unchanged, and the defect, its magnitude, direction and containment are reported: it is a reporting error and not a triage error, since everyone above 0.367 is referred either way, and the banded output absorbs it in 13 of 14 representative comparisons, the exception being a score of 0.70 at age 65, which moves one band.",
     "The locked corpus was then scored descriptively, under a declaration fixed before execution that whatever it showed would not enter the decision: its raw slope is 1.886 and the development-fitted correction moves it to 1.464, toward one on both criteria the development arms failed — had the locked corpus been consulted the correction would have been applied, and the rule that forbade consulting it changed the decision, which is what the rule is for. The arithmetic is unchanged and the defect is contained: it is a reporting error and not a triage error, since everyone above 0.367 is referred either way, and the banded output absorbs it in 13 of 14 representative comparisons.")

# 5.6
replace_section("## 5.6 Analysis Across Tasks", """
## 5.6 Analysis Across Tasks

The screening task was never chosen on evidence — the Pittsburgh corpus has healthy controls on picture description only — and the first attempt to put evidence behind the deployed four-task battery is reported with its own correction. The pre-registered battery test found a five-task battery at 0.6455 [0.5763, 0.7154] against picture description alone at 0.5687 [0.4998, 0.6393] on the same 288 participants, paired difference +0.0769 [0.0015, 0.1505], graded BATTERY-BETTER. That grade does not survive two design defects, both this project's own, found after the first output was seen and disclosed as such: the participant labels were taken from the first row in file order, which is not the first visit, so for the 18 of 288 participants whose label changes across visits the arm used an arbitrary visit's label; and the battery arm carried 320 features against the single task's 64, so task count was confounded with column count. Section 5.25 redoes the comparison with both defects removed, and the battery gain does not survive (+0.0102 [−0.0579, +0.0818], BATTERY-NOT-CONFIRMED). The two results are not a contradiction: feature concatenation lets a model learn to down-weight a task that carries no signal and equal-weight averaging cannot, so together they localise the apparent battery gain — not in administering more tasks but in being able to weight them — and the cheapest way to down-weight the weak task is not to administer it, because the weak task is the picture. The sentence this once licensed, that the four-task design "can now be defended as a measurement rather than a preference", is withdrawn and reproduced here so that a reader of an earlier draft can see exactly what changed.
""")

# 5.7
sub1("The severity index across the picture, fluency and recall tasks is recorded at r = 0.655 with the reference score, an average error of 3.3 points, and that figure is cited with its status: artifact metadata, not a reproduced result. A pre-registered reconstruction recovered the deployed model's configuration exactly, but neither registered aggregation hypothesis reproduced the figure — the cells bracket it at 0.631 to 0.688 — and the rebuilt cohort has 156 participants against the artifact's recorded 155, a one-participant discrepancy that remains unexplained. The grade is CANNOT-CONFIRM, the deployed report says so wherever the index appears, and the index is delivered as a band rather than a number for exactly this reason (section 4.4).",
     "The severity index across the picture, fluency and recall tasks is recorded at r = 0.655 with the reference score, an average error of 3.3 points, and that figure is artifact metadata, not a reproduced result: a pre-registered reconstruction recovered the deployed model's configuration exactly, but neither registered aggregation hypothesis reproduced the figure (the cells bracket it at 0.631 to 0.688) and the rebuilt cohort has 156 participants against the artifact's recorded 155. The grade is CANNOT-CONFIRM, the deployed report says so wherever the index appears, and the index is delivered as a band rather than a number for exactly this reason (section 4.4).")
sub1("Severity stratification of the screening decision itself is a single-cohort analysis and is reported as one — Delaware has no MMSE column and the external corpus's is empty. Table (5.10) gives the gradient on the 459 Pittsburgh recordings with a score:",
     "Severity stratification of the screening decision is a single-cohort analysis, since Delaware has no MMSE column and the external corpus's is empty. Table (5.10) gives the gradient on the 459 Pittsburgh recordings with a score:")

# 5.8 — shorter cells and a shorter second paragraph
for old, new in [
 ("| Nine-year-ahead prediction of later impairment from healthy speech (n = 938) | AUC 0.548 — chance |", "| Nine-year-ahead prediction of later impairment from healthy speech (n = 938) | AUC 0.548, chance |"),
 ("| Two studies' healthy speakers separable at 0.930 | Corpus identity is a stronger signal than disease; a model pooled that way learns the archive, not the condition |", "| Two studies' healthy speakers separable at 0.930 | Corpus identity outweighs disease; a model pooled that way learns the archive |"),
 ("| Residualising a variable out of a feature set does not remove it; the technique was discarded (recoverability is not use: within class the model's evidence is age-flat, section 3.12) |", "| Residualising a variable out of a feature set does not remove it; the technique was discarded (within class the model's evidence is nonetheless age-flat, section 3.12) |"),
 ("| Concatenating tasks does not help when only one task has healthy controls to learn from; superseded as a design question by section 5.25 |", "| Concatenation does not help when only one task has healthy controls to learn from; superseded by section 5.25 |"),
 ("| Naive score averaging across modalities buys nothing; the published remedy needs a runtime this deployment target cannot have |", "| Naive score averaging across modalities buys nothing; the published remedy needs a runtime this target cannot have |"),
 ("| The 64 features are not a redundant pile with a small useful core; dimensionality is not the lever |", "| The 64 features have no small useful core; dimensionality is not the lever |"),
 ("| Domain shift is not repaired by deleting the features that carry it; the reverse direction's +0.014 is not claimable — the ranking saw the target (section 5.21) |", "| Domain shift is not repaired by deleting the features that carry it; the reverse direction's +0.014 saw the target and is not claimable (section 5.21) |"),
 ("| Tested and not found: grouped 0.8228 against ungrouped 0.8203, −0.0025, despite 68.4% participant overlap | Grouping stays as correct practice; this model class does not exploit the leakage it prevents. Not extrapolable to higher-capacity models (section 3.6.1) |", "| Grouped 0.8228 against ungrouped 0.8203, −0.0025, despite 68.4% participant overlap | Grouping stays as correct practice; this model class does not exploit the leakage it prevents, which says nothing about higher-capacity models (section 3.6.1) |"),
 ("| The paper fallback stays a count, the simpler field instruction; the dynamic variants are unmeasurable — the corpus carries no word timings (section 5.22) |", "| The paper fallback stays a count; the dynamic variants are unmeasurable because the corpus carries no word timings (section 5.22) |"),
 ("| Brevity in a healthy speaker is signal, not inadequate sampling; the specificity ceiling is intrinsic to a sixty-second picture description (section 5.23) |", "| Brevity in a healthy speaker is signal; the specificity ceiling is intrinsic to a sixty-second picture description (section 5.23) |"),
 ("| Closes 6% of the gap (0.2346 → 0.2196); the averaging gain is mostly progression (controls-only +0.008) | The deployment recommendation and the equity problem are separate problems (section 5.24) |", "| Closes 6% of the gap (0.2346 → 0.2196); the averaging gain is mostly progression (controls-only +0.008) | The deployment recommendation and the equity problem are separate (section 5.24) |"),
 ("| More tasks do not help; weighting them does, and the cheapest weighting is not administering the weak one — the registered COOKIE-DISPENSABLE outcome, which is how section 5.25's positive finding was reached |", "| More tasks do not help; weighting them does, and the cheapest weighting is not administering the weak one — COOKIE-DISPENSABLE, the route to section 5.25's positive finding |"),
 ("| The task change is not what breaks the index; the target change is. Its only support is a dementia cohort (section 5.27) |", "| The target change breaks the index, not the task change; its only support is a dementia cohort (section 5.27) |"),
 ("| A property check is not a usefulness check; the risk layer's value is interpretive — a calibration job, as section 3.11 predicts (section 5.29) |", "| The risk layer's value is interpretive, a calibration job, as section 3.11 predicts (section 5.29) |"),
 ("| Similarity cannot separate a synonym from a co-occurring object inside one coherent scene; the mechanism outlives this model size (section 5.30) |", "| Similarity cannot separate a synonym from a co-occurring object inside one coherent scene (section 5.30) |"),
]: sub1(old, new)
sub1("Two results need a sentence the others do not. Negative result 8 pairs with the visit-to-visit agreement of section 5.9.1: among controls that agreement is 0.465 — visits months to years apart, so it includes real change and is a lower bound on reliability — and a person whose own two recordings barely resemble each other offers a model little to memorise, so the null and the instability are the same fact measured two ways; the capacity limitation stops this being a claim about other people's work, since a tree ensemble over 64 aggregate features is not a transformer over raw text. Results 3 and 8 are kept apart deliberately, because only one of them found leakage — result 3 demonstrated a feature-level channel (age reconstructable at R² = 0.994), result 8 tested a fold-structure channel and found nothing (−0.0025) — and writing \"leakage inflates results, as was shown\" would collapse a demonstrated mechanism into an absent one.",
     "Two results need a sentence the others do not. Negative result 8 pairs with the visit-to-visit agreement of section 5.9.1: a person whose own two recordings barely resemble each other (agreement 0.465 among controls) offers a model little to memorise, so the null and the instability are the same fact measured two ways, and a tree ensemble over 64 aggregate features is not a transformer over raw text, so this is evidence about this model and not about others. Results 3 and 8 are kept apart because only one found leakage — result 3 a feature-level channel, result 8 nothing in the fold structure — and writing \"leakage inflates results, as was shown\" would collapse a demonstrated mechanism into an absent one.")

# 5.10.1 — trim
sub1("The pre-registered grades: PRIMARY, PARTIAL — the pronoun-free index discriminates on Pittsburgh, improves to 0.625 under age and sex matching so it is not an age artefact, and fails on Delaware; SECONDARY, NEUTRAL — adding demonstratives and vague nouns to the established marker neither helps nor hurts; TERTIARY — the pronoun-free and established measures correlate 0.556 to 0.631 within class, so they read the same construct. The comparison that must accompany the PARTIAL grade: the established pronoun marker also fails on Delaware (0.551, spanning chance), so the Delaware failure is a property of that cohort's target, not a defect of the new measure. The probe fixes a falsifiable expectation for an Arabic dementia sample — the pronoun-free form is a lossy substitute in English, 0.596 against 0.656, so the prediction is an AUC near 0.6, not near 0.8 — and it found a defect in the Arabic engine: matching demonstratives by bare string match drops Delaware to exactly chance (0.5005 against 0.535) because existential and complementiser uses are noise, and the Arabic word هناك does the same double duty, a limitation recorded against the engine, which cannot filter those uses without an offline Arabic parser. This is construct evidence in English only, and it does not validate the Arabic index.",
     "The pre-registered grades: PRIMARY, PARTIAL — the pronoun-free index discriminates on Pittsburgh, improves to 0.625 under age and sex matching so it is not an age artefact, and fails on Delaware; SECONDARY, NEUTRAL — adding demonstratives and vague nouns to the established marker neither helps nor hurts; TERTIARY — the two measures correlate 0.556 to 0.631 within class, so they read the same construct. The established pronoun marker also fails on Delaware (0.551, spanning chance), so that failure is a property of the cohort's target, not a defect of the new measure. The probe fixes a falsifiable expectation for an Arabic dementia sample — the pronoun-free form is a lossy substitute in English, 0.596 against 0.656, so the prediction is an AUC near 0.6, not near 0.8 — and it found a defect in the Arabic engine: matching demonstratives by bare string match drops Delaware to exactly chance (0.5005 against 0.535) because existential and complementiser uses are noise, and the Arabic word هناك does the same double duty, which the engine cannot filter without an offline Arabic parser. This is construct evidence in English only, and it does not validate the Arabic index.")
sub1("Whether the stage dissociation was already known was searched. A systematic review and meta-analysis of 54 studies pools speech-based detection of mild cognitive impairment at 0.78 [0.70, 0.86], names lexical diversity, syntactic complexity, acoustic properties and semantic content as the informative domains — the families found moving on discourse above — and does not isolate referential measures at all [9]; where referential measures have been tested head-on they have not separated even dementia [10]; and the strongest apparent counter-case, pronoun-use differences a decade before diagnosis in six later-diagnosed cases against six matched controls, is a group-level finding whose authors state that it does not support individual-level discrimination [11]. The reviews' silence is absence of evidence; this probe is evidence of absence, resting on one corpus, one target, n = 288. The index remains a defensible candidate dementia marker on picture description; it is not supported as a mild-impairment marker; and Chapter 6 splits the specification by target rather than pretending one instrument serves both.",
     "The literature is consistent with this: a systematic review and meta-analysis of 54 studies pools speech-based detection of mild cognitive impairment at 0.78 [0.70, 0.86] and names lexical diversity, syntactic complexity, acoustic properties and semantic content as the informative domains, without isolating referential measures at all [9]; referential measures tested head-on have not separated even dementia [10]; and the strongest apparent counter-case, pronoun-use differences a decade before diagnosis in six cases against six controls, is a group-level finding whose authors state that it does not support individual-level discrimination [11]. The reviews' silence is absence of evidence; this probe is evidence of absence, resting on one corpus, one target, n = 288. The index remains a defensible candidate dementia marker on picture description, it is not supported as a mild-impairment marker, and Chapter 6 splits the specification by target rather than pretending one instrument serves both.")

# 5.11
sub1("One correction is recorded with the table: the sensitivity and specificity intervals are participant-clustered — the earlier working table resampled recordings, which ignores within-participant clustering and understated uncertainty by up to 1.31-fold on Pittsburgh; the external row, one recording per participant, is the row that needed no change, and the AUC intervals are quoted from the authoritative files rather than recomputed. ",
     "The sensitivity and specificity intervals are participant-clustered; an earlier working table that resampled recordings understated uncertainty by up to 1.31-fold on Pittsburgh, and the AUC intervals are quoted from the authoritative files. ")

# 5.13.1 — drop Table 5.17, keep its numbers in prose
drop_table("**Table (5.17)")
sub1("improves Pittsburgh, worsens Delaware on the very data the map was fitted on, and on the external corpus improves the slope while worsening the intercept and the Brier score, as Table (5.17) reports; the mechanism",
     "improves Pittsburgh (slope 1.516 to 1.176), worsens Delaware on the very data the map was fitted on (0.823 to 0.638, Brier 0.220 to 0.222), and on the external corpus improves the slope (1.886 to 1.464) while worsening the intercept and the Brier score (0.179 to 0.182); the mechanism")
sub1("One number cannot serve three cohorts, and the single most important line in Table (5.16) says why: Delaware's impaired mean (0.409) is indistinguishable from Pittsburgh's healthy mean (0.406) and below the external cohort's healthy mean (0.471). The three cohorts do not share a score scale, so one cut-point cannot mean the same thing in all three: at the deployed threshold sensitivity runs 0.856, 0.569 and 0.962 across them, and the Delaware figure does not reach the 0.75 floor the threshold was chosen to satisfy on the pooled set. Forcing a single global threshold makes it worse — a joint rule requiring 75% sensitivity in every cohort lands at 0.286 and keeps only 18.5% worst-case specificity, and in 48.2% of bootstrap resamples at an 0.85 floor no threshold satisfies the floor everywhere — while the three cohorts, allowed to choose alone at a 0.75 floor, pick 0.510, 0.291 and 0.607, a spread of 0.32 on a unit scale that is structural rather than noise. Per-deployment threshold setting on local data is therefore a requirement of the method, not a refinement of it.",
     "One number cannot serve three cohorts, and the single most important line in Table (5.16) says why: Delaware's impaired mean (0.409) is indistinguishable from Pittsburgh's healthy mean (0.406) and below the external cohort's healthy mean (0.471). The cohorts do not share a score scale, so at the deployed threshold sensitivity runs 0.856, 0.569 and 0.962 across them, and the Delaware figure does not reach the 0.75 floor the threshold was chosen to satisfy. A single global threshold makes it worse — a joint rule requiring 75% sensitivity everywhere lands at 0.286 and keeps 18.5% worst-case specificity, and in 48.2% of bootstrap resamples at an 0.85 floor no threshold satisfies the floor everywhere — while the cohorts allowed to choose alone at a 0.75 floor pick 0.510, 0.291 and 0.607, a spread of 0.32 that is structural rather than noise. Per-deployment threshold setting on local data is therefore a requirement of the method, not a refinement of it.")

# 5.13.2 — drop Tables 5.21 and 5.24, keep their numbers in prose
drop_table("**Table (5.21)")
drop_table("**Table (5.24)")
sub1("Table (5.20) gives the continuous measures with Hedges' g and its interval, because with eighteen against nine a bare standardised difference overstates what is known, and Table (5.21) the binary content items with an exact test. The multiplicity position is stated rather than left to be found: no single comparison among the 64 screened features survives Bonferroni correction, only the falling stool survives a false-discovery correction among the binary items, and the age difference does not reach significance at n = 27, so the argument rests on the coherence of the pattern — sixteen of 64 features at an absolute effect of 0.8 or more, against roughly three expected under a null, all pointing toward thinner description — and on the descriptive facts, 11.5 units against 14.9 and 44% mentioning the falling stool against 100%, which are not in dispute.",
     "Table (5.20) gives the continuous measures with Hedges' g and its interval, because with eighteen against nine a bare standardised difference overstates what is known; on the binary content items the false positives mentioned the falling stool 8 of 18 times against 9 of 9 (Fisher exact p = 0.009) and the cupboard 1 of 18 against 5 of 9 (p = 0.008). The multiplicity position is stated: no single comparison among the 64 screened features survives Bonferroni correction, only the falling stool survives a false-discovery correction among the binary items, and the age difference does not reach significance at n = 27, so the argument rests on the coherence of the pattern — sixteen of 64 features at an absolute effect of 0.8 or more, against roughly three expected under a null, all pointing toward thinner description — and on descriptive facts that are not in dispute.")
sub1("A validity rule on transcript length was the obvious remedy, and it was pre-registered and refused. The 215 development controls above the fixed threshold differ from the 307 correctly passed almost entirely in brevity — 103.2 words against 127.4, information-unit total 11.89 against 16.11 — while age and cognitive score are near-identical, so declaring short recordings non-reportable, as standard instruments carry validity criteria, would change no model, feature or threshold. Table (5.24) shows why the grade is GATE-NOT-JUSTIFIED, negative result 10: gates that keep enough of the sample buy almost nothing, the gate that buys most discards 44% of controls and 49% of the impaired for +0.069 specificity and −0.058 sensitivity, the AUC never leaves 0.739 to 0.757, and the equity co-criterion passed — the rule simply does not work. Brevity in a healthy speaker is signal the model is right to weigh, and the specificity ceiling is intrinsic to a sixty-second picture description rather than an artefact of inadequate sampling, which redirects the remedy from data collection to task design (section 5.25). This probe cannot be externally validated, since testing it on the spent corpus would be a second evaluation — the third occasion on which the lock rule has cost the project a result, after the recalibration decision of section 5.4.1 and the feature set frozen before it was complete.",
     "A validity rule on transcript length was the obvious remedy, and it was pre-registered and refused. The 215 development controls above the fixed threshold differ from the 307 correctly passed almost entirely in brevity — 103.2 words against 127.4, information-unit total 11.89 against 16.11 — while age and cognitive score are near-identical, so declaring short recordings non-reportable would change no model, feature or threshold. The grade is GATE-NOT-JUSTIFIED, negative result 10: across a pre-registered grid from 50 to 100 words, gates that keep enough of the sample buy almost nothing, the gate that buys most (90 words) discards 44% of controls and 49% of the impaired for +0.069 specificity and −0.058 sensitivity, the AUC never leaves 0.739 to 0.757, and the equity co-criterion passed — the rule simply does not work. Brevity in a healthy speaker is signal the model is right to weigh, and the specificity ceiling is intrinsic to a sixty-second picture description rather than an artefact of inadequate sampling, which redirects the remedy from data collection to task design (section 5.25). This probe cannot be externally validated, since testing it on the spent corpus would be a second evaluation.")

# 5.13.3
sub1("Three properties order the argument. The rule is prevalence-independent by construction, where every marginal rule of section 5.17 is implicitly a referral-rate rule. It makes specificity the fixed quantity and sensitivity the reported variable. And it needs a normative sample, not patients — a materially cheaper and more ethically tractable collection problem, and one the Libyan pilot already performs: its healthy arm is exactly this normative sample, so the study that validates the Arabic feature set is the study that supplies the threshold. The reported form follows from the same distributions.",
     "Three properties order the argument: the rule is prevalence-independent by construction, where every marginal rule of section 5.17 is implicitly a referral-rate rule; it makes specificity the fixed quantity and sensitivity the reported variable; and it needs a normative sample, not patients, which the Libyan pilot's healthy arm already is, so the study that validates the Arabic feature set is the study that supplies the threshold.")

# 5.24 (new 5.14)
sub1("Averaging k recordings does cut measurement error by root-k in principle — the minimal detectable change falls to 0.202 at two recordings and 0.090 at ten — but root-k assumes independent errors, two recordings minutes apart share the room and the speaker's day, and with error correlation of 0.2 to 0.6 the two-recording figure is 0.222 to 0.256; and it does not make individual tracking viable, since the impaired group drifts +0.0372 per year and detecting one year of average progression would need the error of 59 averaged recordings.",
     "Averaging k recordings cuts measurement error by root-k only under independent errors — two recordings minutes apart share the room and the speaker's day, so the two-recording minimal detectable change is 0.222 to 0.256 rather than 0.202 — and it does not make individual tracking viable, since the impaired group drifts +0.0372 per year and detecting one year of average progression would need the error of 59 averaged recordings.")

# 5.25 (new 5.15)
sub1("What must not be claimed travels with the finding. It says nothing about the picture task for dementia, where it works and where the external evaluation stands; the named best pair is selected in-sample and is an upper-bound claim, while what is robust is that the picture task is worst, its own interval includes chance, and both discourse tasks beat it with intervals excluding zero; the claim that adding the picture task actively degrades a battery does not survive the corrected label rule and is not made; and 18 of the 288 participants (6.25%) change label across visits, including reversion, which places a ceiling on any classifier evaluated against these labels [6].",
     "What must not be claimed travels with the finding: it says nothing about the picture task for dementia, where it works and where the external evaluation stands; the named best pair is selected in-sample and is an upper bound, while what is robust is that the picture task is worst and both discourse tasks beat it with intervals excluding zero; and 18 of the 288 participants (6.25%) change label across visits, including reversion, which places a ceiling on any classifier evaluated against these labels [6].")

# 5.30 (new 5.16) — tighter
replace_section("## 5.30 Further Successor Probes", """
## 5.30 Further Successor Probes

Five further probes belong to the specified successor and are reported at the length their results warrant; each has a row in Table (5.11) with its grade and its repository record, and none changes what the frozen model can claim.

**Domain shift and the pruning remedy that failed (negative result 7).** The shift between the two development cohorts' controls is small on the deployed features — median absolute standardised difference 0.22, none reaching 0.8 — because the 0.930 corpus-separability figure of section 3.2.1 was measured with transcription markup that the deployed 64 exclude. Removing the most-shifted features and retraining throwaway transfer models made the direction that matters, toward the mild-impairment cohort, worse at every k (0.6460 with all features; 0.6424, 0.6421 and 0.6434 with 5, 10 and 15 removed), and the opposite direction's +0.014 is not claimable because the shift ranking saw the target. A remedy aimed at a 0.22 median shift has almost nothing to work on, and drops useful signal with it.

**Information efficiency does not beat information count (negative result 9).** Measured single-feature and directed on the development set, units per hundred words reach 0.6031 against the raw count's 0.7096, a paired participant-clustered difference of −0.1074 [−0.1673, −0.0464] with no resample favouring density; the count is strong and sex-unequal (gap +0.083), density weak and sex-fair (+0.006), and raw word count nearly uninformative (0.5552), so the sex gap of section 5.2.1 lives in the information-content effect itself, and the paper fallback stays a count. The dynamic variants — time to first unit, units by thirty seconds, retrieval slope — are unmeasurable, because the corpus the field trains on carries no word-level timings. A redundancy found on the way: the proportion feature is the count divided by a constant, so the deployed set has 64 columns and 63 distinct quantities, left in place because the model is frozen (section 3.2.2).

**The minimal probe, and a claim withdrawn before it reached the thesis.** The first version of this analysis said that counting words ties the calibrated ensemble on mild-impairment discourse; the claim is withdrawn as a selection artefact, because word count was the argmax over 43 features on the same participants while the ensemble's architecture was fixed before the data were seen. Estimated alike — the best single feature chosen inside each training fold — the fair comparator is 0.6018 against the ensemble's 0.6379, a selection optimism of +0.0455, so the apparatus buys +0.0361 on this target (section 6.1; `results/reconstruction/selection_optimism.json`); word count remains the right hand-computable measure on discourse, its true value lies between about 0.60 and 0.647, and the successor's power calculation runs on the conservative end.

**The age-adjusted posterior and discrimination (negative result 14).** On the combined development set the age-adjusted posterior gains +0.0163 [−0.0127, +0.0446] over the raw score, ADJUSTMENT-NEUTRAL; Pittsburgh's apparent gain of +0.0356 [+0.0035, +0.0694] is not a gain, because its dementia group is 6.6 years older than its controls by construction and under age matching the gain reverses to −0.0346. The layer's value is interpretive, not discriminative — converting a screening score into an age-appropriate absolute risk is a calibration job, which is what it was built for — and family history could not be tested at all, since no corpus in this project records it.

**Vector matching for information units (negative result 15).** Whether word-vector similarity could loosen the scorer's too-tight lists (section 5.5.1) was tested at nine declared thresholds against the twenty hand-scored transcripts: the word-list baseline has 7 false credits and every vector threshold inflates them by an order of magnitude, 74 at the best threshold and 144 at the loosest, grade VECTORS-HURT. Static vectors encode topical relatedness, not synonymy, and everything in a picture description is topically related to everything else, so no cut-off separates a synonym from a co-occurring object; the undercount lives in the six action units, so the remedy is better lists and a dependency-aware action rule, neither deployable without changing the frozen model.
""")

# retire Figures 5.4 and 5.5 (each duplicated by its table)
sub1(", and Figure (5.4) draws it with its intervals.", ".")
sub1("\n**Figure (5.4) : Feature-set ablation with bootstrap intervals; age alone at 0.557 is the floor the speech families are measured against.**\n", "")
sub1("Table (5.12) summarises and Figure (5.5) draws the result.", "Table (5.12) summarises the result (`results/robustness/stability.csv`).")
sub1("\n**Figure (5.5) : Acoustic stability under eight degradations; the 10 dB failure is the basis of the refusal threshold.**\n", "")

t = re.sub(r"\n{3,}", "\n\n", t)
open(P, "w", encoding="utf-8").write(t)
words = len(re.findall(r"\S+", re.sub(r"\|", " ", t.split("**References Cited")[0])))
print("trimmed chapter5.md:", words, "words (incl. tables)")
